Kozlov mikhail lab1
UNN-ITMM-Software/devtools-course-practice pull request #103
Opened 2024-03-27 19:50 UTC by Mishaizlesa

2024-03-27 20:26 UTC, Kuznetsov-Artyom requested changes

2024-03-27 20:26 UTC, Kuznetsov-Artyom commented on lab-guide/topics.md
Исправьте пожалуйста пр так, чтобы не отображался этот файл

После вытягивания актуальной информации с main ветки лучше используйте git rebase

2024-03-31 15:49 UTC, Kuznetsov-Artyom approved these changes

2024-03-31 15:58 UTC, FirewallGR approved these changes

2024-03-31 15:58 UTC, merged