Жбанова Н.С. 381806-2 ЛР1
UNN-ITMM-Software/devtools-course-practice pull request #104
Opened 2021-03-25 08:57 UTC by 381706-2-zhbanova-nadezhda

### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [ ] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [ ] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [ ] Get two approve from your fellow students
- [ ] Take a review from one of the administrators

2021-03-28 11:30 UTC, OnlyDeniko commented
Приглашайте 2-х студентов с потока на ревью

2021-03-28 11:51 UTC, 381706-2-zhbanova-nadezhda commented
@stasyurin @gitlng проверьте пожалуйста

2021-03-28 12:05 UTC, stasyurin approved these changes

2021-03-28 15:33 UTC, OnlyDeniko commented
@stasyurin 
Те, кто аппрувит пулл реквесты без оставления комментариев попадают в специальный список и могут иметь трудности с получением зачёта. Конкретно по данному PR пропущенны очевидные проблемы с дублированием тестов. Так же, можно рекомендовать реализовывать дополнительный функционал (например, добавить параметрический тест).

2021-03-28 15:36 UTC, gitlng approved these changes
Все нормально, но советую заменить второй тест на другой. В нем повторение существующего уже.

2021-03-28 16:55 UTC, stasyurin commented
> @stasyurin
> Те, кто аппрувит пулл реквесты без оставления комментариев попадают в специальный список и могут иметь трудности с получением зачёта. Конкретно по данному PR пропущенны очевидные проблемы с дублированием тестов. Так же, можно рекомендовать реализовывать дополнительный функционал (например, добавить параметрический тест).

Понятно
Не знал этого
На счет дублирования тестов, я сам реализовал в своих проверку на выкидывание исключения при делении на ноль, и думал, что многие это сделали, и так как не было дублирующегося один в один кода, очевидно что просто совпали мысли по общей логике.
А остальные мысли просто посчитал незначительными для высказывания, но раз такие правила, то вот они:
- я бы заменил EXPECT'ы на ASSERT'ы везде, потому что на лекциях говорили, что это в целом более хорошая практика, если у нас не конкретная ситуация, где нужны EXPECT'ы. Здесь явно не такая ситуация, потому что в первых двух тестах после EXPECT'а тесты сразу заканчиваются, а EXPECT подразумевает, что мы ставим его, чтобы в случае провала теста, код продолжал выполняться - тут он не продолжит выполняться (в рамках этого теста ofc) в любом случае;
- я бы заменил значения типа 3.0 или 7.0 на что-то вроде 3.15 и 7.31, потому что программа все-таки поддерживает работу с double'ми, а читая тест, может сложиться ошибочное представление, что почему-то мы можем задавать в качестве входных данных только числа с нулевой дробной частью.

2021-03-29 10:46 UTC, OnlyDeniko commented on modules/complex-number/test/test_zhbanova_nadezhda_complex_number.cpp
> +TEST(Nadezhda_Zhbanova_ComplexNumberTest, difference_and_get_re_get_im) {
[Аналогичный тест ](https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/modules/complex-number/test/test_gogov_vlad_complex_number.cpp#L25) уже в мастере

2021-03-29 17:04 UTC, stasyurin commented on modules/complex-number/test/test_zhbanova_nadezhda_complex_number.cpp
> +    ASSERT_EQ(z0 == z1, true);
Лучше использовать функцию ASSERT_TRUE

2021-03-30 07:47 UTC, OnlyDeniko requested changes

2021-03-30 07:47 UTC, OnlyDeniko commented on modules/complex-number/test/test_zhbanova_nadezhda_complex_number.cpp
> +TEST(Nadezhda_Zhbanova_ComplexNumberTest, create_zero) {
[Тест уже в мастере](https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/modules/complex-number/test/test_kudriavtsev_alexandr_complex_number.cpp#L8).
Просьба проверять уже существующие тесты

2021-03-30 09:10 UTC, OnlyDeniko approved these changes

2021-03-30 09:11 UTC, merged