Added tests for complex-numbers
UNN-ITMM-Software/devtools-course-practice pull request #105
Opened 2021-03-27 08:19 UTC by gitlng

### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [ ] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [ ] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [ ] Get two approve from your fellow students
- [ ] Take a review from one of the administrators

2021-03-27 08:29 UTC, gitlng commented
@Talesard , @katsum25

2021-03-27 09:03 UTC, gitlng commented
@Talesard , @katsum25

2021-03-27 09:03 UTC, katsum25 commented
Тесты, подобные summing, division, multiplying, subtraction, уже присутствуют в мастере.

2021-03-27 10:03 UTC, katsum25 commented on modules/complex-number/test/test_tkachev_alexey_complex_number.cpp
> +TEST(Tkachev_Alexey_ComplexNumberTest, summing) {
Дубликат теста в мастере
https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/37d19db55160588051ba558bf352adb7bf212da5/modules/complex-number/test/test_gogov_vlad_complex_number.cpp#L7

2021-03-27 10:03 UTC, katsum25 commented on modules/complex-number/test/test_tkachev_alexey_complex_number.cpp
> +TEST(Tkachev_Alexey_ComplexNumberTest, subtraction) {
`Дубликат теста в мастере
https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/37d19db55160588051ba558bf352adb7bf212da5/modules/complex-number/test/test_gogov_vlad_complex_number.cpp#L25

2021-03-27 10:03 UTC, katsum25 commented on modules/complex-number/test/test_tkachev_alexey_complex_number.cpp
> +TEST(Tkachev_Alexey_ComplexNumberTest, division) {
Дубликат теста в мастере
https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/37d19db55160588051ba558bf352adb7bf212da5/modules/complex-number/test/test_gogov_vlad_complex_number.cpp#L61

2021-03-27 10:03 UTC, katsum25 commented on modules/complex-number/test/test_tkachev_alexey_complex_number.cpp
> +TEST(Tkachev_Alexey_ComplexNumberTest, multiplying) {
Дубликат теста в мастере
https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/37d19db55160588051ba558bf352adb7bf212da5/modules/complex-number/test/test_gogov_vlad_complex_number.cpp#L43

2021-03-27 11:48 UTC, gitlng commented
@Talesard , @katsum25

2021-03-27 12:00 UTC, katsum25 approved these changes

2021-03-27 14:50 UTC, Talesard approved these changes
gj

Можно вынести сумму из assert, но вроде такой вариант тоже норм.
```C++
ASSERT_EQ(complex_number_1 + complex_number_2, true_complex_number);
```

2021-03-29 06:27 UTC, streltsova-yana requested changes

2021-03-29 06:27 UTC, streltsova-yana commented on modules/complex-number/test/test_tkachev_alexey_complex_number.cpp
> +    ASSERT_EQ(complex_number_1 + complex_number_2, true_complex_number);
В этом и последующих тестах в ASSERT_EQ сначала ожидаемое значение, а потом фактическое

2021-03-29 06:30 UTC, streltsova-yana approved these changes

2021-03-29 06:31 UTC, merged