Лебедев А. В. 381803-2 ЛР1
UNN-ITMM-Software/devtools-course-practice pull request #107
Opened 2021-03-28 13:22 UTC by andrewkin77

### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [ ] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [ ] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [ ] Get two approve from your fellow students
- [ ] Take a review from one of the administrators

2021-03-28 15:01 UTC, BrandonRTL requested changes

2021-03-28 15:18 UTC, BrandonRTL approved these changes
My job here is done

2021-03-28 17:24 UTC, dmitrybezro approved these changes
Отсутствие отступов в 3-м тесте негативно сказывается на читабельности кода.

2021-03-28 17:43 UTC, dkurt commented on modules/complex-number/test/test_lebedev_andrew_complex_number.cpp
> +     ASSERT_EQ(z1.getRe(), re);
Мы обсудили этот вопрос в чате, желательно использовать Assert везде, чтобы избежать падений исполнения тестов (пример есть в чате).

2021-03-28 17:44 UTC, dkurt commented
@dmitrybezro, было бы удобнее если комментарии оставлялись с прикреплением на конкретную строку.

2021-03-28 17:52 UTC, andrewkin77 commented on modules/complex-number/test/test_lebedev_andrew_complex_number.cpp
> +     ASSERT_EQ(z1.getRe(), re);
@dkurt Глеб имел ввиду, что сначала идёт ожидаемое значение, а потом мой результат. У меня наоборот было. Так у меня везде assert

2021-03-29 06:07 UTC, WerWebWer approved these changes

2021-03-29 06:08 UTC, merged