Колесин А. С. 381806-2 ЛР1
UNN-ITMM-Software/devtools-course-practice pull request #109
Opened 2021-03-29 07:08 UTC by palisarbaro

2021-03-29 08:01 UTC, palisarbaro commented
@stasyurin @gitlng  проверьте пожалуйста

2021-03-29 09:32 UTC, stasyurin commented
[такой же совет по поводу замены int'ов на double'ы](https://github.com/UNN-ITMM-Software/devtools-course-practice/pull/104#issuecomment-808924024)

2021-03-29 09:46 UTC, stasyurin commented on modules/complex-number/test/test_kolesin_andrey_complex_number.cpp
> +TEST(Kolesin_Andrey_ComplexNumberTest, NegSqr) {
хорошим тоном считается разделять тесты пустой строкой

2021-03-29 19:59 UTC, gitlng requested changes
Сами тесты нормальные по смыслу, но не очень по оформлению. Повысьте читабельность, пожалуйста. А именно: 1. Замените однобуквенные переменные на полноценные слова, имеющие смысл в данном контексте.2. Лучше сначала объявить переменные, например,
 double re = ..., double im = ...,
а потом уже их подставлять при создании переменных класса. (Но это все же скорее придирка, дело ваше). 3. Поменяйте название 3-го теста на понятное. Оно совсем никак не описывает, что делает сам тест. В сочетании, с именованием переменных третий тест трудно разобрать. 
4. Да и в целом, все названия тестов должны пояснять нормально, что они делают. Я бы посоветовал немного подробнее их написать.

2021-03-30 05:38 UTC, stasyurin approved these changes
Меня все устраивает

2021-03-30 05:38 UTC, stasyurin commented on modules/complex-number/test/test_kolesin_andrey_complex_number.cpp
> +    ComplexNumber a(-5.2, 0);
посмотрел [образец](https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/3b8f8039376c4622ce78fd9a1275ab4a78b58fd3/modules/complex-number/test/test_simple.cpp), там тоже 0, а не 0.0, так что думаю можно оставить так

2021-03-30 06:23 UTC, gitlng approved these changes
Все нормально, одобряю. Но я все же бы не советовал использовать имена a, b для переменных. Лучше first, second. Но на читабельность в данный момент у вас это не влияет, так что я как минус это не буду ставить. Но не советую так писать.

2021-03-30 14:38 UTC, WerWebWer approved these changes

2021-03-30 14:38 UTC, merged