Салаев - Лабораторная работа #1
UNN-ITMM-Software/devtools-course-practice pull request #109
Opened 2024-03-28 18:19 UTC by Handle-less

2024-03-28 20:56 UTC, Kuznetsov-Artyom reviewed
Добавьте пожалуйста тесты с дробными значениями

2024-03-29 15:28 UTC, FirewallGR commented
Добавьте пожалуйста описание задачи

2024-03-29 15:44 UTC, FirewallGR requested changes
Добавьте пожалуйста проверку деления на 0

2024-03-29 16:08 UTC, Kuznetsov-Artyom approved these changes

2024-03-31 15:49 UTC, FirewallGR approved these changes

2024-03-31 15:49 UTC, merged