Виденева-Лабораторная работа#1
UNN-ITMM-Software/devtools-course-practice pull request #111
Opened 2024-03-29 13:51 UTC by katrin000

Виденева Екатерина ПМИ3 Лабораторная работа 1

2024-03-29 14:09 UTC, Kuznetsov-Artyom approved these changes

2024-03-29 15:27 UTC, FirewallGR commented
Добавьте пожалуйста описание в readme

2024-03-29 15:46 UTC, FirewallGR requested changes
Добавьте пожалуйста тесты деления на 0

2024-03-29 17:06 UTC, Kuznetsov-Artyom approved these changes
LGTM

2024-03-31 15:49 UTC, FirewallGR approved these changes

2024-03-31 15:49 UTC, merged