Прокофьева Е.А. 381806-2 ЛР№1.
UNN-ITMM-Software/devtools-course-practice pull request #112
Opened 2021-03-29 13:35 UTC by prokofeval

### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [ ] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [ ] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [ ] Get two approve from your fellow students
- [ ] Take a review from one of the administrators

2021-03-29 13:44 UTC, prokofeval commented
@diligentConcernist , @WolfCub15 Проверьте, пожалуйста.

2021-03-29 17:11 UTC, diligentConcernist commented on modules/complex-number/test/test_prokofeva_elizaveta_complex_number.cpp
> +    double im = 45.3435;
Хоть и очевидно, что присваивание работает, но на мой взгляд лучше взять более "рандомные" начальные значения:
```suggestion
    double re = 69.4266;
    double im = -6.7813;
```

2021-03-29 17:11 UTC, diligentConcernist commented on modules/complex-number/test/test_prokofeva_elizaveta_complex_number.cpp
> +TEST(Prokofeva_Liza_Complex_Number, Test_Equal_Mark) {
В этом тесте ты, по большей части, проверяешь присваивание. Так что лучше сделать соответствующее название:
```suggestion
TEST(Prokofeva_Liza_Complex_Number, Test_Assignment) {
```

2021-03-29 21:36 UTC, WolfCub15 requested changes

2021-03-30 09:35 UTC, WolfCub15 requested changes

2021-03-30 09:35 UTC, WolfCub15 commented on modules/complex-number/test/test_prokofeva_elizaveta_complex_number.cpp
> +}
данный тест уже тоже присутствует в [мастере](https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/modules/complex-number/test/test_shagov_maksim_complex_number.cpp#L7)

2021-03-30 09:53 UTC, diligentConcernist approved these changes
У меня замечаний больше нет.

2021-03-30 09:54 UTC, WolfCub15 approved these changes

2021-03-30 10:26 UTC, OnlyDeniko approved these changes

2021-03-30 10:27 UTC, merged