Зайцев А.Р. 381806-3 ЛР1
UNN-ITMM-Software/devtools-course-practice pull request #113
Opened 2021-03-29 20:10 UTC by zaitcev-andrey

### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [ ] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [ ] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [ ] Get two approve from your fellow students
- [ ] Take a review from one of the administrators

2021-03-29 20:42 UTC, zaitcev-andrey commented
@sergey-makarichev @Nikita23456 Проверьте, пожалуйста

2021-03-29 20:55 UTC, Nikita23456 commented on modules/complex-number/test/test_zaitsev_andrey_complex_number.cpp
> +  ComplexNumber num4(re4, im4);
Для сокращения кода в  данной реализации лучше сразу передавать значения в параметры для создания комплексного числа.

2021-03-29 21:00 UTC, sergey-makarichev commented on modules/complex-number/test/test_zaitsev_andrey_complex_number.cpp
> +  ASSERT_EQ(num.getIm(), im);
Сначала должен идти ожидаемый результат, затем фактический.

2021-03-29 21:00 UTC, sergey-makarichev commented on modules/complex-number/test/test_zaitsev_andrey_complex_number.cpp
> +    testing::Values(8.0, 12.0)));
Можно было бы проверить более "экзотические" значения вещественных чисел.

2021-03-30 08:39 UTC, sergey-makarichev commented on modules/complex-number/test/test_zaitsev_andrey_complex_number.cpp
> +#include "include/complex_number.h"
Желательно разделить подключение заголовочных файлов пустыми строками и расположить в порядке согласно  Google C++ Code Style.

2021-03-30 09:19 UTC, zaitcev-andrey commented on modules/complex-number/test/test_zaitsev_andrey_complex_number.cpp
> +#include "include/complex_number.h"
Да, точно, забыл про это. Сейчас исправлю.

2021-03-30 09:34 UTC, streltsova-yana commented
Для ускорения прохождения ревью вы можете пригласить сокурсников посмотреть ваш PR, упомянув их в комментариях (или попросить тех, кто уже смотрел, снова посмотреть новые изменения и их заапрувить)

[See more details](https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

2021-03-30 10:14 UTC, Nikita23456 approved these changes

2021-03-30 10:19 UTC, sergey-makarichev approved these changes

2021-03-30 12:22 UTC, streltsova-yana requested changes

2021-03-30 12:22 UTC, streltsova-yana commented on modules/complex-number/test/test_zaitsev_andrey_complex_number.cpp
> +  testing::Combine(
Из-за Combine (это декартово произведение - всевозможные комбинации из набора параметров) тесты запускаются 16 раз, точно ли ожидается такое поведение? Думаю, что для параметрического теста будет достаточно и 4х запусков

2021-03-30 12:45 UTC, zaitcev-andrey commented on modules/complex-number/test/test_zaitsev_andrey_complex_number.cpp
> +  testing::Combine(
Соглашусь, сейчас исправлю.

2021-03-30 13:05 UTC, streltsova-yana approved these changes

2021-03-30 13:06 UTC, merged