Кириченко Н. А. 381806-3 ЛР1
UNN-ITMM-Software/devtools-course-practice pull request #116
Opened 2021-03-29 21:34 UTC by Nikita23456

### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [ ] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [ ] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [ ] Get two approve from your fellow students
- [ ] Take a review from one of the administrators

2021-03-29 21:37 UTC, Nikita23456 commented
@zaitcev-andrey @sergey-makarichev посмотрите , пожалуйста.

2021-03-29 21:43 UTC, zaitcev-andrey commented on modules/complex-number/test/test_kirichenko_nikita_complex_number.cpp
> +#include "include/complex_number.h"
Лучше разделить заголовочные файлы пустыми строками.

2021-03-29 21:43 UTC, zaitcev-andrey commented on modules/complex-number/test/test_kirichenko_nikita_complex_number.cpp
> +}
Этот тест очень похож на прошлый, лучше напиши вместо него другой. Было бы прекрасно, если бы он был параметрическим.

2021-03-30 05:45 UTC, dkurt commented on modules/complex-number/test/test_kirichenko_nikita_complex_number.cpp
> +#include "include/complex_number.h"
Порядок тоже желательно по [Google C++ Code Style](https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes) сделать: 
> Related header, C system headers, C++ standard library headers, other libraries' headers, your project's headers.

```cpp
#include <cmath>

#include <gtest/gtest.h>

#include "include/complex_number.h"
```

2021-03-30 07:31 UTC, sergey-makarichev commented on modules/complex-number/test/test_kirichenko_nikita_complex_number.cpp
> +TEST(Kirichenko_Nikita_ComplexNumberTest, Comparison) {
можно было бы написать более информативное название теста

2021-03-30 07:31 UTC, sergey-makarichev commented on modules/complex-number/test/test_kirichenko_nikita_complex_number.cpp
> +    ComplexNumber res(-26.0, 82.0);
не очень понятно, откуда взялись такие параметры конструктора

2021-03-30 11:39 UTC, Nikita23456 commented on modules/complex-number/test/test_kirichenko_nikita_complex_number.cpp
> +TEST(Kirichenko_Nikita_ComplexNumberTest, Comparison) {
Эти параметры - заранее посчитанный вручную результат.

2021-03-30 11:48 UTC, Nikita23456 commented on modules/complex-number/test/test_kirichenko_nikita_complex_number.cpp
> +    ComplexNumber res(-26.0, 82.0);
Эти параметры - заранее посчитанный вручную результат.

2021-03-30 11:49 UTC, zaitcev-andrey approved these changes
Мне больше добавить нечего, всё хорошо.

2021-03-30 11:50 UTC, sergey-makarichev approved these changes

2021-03-30 13:20 UTC, streltsova-yana requested changes

2021-03-30 13:20 UTC, streltsova-yana commented on modules/complex-number/test/test_kirichenko_nikita_complex_number.cpp
> +#include <cmath>
Заголовочные файлы С++ между собой не следует отделять пустой строкой
[See more details](https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes)

2021-03-30 13:20 UTC, streltsova-yana commented on modules/complex-number/test/test_kirichenko_nikita_complex_number.cpp
> +TEST_P(Kirichenko_Nikita_ComplexNumberTestTest_Param, Operations_Test) {
Похожий [тест](https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/86516fbb963a0017942695e7413e94bb645ebe68/modules/complex-number/test/test_zoreev_mikhail_complex_number.cpp#L38) уже есть в мастере

2021-03-30 13:56 UTC, streltsova-yana requested changes

2021-03-30 13:56 UTC, streltsova-yana commented on modules/complex-number/test/test_kirichenko_nikita_complex_number.cpp
> +TEST_P(Kirichenko_Nikita_ComplexNumberTestTest_Param, Operations_Test) {
Похожий [тест](https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/86516fbb963a0017942695e7413e94bb645ebe68/modules/complex-number/test/test_pronkin_dmitry_complex_number.cpp#L38) также есть в мастере

2021-03-30 14:19 UTC, Nikita23456 commented on modules/complex-number/test/test_kirichenko_nikita_complex_number.cpp
> +TEST_P(Kirichenko_Nikita_ComplexNumberTestTest_Param, Operations_Test) {
Надеюсь подобного теста нет в мастере...

2021-03-30 14:43 UTC, streltsova-yana approved these changes

2021-03-30 14:44 UTC, merged