Гущин А.А. 381806-3 ЛР1
UNN-ITMM-Software/devtools-course-practice pull request #122
Opened 2021-03-30 11:41 UTC by ArtyomGi

### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [ ] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [ ] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [ ] Get two approve from your fellow students
- [ ] Take a review from one of the administrators

2021-03-30 11:44 UTC, ArtyomGi commented
@Andrey0948 @Vladislavbul Сделайте ревью, пожалуйста.

2021-03-30 16:37 UTC, Andrey0948 requested changes
Всё хорошо, замечаний нет
Только в первом тесте

2021-03-30 16:37 UTC, Andrey0948 commented on modules/complex-number/test/test_gushchin_artem_complex_number.cpp
> +    EXPECT_EQ(re, z.getRe());
Вместо EXPECT_EQ лучше писать ASSERT_EQ, т.к. после EXPECT_EQ будет продолжать выполняться тест, что может привести к нежелательным эффектам.

2021-03-30 16:37 UTC, Andrey0948 commented on modules/complex-number/test/test_gushchin_artem_complex_number.cpp
> +    EXPECT_EQ(im, z.getIm());
Аналогично замечанию выше.

2021-03-30 18:49 UTC, Vladislavbul commented
Добавить нечего, работа выполнена хорошо, исправь рекомендации Андрея и все.

2021-03-30 20:06 UTC, Andrey0948 commented on modules/complex-number/test/test_gushchin_artem_complex_number.cpp
> +TEST_P(Gushchin_Artem_Operations_ComplexNumberTest, Sum_Operation) {
По названию теста не совсем ясно что он делает, лучше заменить на более понятное
У теста Diff, Mult аналогично.

2021-03-31 13:50 UTC, ArtyomGi commented
@Vladislavbul @Andrey0948 Обновлено

2021-03-31 14:09 UTC, Andrey0948 approved these changes
Просто во

2021-03-31 15:21 UTC, Vladislavbul approved these changes
Хорошая работа.

2021-03-31 18:26 UTC, WerWebWer approved these changes

2021-03-31 18:27 UTC, merged