Кузнецов Н. С. 381806-3 ЛР1
UNN-ITMM-Software/devtools-course-practice pull request #123
Opened 2021-03-30 12:12 UTC by kuznetsov-ns

### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [ ] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [ ] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [ ] Get two approve from your fellow students
- [ ] Take a review from one of the administrators

2021-03-30 12:13 UTC, kuznetsov-ns commented
@ArtyomGi @Vladislavbul сделайте ревью

2021-03-30 16:24 UTC, ArtyomGi requested changes

2021-03-30 16:24 UTC, ArtyomGi commented on modules/complex-number/test/test_kuznetsov_nikita_complex_number.cpp
> +#include <gtest/gtest.h>
Заголовочные файлы желательно разделять по блокам пустой строкой. Блоки с пользовательскими заголовочными, стандартными заголовочными файлами C и C++, и заголовочными с текущей библиотеки должны располагаться отдельно

2021-03-30 16:24 UTC, ArtyomGi commented on modules/complex-number/test/test_kuznetsov_nikita_complex_number.cpp
> +  ComplexNumber z2(1.0, 3.0);
Желательно сделать параметризованные тесты. Они дают больший тестовый функционал, позволяя проверить множество значений. Возможно, что на каких-то значениях тесты будут проходить, а на некоторых нет, поэтому желательно расширить количество тестовых значений с помощью параметризации.

2021-03-30 16:24 UTC, ArtyomGi commented on modules/complex-number/test/test_kuznetsov_nikita_complex_number.cpp
> +  ComplexNumber z2(1.0, 3.0);
Аналогичная ситуация с комментарием выше, этот тест желательно сделать параметризованным.

2021-03-30 16:24 UTC, ArtyomGi commented on modules/complex-number/test/test_kuznetsov_nikita_complex_number.cpp
> +TEST(Kuznetsov_Nikita_ComplexNumberTest, Can_Assign_Element) {
Assign в названии теста немного неточно выражает его суть. Обычно под assign понимается присваивание через operator= (оператор присваивания), здесь же проверяется корректность конструктора копирования

2021-03-31 10:36 UTC, Vladislavbul approved these changes

2021-03-31 13:48 UTC, ArtyomGi requested changes

2021-03-31 13:48 UTC, ArtyomGi commented on modules/complex-number/test/test_kuznetsov_nikita_complex_number.cpp
> +#include <tuple>
Аналогично с комментарием выше, желательно tuple и complex_number.h разделить

2021-03-31 13:48 UTC, ArtyomGi commented on modules/complex-number/test/test_kuznetsov_nikita_complex_number.cpp
> +TEST_P(Kuznetsov_Nikita_ComplexNumberTest_param, Can_Sum_Elements) {
Не выдержан стиль названий тестов. Желательно их выдерживать в одном стиле, т.е. в этом случае Param с заглавной буквы

2021-03-31 13:48 UTC, ArtyomGi commented on modules/complex-number/test/test_kuznetsov_nikita_complex_number.cpp
> +TEST_P(Kuznetsov_Nikita_ComplexNumberTest_param, Can_Multiply_Elements) {
Аналогично замечанию выше насчет стиля

2021-03-31 13:48 UTC, ArtyomGi commented on modules/complex-number/test/test_kuznetsov_nikita_complex_number.cpp
> +    testing::Values(5.0, -4.0))
На мой взгляд маловато значений. Можно еще добавить случай с одним/двумя аргументами, равными нулю

2021-03-31 16:24 UTC, streltsova-yana requested changes

2021-03-31 16:24 UTC, streltsova-yana commented on modules/complex-number/test/test_kuznetsov_nikita_complex_number.cpp
> +  testing::Combine(
Из-за Combine (это декартово произведение - всевозможные комбинации из набора параметров) тесты запускаются 16 раз, точно ли ожидается такое поведение? Думаю, что для параметрического теста будет достаточно и 4х запусков

2021-03-31 16:24 UTC, streltsova-yana commented on modules/complex-number/test/test_kuznetsov_nikita_complex_number.cpp
> +TEST(Kuznetsov_Nikita_ComplexNumberTest, Can_Copy_Element) {
Похожий [тест](https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/4f4c987ce2ee602e835b9b94ece03f3590abbafc/modules/complex-number/test/test_Belik_Julia_complex_number.cpp#L8) уже есть в мастере

2021-03-31 17:06 UTC, merged