Киселева А.С. 381806-2 ЛР1
UNN-ITMM-Software/devtools-course-practice pull request #125
Opened 2021-03-30 12:57 UTC by netweel

### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [ ] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [ ] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [ ] Get two approve from your fellow students
- [ ] Take a review from one of the administrators

2021-03-30 13:01 UTC, netweel commented
@Talesard

2021-03-30 13:24 UTC, OlgaMakesThings commented
Не совсем читаемый код. Попробуй разбить код тестов на секции, разделяя их пустыми строками

2021-03-30 14:45 UTC, Talesard requested changes
- Нужно поменять EXPECT_EQ на ASSERT_EQ
- Стоят 2 пустые строки в конце файла вместо одной (просто кодстайл)
- Abs_Of_Conjugate_Numbers -  ± такой тест уже есть: https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/2c87dbdd62748941faadb9a304a212a5debebebb/modules/complex-number/test/test_bezrodnov_dmitry_complex_number.cpp#L23

2021-03-31 08:30 UTC, Talesard approved these changes
GJ

2021-03-31 18:54 UTC, WerWebWer approved these changes

2021-03-31 18:54 UTC, merged