Гапон А.К. 381806-3 ЛР1
UNN-ITMM-Software/devtools-course-practice pull request #128
Opened 2021-03-30 18:14 UTC by Andrey0948

### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [ ] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [ ] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [ ] Get two approve from your fellow students
- [ ] Take a review from one of the administrators

2021-03-30 18:20 UTC, Andrey0948 commented
@ArtyomGi @Vladislavbul сделайте ревью, пжл

2021-03-30 18:41 UTC, ArtyomGi requested changes

2021-03-30 18:41 UTC, ArtyomGi commented on modules/complex-number/test/test_gapon_andrey_complex_number.cpp
> +#include <cmath>
Насколько вижу, лишний #include. По коду не используются функции из него. Если не пропускаю что-то, то лучше убрать

2021-03-30 18:41 UTC, ArtyomGi commented on modules/complex-number/test/test_gapon_andrey_complex_number.cpp
> +    ComplexNumber num1 = (a + b) * c;
Здесь желательно разделить логические части кода в соответствии с блоками Arrange, Act, Assert. Без разделения тяжело понимать, что делает тест

2021-03-30 18:41 UTC, ArtyomGi commented on modules/complex-number/test/test_gapon_andrey_complex_number.cpp
> +TEST(Gapon_Andrey_ComplexNumberTest, Calculation) {
"Calculation" довольно невыразительное название теста. Довольно сложно по такому названию понять, что конкретно делает этот тест. Стоит назвать так, чтобы название конкретно описывало, что проверяется

2021-03-30 18:41 UTC, ArtyomGi commented on modules/complex-number/test/test_gapon_andrey_complex_number.cpp
> +TEST_P(Gapon_Andrey_ComplexNumberTest_Param, associative_Test) {
Стоит придерживаться единого стиля написания названий тестов. "associative_Test" немного выбивается из общего стиля

2021-03-30 18:41 UTC, ArtyomGi commented on modules/complex-number/test/test_gapon_andrey_complex_number.cpp
> +    distributive_Test) {
Аналогично комментарию выше, стоит придерживаться единого стиля написания названий

2021-03-30 18:41 UTC, ArtyomGi commented on modules/complex-number/test/test_gapon_andrey_complex_number.cpp
> +    EXPECT_EQ(res, num1);
Желательнее применять ASSERT_EQ вместо EXPECT_EQ

2021-03-31 09:10 UTC, Vladislavbul reviewed
Мне добавить нечего. Артем указал на все недостатки.

2021-03-31 09:30 UTC, Vladislavbul approved these changes

2021-03-31 13:44 UTC, ArtyomGi requested changes

2021-03-31 13:44 UTC, ArtyomGi commented on modules/complex-number/test/test_gapon_andrey_complex_number.cpp
> +        std::make_tuple(1.0, 2.0, 3.0, 4.0, 5.0, 6.0)));
Значения повторяются с первой строкой. Нужно либо убрать, либо заменить на другие

2021-03-31 13:59 UTC, ArtyomGi approved these changes
Замечаний больше не имею, все хорошо.
Good Job!

2021-03-31 18:27 UTC, WerWebWer approved these changes

2021-03-31 18:28 UTC, merged