Гурылев Н.С. 381806-3 ЛР1
UNN-ITMM-Software/devtools-course-practice pull request #129
Opened 2021-03-30 18:18 UTC by gurylev-nikita

### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [ ] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [ ] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [ ] Get two approve from your fellow students
- [ ] Take a review from one of the administrators

2021-03-30 18:21 UTC, gurylev-nikita commented
@Vladislavbul @kuznetsov-ns сделайте ревью, пожалуйста.

2021-03-30 18:27 UTC, Vladislavbul commented on modules/complex-number/test/test_gurylev_nikita_complex_number.cpp
> +#include <gtest/gtest.h>
Заголовочные файлы желательно разделять по блокам пустой строкой.

2021-03-31 09:15 UTC, Vladislavbul commented on modules/complex-number/test/test_gurylev_nikita_complex_number.cpp
> +    ASSERT_DOUBLE_EQ(2.0, result.getIm());
Следует разделить логические части кода по блокам.

2021-03-31 10:38 UTC, kuznetsov-ns commented on modules/complex-number/test/test_gurylev_nikita_complex_number.cpp
> +    ASSERT_EQ(result1, result2);
Раздели логические части кода новой строкой, также этот тест лучше сделать параметризованным

2021-03-31 17:54 UTC, Vladislavbul approved these changes

2021-03-31 18:14 UTC, kuznetsov-ns approved these changes
Замечаний нет

2021-03-31 20:16 UTC, streltsova-yana requested changes

2021-03-31 20:16 UTC, streltsova-yana commented on modules/complex-number/test/test_gurylev_nikita_complex_number.cpp
> +TEST_P(Gurylev_Nikita_ComplexNumberTest_Param, ComparisonOperation) {
Похожий [тест](https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/c8aa5ec625e551ef9ba8807efd1f280b78c1c7b7/modules/complex-number/test/test_kirichenko_nikita_complex_number.cpp#L29) уже есть в мастере

2021-04-01 14:10 UTC, streltsova-yana commented
Необходимо обновить локально main и сделать с ним rebase:
`git checkout main`
`git pull remote main`
`git rebase main my_branch_name`
`git push -f origin my_branch_name`

2021-04-01 17:50 UTC, streltsova-yana approved these changes

2021-04-01 17:50 UTC, merged