Волкова А.Д. 381806-2. ЛР2.
UNN-ITMM-Software/devtools-course-practice pull request #157
Opened 2021-04-13 09:20 UTC by WolfCub15

### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [ ] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [ ] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [ ] Get two approve from your fellow students
- [ ] Take a review from one of the administrators

2021-04-13 10:48 UTC, dkurt commented on modules/Kruskal_algorithm/test/test_Kruskal_algorithm.cpp
> +TEST(Kruskal_algorithm, Сonstructor) {
CI blames this line on Windows:
```
D:\a\devtools-course-practice\devtools-course-practice\modules\Kruskal_algorithm\test\test_Kruskal_algorithm.cpp(11,1): error C3872: '0xa1': this character is not allowed in an identifier [D:\a\devtools-course-practice\devtools-course-practice\dashboard\build\modules\Kruskal_algorithm\test\test_Kruskal_algorithm.vcxproj]
```
Can you please rewrite this line just to check if there is no non-ASCII characters?

2021-04-13 10:54 UTC, dkurt commented on modules/Kruskal_algorithm/include/Kruskal_algorithm.h
> +};
If you able you may try to document the class so it will appear in the [docs](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html).

Just add a line to https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/docs/Doxyfile.

2021-04-13 12:35 UTC, OnlyDeniko reviewed
Делаю ревью как **студент**, а не админ.
Посмотри, пожалуйста, на code coverage, возможно придется добавить тесты, чтобы покрыть всё по максимуму

2021-04-13 12:35 UTC, OnlyDeniko commented on modules/Kruskal_algorithm/include/Kruskal_algorithm.h
> +    explicit Graph(const int n);
Мне кажется логично будет убрать конструктор по умолчанию и сделать во втором конструкторе параметр по умолчанию. Смысл и реализация второго конструктора не изменится

```suggestion
    explicit Graph(const int n = 0);
```

2021-04-13 12:35 UTC, OnlyDeniko commented on modules/Kruskal_algorithm/include/Kruskal_algorithm.h
> +    ~Graph();
Поскольку внутри класса используются только контейнеры STL и целочисленные переменные, то деструктор можно сделать по умолчанию, логика нарушена не будет
```suggestion
    ~Graph() = default;
```

2021-04-13 12:35 UTC, OnlyDeniko commented on modules/Kruskal_algorithm/src/Kruskal_algorithm.cpp
> +}
Проверка на самоприсваивание
```suggestion
Graph& Graph::operator=(const Graph& tmp) {
    if (this == &tmp) return *this;
    n = tmp.get_n();
    G = tmp.get_G();
    MST = tmp.get_MST();
    parent = tmp.get_parent();
    return *this;
}
```

2021-04-13 12:35 UTC, OnlyDeniko commented on modules/Kruskal_algorithm/src/Kruskal_algorithm.cpp
> +                                 parent(tmp.get_parent()) {}
Внутри конструктора можем напрямую достучаться до полей класса
```suggestion
Graph::Graph(const Graph& tmp) : n(tmp.n),
                                 G(tmp.G),
                                 MST(tmp.MST),
                                 parent(tmp.parent) {}
```

2021-04-13 12:35 UTC, OnlyDeniko commented on modules/Kruskal_algorithm/src/Kruskal_algorithm.cpp
> +    MST.clear();
Нет нужды делать clear(), эти контейнеры и так пустые по умолчанию

2021-04-13 12:35 UTC, OnlyDeniko commented on modules/Kruskal_algorithm/src/Kruskal_algorithm.cpp
> +    }
Можно избавиться от функции make_set(), используя std::iota
```suggestion
    std::iota(parent.begin(), parent.end(), 0);
```

2021-04-13 12:35 UTC, OnlyDeniko commented on modules/Kruskal_algorithm/src/Kruskal_algorithm.cpp
> +}
Сделай, пожалуйста, название аргумента функции понятным, например `vertex`

2021-04-13 12:35 UTC, OnlyDeniko commented on modules/Kruskal_algorithm/src/Kruskal_algorithm.cpp
> +}
Для того, чтобы каждый раз не создавать генератор рандомных чисел в вызове данной функции, можно воспользоваться эвристикой объединения по рангу, либо сделать генератор приватным полем. Впринципе, не критично

2021-04-13 13:56 UTC, OnlyDeniko approved these changes
LGTM 💯

2021-04-13 17:05 UTC, WolfCub15 commented
@vla5924 посмотри, пожалуйста

2021-04-15 15:37 UTC, vla5924 requested changes

2021-04-15 15:37 UTC, vla5924 commented on modules/Kruskal_algorithm/src/Kruskal_algorithm.cpp
> +    n = size;
Лучше поместить безусловное присваивание в список инициализации.

2021-04-15 15:37 UTC, vla5924 commented on modules/Kruskal_algorithm/include/Kruskal_algorithm.h
> +    std::vector<int> get_parent() const;
Правильнее возвращать ссылки на константы:
```suggestion
    const std::vector<std::pair<int, edge>>& get_G() const;
    const std::vector<std::pair<int, edge>>& get_MST() const;
    const std::vector<int>& get_parent() const;
```

2021-04-15 15:37 UTC, vla5924 commented on modules/Kruskal_algorithm/src/Kruskal_algorithm.cpp
> +#include <numeric>
_MINOR:_ можно отсортировать список заголовков по алфавиту.

2021-04-15 15:37 UTC, vla5924 commented on modules/Kruskal_algorithm/src/Kruskal_algorithm.cpp
> +    return parent[vertex] = find_set(parent[vertex]);
Лучше не использовать подобные конструкции без видимой причины, а писать отдельными выражениями:
```suggestion
    parent[vertex] = find_set(parent[vertex]);
    return parent[vertex];
```

2021-04-15 15:37 UTC, vla5924 commented on modules/Kruskal_algorithm/src/Kruskal_algorithm.cpp
> +    n = vertex_n;
Здесь не нужна проверка для `vertex_n`?

2021-04-16 13:07 UTC, WolfCub15 commented
@vla5924

2021-04-17 19:52 UTC, vla5924 approved these changes

2021-04-19 08:55 UTC, WerWebWer approved these changes

2021-04-19 08:56 UTC, merged