Белик Ю.А. 381806-1. ЛР2.
UNN-ITMM-Software/devtools-course-practice pull request #158
Opened 2021-04-15 07:12 UTC by BelikJulia

### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [ ] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [ ] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [ ] Get two approve from your fellow students
- [ ] Take a review from one of the administrators

2021-04-15 07:14 UTC, dkurt commented on modules/triangle-point/include/TrianglePoint.h
> +    bool isInside(std::pair<double, double>  x);
Please add an empty line between the methods.

2021-04-19 09:10 UTC, ParanichevaAlyona approved these changes
Хорошая работа

2021-04-19 09:12 UTC, SMolotkova commented
Все отлично

2021-04-19 17:42 UTC, streltsova-yana requested changes

2021-04-19 17:42 UTC, streltsova-yana commented on modules/triangle-point/CMakeLists.txt
> +add_subdirectory(test)
Необходимо добавить пустую строку в конец файла

2021-04-19 17:42 UTC, streltsova-yana commented on modules/triangle-point/src/CMakeLists.txt
> +set(LIBRARY_DEPS "${LIBRARY_DEPS};${target}" PARENT_SCOPE)
Необходимо добавить пустую строку в конец файла

2021-04-19 17:42 UTC, streltsova-yana commented on modules/triangle-point/src/TrianglePoint.cpp
> +    c = _c;
Лучше поместить безусловное присваивание в список инициализации

2021-04-19 17:42 UTC, streltsova-yana commented on modules/triangle-point/test/CMakeLists.txt
> +    LABELS "${MODULE}")
Необходимо добавить пустую строку в конец файла

2021-04-19 17:42 UTC, streltsova-yana commented on modules/triangle-point/test/test_triangle_point.cpp
> +    ASSERT_EQ(tmp, true);
Здесь и везде ниже сначала идёт ожидаемое значение, затем реальное

2021-04-19 17:42 UTC, streltsova-yana commented on modules/triangle-point/src/TrianglePoint.cpp
> +#include "include/TrianglePoint.h"
Заголовочные файлы С++ и заголовочные файлы проекта лучше отделять пустой строкой

[See more details](https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes)

2021-04-19 18:23 UTC, BelikJulia commented on modules/triangle-point/src/TrianglePoint.cpp
> +#include "include/TrianglePoint.h"
Все исправлено

2021-04-20 08:12 UTC, streltsova-yana approved these changes

2021-04-20 08:13 UTC, streltsova-yana commented
Необходим ещё один approve от сокурсника

2021-04-20 08:17 UTC, SMolotkova approved these changes

2021-04-20 08:19 UTC, merged