Гогов В.И. 381806-1. ЛР2.
UNN-ITMM-Software/devtools-course-practice pull request #159
Opened 2021-04-15 15:12 UTC by vlad-gogov

### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [ ] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [ ] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [ ] Get two approve from your fellow students
- [ ] Take a review from one of the administrators

2021-04-15 15:13 UTC, vlad-gogov commented
@MaksimShagov @vla5924

2021-04-15 15:20 UTC, MaksimShagov requested changes

2021-04-15 15:20 UTC, MaksimShagov commented on modules/dheap/src/dheap.cpp
> +}
Вектор нужно передавать по ссылке. Так же weight можно проинициализировать через список(так же как и base).

2021-04-15 15:20 UTC, MaksimShagov commented on modules/dheap/test/test_dheap.cpp
> +TEST(DheapTest, can_hilling_dheap) {
Лучше написать can_hill_dheap (как вариант)).

2021-04-15 15:27 UTC, vla5924 requested changes

2021-04-15 15:27 UTC, vla5924 commented on modules/dheap/include/dheap.h
> +    Dheap(int base_, const std::vector<int> weight_);
```suggestion
    Dheap(int base_, const std::vector<int>& weight_);
```

2021-04-15 15:27 UTC, vla5924 commented on modules/dheap/src/dheap.cpp
> +    int firstChild = node * base + 1;
Выражение `node * base + 1` считается два раза. Следовательно, нужно поместить его в переменную и переиспользовать.

2021-04-15 15:27 UTC, vla5924 commented on modules/dheap/src/dheap.cpp
> +    diving(0);
После этих действий в куче появляется два одинаковых объекта, а изъятия не происходит. Для правильности операции нужно также делать `weight.pop_back()`.

2021-04-15 15:27 UTC, vla5924 commented on modules/dheap/include/dheap.h
> +    std::vector<int> weight;
Логичнее назвать поле `weights`.
```suggestion
    std::vector<int> weights;
```

2021-04-15 15:42 UTC, vla5924 approved these changes

2021-04-15 15:42 UTC, MaksimShagov approved these changes
Good

2021-04-16 06:26 UTC, OnlyDeniko approved these changes
LGTM 👍

2021-04-16 06:26 UTC, merged