Шагов Максим. 381806-1. ЛР2.
UNN-ITMM-Software/devtools-course-practice pull request #162
Opened 2021-04-19 13:57 UTC by MaksimShagov

### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [ ] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [ ] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [ ] Get two approve from your fellow students
- [ ] Take a review from one of the administrators

2021-04-19 13:58 UTC, MaksimShagov commented
@vlad-gogov, @vla5924

2021-04-19 14:15 UTC, vlad-gogov requested changes

2021-04-19 14:15 UTC, vlad-gogov commented on modules/30_rule/src/30_rule.cpp
> +        }
Инициализацию вектора можно провести так state[r].resize(cols, dead)

2021-04-19 14:15 UTC, vlad-gogov commented on modules/30_rule/src/30_rule.cpp
> +        }
Аналогично 14 строчке

2021-04-19 14:15 UTC, vlad-gogov commented on modules/30_rule/src/30_rule.cpp
> +    state[0] = states;
Нужно перенести после 30 строчке и начинать цикл с r = 1

2021-04-19 14:15 UTC, vlad-gogov commented on modules/30_rule/src/30_rule.cpp
> +vector<vector<CellState>> CellularAuto::get_state() {
Нужно возвращать const vector<vector<CellState>>&

2021-04-19 14:15 UTC, vlad-gogov commented on modules/30_rule/src/30_rule.cpp
> +    unsigned int rows = state.size();
Лучше привести к unsigned int через static_cast

2021-04-19 14:15 UTC, vlad-gogov commented on modules/30_rule/src/30_rule.cpp
> +        cells = state[0].size();
Аналогично 55 строчке

2021-04-19 14:34 UTC, vla5924 requested changes

2021-04-19 14:34 UTC, vla5924 commented on modules/30_rule/include/30_rule.h
> +#include <iostream>
Символы из заголовка `<iostream>`  в этом файле не используются. Стоит удалить.

2021-04-19 14:34 UTC, vla5924 commented on modules/30_rule/include/30_rule.h
> +using std::vector;
В заголовочных файлах не следует использовать `using`, тем более такой.

2021-04-19 14:34 UTC, vla5924 commented on modules/30_rule/include/30_rule.h
> +enum CellState {
Если значения из этого enum нигде не используются неявно в качестве int, то нужно объявить его как enum class.

2021-04-19 14:34 UTC, vla5924 commented on modules/30_rule/include/30_rule.h
> +    dead, alive
_MINOR:_ Рекомендую константы enum писать заглавными буквами (это же все-таки константы) и на отдельных строках.

2021-04-19 14:34 UTC, vla5924 commented on modules/30_rule/src/30_rule.cpp
> +    }
После return в else нет смысла.

```suggestion
    if (state[row][col - 1] == dead && state[row][col] == dead &&
     state[row][col + 1] == alive)
        return alive;
    if (state[row][col - 1] == dead && state[row][col] == alive &&
     state[row][col + 1] == dead)
        return alive;
    if (state[row][col - 1] == dead && state[row][col] == alive &&
     state[row][col + 1] == alive)
        return alive;
    if (state[row][col - 1] == alive && state[row][col] == dead &&
     state[row][col + 1] == dead)
        return alive;
```

2021-04-20 09:20 UTC, vla5924 approved these changes

2021-04-20 09:20 UTC, vlad-gogov approved these changes

2021-04-20 11:13 UTC, streltsova-yana requested changes

2021-04-20 11:13 UTC, streltsova-yana commented on modules/30_rule/CMakeLists.txt
> +# include("CTestTests.txt")
Необходимо добавить пустую строку в конец файла

2021-04-20 11:13 UTC, streltsova-yana commented on modules/30_rule/src/CMakeLists.txt
> +set(LIBRARY_DEPS "${LIBRARY_DEPS};${target}" PARENT_SCOPE)
Необходимо добавить пустую строку в конец файла

2021-04-20 11:13 UTC, streltsova-yana commented on modules/30_rule/test/CMakeLists.txt
> +    LABELS "${MODULE}")
Необходимо добавить пустую строку в конец файла

2021-04-20 11:13 UTC, streltsova-yana commented on modules/30_rule/test/test_30_rule.cpp
> +    ASSERT_NO_THROW(CellularAuto(1, 1, state));
Здесь точно ожидается CellularAuto(1, 1, state), а не CellularAuto(1, 3, state)?

2021-04-20 11:13 UTC, streltsova-yana commented on modules/30_rule/test/test_30_rule.cpp
> +    ASSERT_EQ(automat.get_state()[1], state);
Здесь и везде ниже сначала ожидаемое значение, а затем реальное

2021-04-20 15:10 UTC, streltsova-yana approved these changes

2021-04-20 15:11 UTC, merged