Боровков Сергей. Лабораторная работа №2.
UNN-ITMM-Software/devtools-course-practice pull request #163
Opened 2024-04-04 09:42 UTC by slx52

Сортировка "Вставками". 
Были добавлены тесты написанного функционала.

2024-04-05 16:33 UTC, Kuznetsov-Artyom commented
@slx52 Тегните двух любых студентов из [списка,](https://unn-itmm-software.github.io/devtools-course-practice) чтобы они провели код ревью.

2024-04-06 09:39 UTC, slx52 commented
@Gr0miLa @Manymoera

2024-04-06 09:42 UTC, Gr0miLa approved these changes

2024-04-06 09:44 UTC, Manymoera approved these changes

2024-04-06 12:45 UTC, Kuznetsov-Artyom requested changes

2024-04-06 12:45 UTC, Kuznetsov-Artyom commented on modules/borovkov_s_sort/test/test_insertion_sort.cpp
> +  std::vector<int> test1 = {5, 2, 4, 6, 1, 3};
```suggestion
  std::vector<int> test1{5, 2, 4, 6, 1, 3};
```

2024-04-06 12:45 UTC, Kuznetsov-Artyom commented on modules/borovkov_s_sort/test/test_insertion_sort.cpp
> +  std::vector<int> test1 = {5, 2, 4, 6, 1, 3};
Также поправьте пожалуйста в других местах

2024-04-06 12:45 UTC, Kuznetsov-Artyom commented on modules/borovkov_s_sort/test/test_insertion_sort.cpp
Добавьте пожалуйста рандомные тесты на большом диапазоне. Затем сравните корректность работы с другой сортировкой (воспользуйтесь std::sort)

Можете пожалуйста переделать свою функцию под шаблон? И сравнить работу на других типах например `double` `size_t` и тд.

2024-04-11 19:43 UTC, Kuznetsov-Artyom approved these changes

2024-04-11 19:43 UTC, merged