Черных Д.А. 381803-2 ЛР_2
UNN-ITMM-Software/devtools-course-practice pull request #164
Opened 2021-04-20 08:55 UTC by dashachernyh

### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [ ] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [ ] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [ ] Get two approve from your fellow students
- [ ] Take a review from one of the administrators

2021-04-21 17:54 UTC, BrandonRTL requested changes

2021-04-21 17:54 UTC, BrandonRTL commented on modules/prime_numbers/include/prime_numbers.h
>      explicit PrimeNumber(const int size = 0);
В cpp файле нет const. (Не ну я без негатива, там просто в правилах написано, что рецензент ОБЯЗАН к чему-то прикопаться)

2021-04-21 18:32 UTC, Vodeneev approved these changes
всё гуд!

2021-04-21 19:59 UTC, MADZEROPIE commented on modules/prime_numbers/src/prime_numbers.cpp
> +  for (int i = 0; i < n; i++) { primes[i] = gen() % 100; }
Загадка от Жака Фреско: Почему линтер не ругается на это?

2021-04-21 20:01 UTC, MADZEROPIE commented on modules/prime_numbers/include/prime_numbers.h
> +#include<random>
И на это...

2021-04-22 15:12 UTC, BrandonRTL approved these changes

2021-04-22 17:54 UTC, alxndrvna approved these changes

2021-04-23 13:32 UTC, merged