Яшин - Лабораторная работа #2
UNN-ITMM-Software/devtools-course-practice pull request #165
Opened 2022-04-17 23:50 UTC by KirillYashin

2022-04-18 00:46 UTC, KirillYashin commented
@gordushha @PureEvil-UselessMan review pls

2022-04-18 16:23 UTC, gordushha approved these changes

2022-04-20 18:58 UTC, PureEvil-UselessMan requested changes
Все хорошо, но в binary_search.h на 30-ой строке стоит лишняя точка с запятой.

2022-04-20 19:07 UTC, KirillYashin commented
> Все хорошо, но в binary_search.h на 30-ой строке стоит лишняя точка с запятой.

fixed

2022-04-20 19:10 UTC, PureEvil-UselessMan approved these changes
Молодец! Approved.

2022-04-20 20:35 UTC, KirillYashin commented
@SHVlader review pls

2022-04-20 20:46 UTC, merged