Козлов Михаил. Лаба 2
UNN-ITMM-Software/devtools-course-practice pull request #165
Opened 2024-04-04 16:43 UTC by Mishaizlesa

2024-04-04 21:01 UTC, Kuznetsov-Artyom commented
Добавьте пожалуйста краткое описание задачи в пр

2024-04-05 16:33 UTC, Kuznetsov-Artyom commented
@Mishaizlesa Тегните двух любых студентов из [списка,](https://unn-itmm-software.github.io/devtools-course-practice) чтобы они провели код ревью.

2024-04-05 16:35 UTC, Mishaizlesa commented
@mada40 @drinkwr

2024-04-05 17:03 UTC, drinkwr commented
добавь тесты на граф с кратными ребрами

2024-04-05 17:52 UTC, drinkwr approved these changes

2024-04-05 20:30 UTC, mada40 commented
Добавьте тест на полный граф

2024-04-05 22:03 UTC, mada40 approved these changes

2024-04-05 22:32 UTC, Kuznetsov-Artyom requested changes

2024-04-05 22:32 UTC, Kuznetsov-Artyom commented on modules/kozlov_m_graph_diam/include/graph.h
> +            for (auto e : adj[x]) {
Лучше избегать лишнего копирования, если это возможно.
```suggestion
            for (const auto& e : adj[x]) {
```

2024-04-06 12:28 UTC, Kuznetsov-Artyom approved these changes

2024-04-06 12:28 UTC, merged