Борисов Савелий - Лабораторная работа #2
UNN-ITMM-Software/devtools-course-practice pull request #166
Opened 2024-04-05 07:27 UTC by Amazingkivas

Реализация структуры данных Стэк

2024-04-05 22:34 UTC, Kuznetsov-Artyom reviewed
@Amazingkivas Тегните двух любых студентов из [списка,](https://unn-itmm-software.github.io/devtools-course-practice) чтобы они провели код ревью.

2024-04-06 06:44 UTC, Amazingkivas commented
@BlackAngel2108 @lesnikowka

2024-04-06 10:59 UTC, BlackAngel2108 approved these changes

2024-04-06 11:09 UTC, lesnikowka approved these changes

2024-04-06 14:54 UTC, Kuznetsov-Artyom requested changes

2024-04-06 14:54 UTC, Kuznetsov-Artyom commented on modules/borisov_s_stack/include/stack.h
Используйте правило пяти (Rule of five)

2024-04-06 14:54 UTC, Kuznetsov-Artyom commented on modules/borisov_s_stack/include/stack.h
Добавьте операторы равенства/неравенства

2024-04-06 14:56 UTC, Kuznetsov-Artyom commented on modules/borisov_s_stack/include/stack.h
Также добавьте пожалуйста соответствующие тесты для перемещающий и копирующий операций, а также проверку на равенство/неравенство

2024-04-08 18:58 UTC, Kuznetsov-Artyom commented on modules/borisov_s_stack/include/stack.h
> +    }
Что произойдет, если мы сделаем такую запись?
```
stack = std::move(stack);
```

2024-04-08 19:09 UTC, Kuznetsov-Artyom commented on modules/borisov_s_stack/include/stack.h
> +            throw std::string("Stack is empty");
В случае если кто-то захочет перехватить ваше исключение, например так:
```cpp
try {
  // Какой-то код использующий ваш стек
} catch (const std::exception& ex) {
  std::cerr << ex.what() << '\n';
}
```
Исключение будет перехвачено?

2024-04-08 20:12 UTC, Kuznetsov-Artyom approved these changes
Спасибо за внесенные изменения

2024-04-08 20:12 UTC, merged