Kiselev igor lab2
UNN-ITMM-Software/devtools-course-practice pull request #168
Opened 2024-04-05 14:56 UTC by ISK7

Алгоритм билинейной интерполяции двумерного массива как набора пикселей. Суть алгоритма в вычислении среднего значения функции в точке между известными значениями. В данном случае алгоритм обрабатывает цветное изображение, чтобы сгладить возможную угловатость, несколько размыть изображение. Алгоритм реализован в классе BillinearInterpolation в качестве методов. Конструктор класса принимает на вход обрабатываемое изображение. Алгоритм может работать с ядрами 2х2 (метод twoCore()) и ядрами 3х3 (метод threeCore()).

2024-04-05 16:31 UTC, Kuznetsov-Artyom commented
@ISK7 Тегните двух любых студентов из [списка,](https://unn-itmm-software.github.io/devtools-course-practice) чтобы они провели код ревью.

2024-04-05 19:12 UTC, ISK7 commented
@pozvas , @GERONlMO , извиняйте, но рандом решил, что меня ревьюшите вы

2024-04-07 10:58 UTC, pozvas approved these changes

2024-04-07 18:21 UTC, pozvas approved these changes
Можешь дать имена значащим константам в Color.cpp (0 и 255)

2024-04-11 16:58 UTC, Kuznetsov-Artyom commented
Добавьте описание работы в пр

2024-04-12 11:19 UTC, Kuznetsov-Artyom requested changes

2024-04-12 11:19 UTC, Kuznetsov-Artyom commented on modules/kiselev_i_billinear_interpolation/include/Billinear_interpolation.h
> +    BillinearInterpolation(const BillinearInterpolation &bi);
Было бы неплохо добавить и перемещающие операции (конструктор и оператор присваивания).
Или лучше удалить этот конструктор, в таком случае компилятор создаст все 4 операции (конструкторы и операторы присваивания) самостоятельно.

2024-04-12 11:19 UTC, Kuznetsov-Artyom commented on modules/kiselev_i_billinear_interpolation/src/Billinear_interpolation.cpp
> +    h1.setB(lu.getB() + (ru.getB() - lu.getB()) * (x2 - x1) / (2 * x2 - x1));
Было бы удобно иметь метод `setColor`, если нужно задать сразу все 3 компоненты.

2024-04-12 11:19 UTC, Kuznetsov-Artyom commented on modules/kiselev_i_billinear_interpolation/test/test_main.cpp
> +// Copyright 2017 Korniakov Kirill
Поменяйте копирайт

2024-04-12 14:01 UTC, Kuznetsov-Artyom approved these changes

2024-04-12 14:02 UTC, Kuznetsov-Artyom commented
В целом все отлично, только добавьте еще копирующий оператор присваивания и исправьте ошибки билда

2024-04-12 14:27 UTC, Kuznetsov-Artyom requested changes

2024-04-12 14:27 UTC, Kuznetsov-Artyom commented on modules/kiselev_i_billinear_interpolation/src/Billinear_interpolation.cpp
> +
Исправьте оператор. Ошибочная логика и сигнатура.

2024-04-13 13:47 UTC, Kuznetsov-Artyom requested changes

2024-04-13 13:47 UTC, Kuznetsov-Artyom commented on modules/kiselev_i_billinear_interpolation/src/Billinear_interpolation.cpp
> +}
```suggestion
BillinearInterpolation& BillinearInterpolation::operator=
(const BillinearInterpolation& bi) {
    if (&bi != this) {
        source = bi.source;
    }
    return *this;
}
```

2024-04-13 13:47 UTC, Kuznetsov-Artyom commented on modules/kiselev_i_billinear_interpolation/include/Billinear_interpolation.h
> +    BillinearInterpolation& operator=(BillinearInterpolation& bi);
```suggestion
    BillinearInterpolation& operator=(const BillinearInterpolation& bi);
```

2024-04-15 15:39 UTC, Kuznetsov-Artyom approved these changes

2024-04-15 15:39 UTC, merged