Храмов Иван. Лабораторная работа 2.
UNN-ITMM-Software/devtools-course-practice pull request #171
Opened 2024-04-07 00:19 UTC by At0mn1yIvan

2024-04-07 01:02 UTC, At0mn1yIvan commented
По неясным причинам не находится исполняемый файл на винде. Локально проблемы нет.

2024-04-07 11:03 UTC, At0mn1yIvan commented
@Kuznetsov-Artyom

2024-04-07 17:04 UTC, Kuznetsov-Artyom commented
> @Kuznetsov-Artyom

В ближайшее время разберемся, спасибо, что отправили уведомление.

2024-04-08 10:42 UTC, Kuznetsov-Artyom commented
@At0mn1yIvan radix_sort.cpp(8,20): error C2039: 'string': is not a member of 'std'. Подключите заголовочный файл `<string>`

2024-04-08 13:33 UTC, At0mn1yIvan commented
@Kuznetsov-Artyom , спасибо! Ошибка действительно была в этом. В ubuntu данной проблемы не возникало.

2024-04-08 14:07 UTC, Kuznetsov-Artyom reviewed
@At0mn1yIvan Тегните двух любых студентов из [списка,](https://unn-itmm-software.github.io/devtools-course-practice) чтобы они провели код ревью.

2024-04-08 14:08 UTC, At0mn1yIvan commented
@pozvas @Frenetz

2024-04-08 14:19 UTC, pozvas approved these changes
Можешь в countSort сделать base константой

2024-04-08 15:08 UTC, Frenetz approved these changes
Добавь тесты на сортировку массива с одним элементом и тест на уже отсортированный массив

2024-04-08 18:07 UTC, Kuznetsov-Artyom requested changes

2024-04-08 18:07 UTC, Kuznetsov-Artyom commented on modules/khramov_i_lab2/src/radix_sort.cpp
Можете переделать вашу функцию сортировки под шаблон?

2024-04-08 18:07 UTC, Kuznetsov-Artyom commented on modules/khramov_i_lab2/src/radix_sort.cpp
> +        throw std::string("The array is empty. Nothing to sort.");
В случае если кто-то захочет перехватить ваше исключение, например так:
```cpp
try {
  // Какой-то код вызывающий вашу сортировку
} catch (const std::exception& ex) {
  std::cerr << ex.what() << '\n';
}
```
Исключение будет перехвачено?

2024-04-08 18:07 UTC, Kuznetsov-Artyom commented on modules/khramov_i_lab2/test/test_khramov_ivan_radix.cpp
Добавьте пожалуйста рандомный тест на большом диапазоне

2024-04-08 18:07 UTC, Kuznetsov-Artyom commented on modules/khramov_i_lab2/test/test_khramov_ivan_radix.cpp
> +     [](int a, int b) { return a > b; });
```suggestion
    std::sort(expected.begin(), expected.end(), std::greater<int>());
```
Также для гарантии подключите `<functional>`
Поправьте и в других тестах

2024-04-08 18:52 UTC, At0mn1yIvan commented on modules/khramov_i_lab2/src/radix_sort.cpp
Данная реализация целиком заточена под int и не предполагает сортировки элементов типа double

2024-04-08 19:04 UTC, At0mn1yIvan commented on modules/khramov_i_lab2/src/radix_sort.cpp
Однако под шаблон я переделать могу, предполагая, что будут использованы элементы типа int

2024-04-08 19:05 UTC, At0mn1yIvan commented on modules/khramov_i_lab2/src/radix_sort.cpp
Для double реализация будет совершенно иной

2024-04-08 19:06 UTC, Kuznetsov-Artyom commented on modules/khramov_i_lab2/src/radix_sort.cpp
> Данная реализация целиком заточена под int и не предполагает сортировки элементов типа double

Я это понимаю), поэтому ниже попросил еще сделать тесты для целочисленных типов данных. Для того чтобы гарантировать, что шаблон класса будет инстанцирован с нужным типом (целочисленным), используйте SFINAE.

2024-04-08 19:08 UTC, At0mn1yIvan commented on modules/khramov_i_lab2/src/radix_sort.cpp
Хорошо, спасибо!

2024-04-08 20:01 UTC, At0mn1yIvan commented on modules/khramov_i_lab2/src/radix_sort.cpp
Что подразумевает SFINAE? Как это требуется сделать?

2024-04-08 20:10 UTC, Kuznetsov-Artyom commented on modules/khramov_i_lab2/src/radix_sort.cpp
> Что подразумевает SFINAE? Как это требуется сделать?

На данную тему очень много постов на просторах интернета. В качестве примера могу посоветовать эти источники:
1) https://www.geeksforgeeks.org/substitution-failure-is-not-an-error-sfinae-in-cpp/
2) https://en.cppreference.com/w/cpp/language/sfinae
3) http://scrutator.me/post/2016/12/12/sfinae.aspx

2024-04-08 20:19 UTC, Kuznetsov-Artyom commented on modules/khramov_i_lab2/src/radix_sort.cpp
> Что подразумевает SFINAE? Как это требуется сделать?

Также дополнительно могу посоветовать конкретную литературу:
Книга Вандервурд  "Шаблоны С++"  п6.3 п8.4

2024-04-08 20:35 UTC, At0mn1yIvan commented on modules/khramov_i_lab2/src/radix_sort.cpp
Спасибо. Кажется, реализовал.

2024-04-08 20:35 UTC, At0mn1yIvan commented on modules/khramov_i_lab2/src/radix_sort.cpp
> +        throw std::string("The array is empty. Nothing to sort.");
Исправил

2024-04-08 20:35 UTC, At0mn1yIvan commented on modules/khramov_i_lab2/test/test_khramov_ivan_radix.cpp
Добавил

2024-04-08 20:35 UTC, At0mn1yIvan commented on modules/khramov_i_lab2/test/test_khramov_ivan_radix.cpp
> +     [](int a, int b) { return a > b; });
Изменил

2024-04-08 20:46 UTC, Kuznetsov-Artyom commented on modules/khramov_i_lab2/include/radix_sort.h
> +        throw std::runtime_error("The array is empty. Nothing to sort.");
Мне кажется, в данном контексте больше подойдет тип ошибки `std::invalid_argument`

2024-04-08 20:47 UTC, Kuznetsov-Artyom commented on modules/khramov_i_lab2/include/radix_sort.h
> +        throw std::runtime_error("The array is empty. Nothing to sort.");
А так в целом все отлично, спасибо за внесенные изменения!:)

2024-04-08 20:49 UTC, Kuznetsov-Artyom approved these changes

2024-04-08 20:49 UTC, At0mn1yIvan commented on modules/khramov_i_lab2/include/radix_sort.h
> +        throw std::runtime_error("The array is empty. Nothing to sort.");
Изменил. Спасибо за активную помощь!

2024-04-08 20:52 UTC, merged