Молоткова Светлана. 381806-1. ЛР2.
UNN-ITMM-Software/devtools-course-practice pull request #175
Opened 2021-04-22 17:12 UTC by SMolotkova

### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [ ] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [ ] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [ ] Get two approve from your fellow students
- [ ] Take a review from one of the administrators

2021-04-22 17:46 UTC, ParanichevaAlyona reviewed
Стоило бы сделать поля a, b, c private

2021-04-24 16:46 UTC, BelikJulia commented on modules/quadratic_equation/src/QuadraticEquation.cpp
> +    double x1 = (-b + sqrt(d)) / (2 * a);
Что будет при отрицательном дискриминанте и нулевом коэффициенте а?

2021-04-24 17:29 UTC, ParanichevaAlyona approved these changes
Хорошая работа

2021-04-24 18:24 UTC, BelikJulia approved these changes
все хорошо

2021-04-24 21:31 UTC, streltsova-yana requested changes

2021-04-24 21:31 UTC, streltsova-yana commented on modules/quadratic_equation/include/QuadraticEquation.h
> +        throw "Error";
В неполном квадратном уравнении b и c могут одновременно быть равными нулю

2021-04-24 21:31 UTC, streltsova-yana commented on modules/quadratic_equation/include/QuadraticEquation.h
> +    QuadraticEquation(double a, double b, double c) {
Реализацию конструктора лучше написать в .cpp файле

2021-04-24 21:31 UTC, streltsova-yana commented on modules/quadratic_equation/src/QuadraticEquation.cpp
> +         throw "Error";
Можно было бы написать более конкретное сообщение об ошибке

2021-04-25 10:56 UTC, streltsova-yana approved these changes

2021-04-25 10:56 UTC, merged