Колесников Глеб 381803-2 ЛР2
UNN-ITMM-Software/devtools-course-practice pull request #176
Opened 2021-04-22 17:25 UTC by BrandonRTL

### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [ ] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [ ] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [ ] Get two approve from your fellow students
- [ ] Take a review from one of the administrators

2021-04-22 18:10 UTC, andrewkin77 requested changes
Поменяй, пожалуйста, названия последних тестов, вряд ли их кто-то поймёт

2021-04-22 18:11 UTC, MADZEROPIE reviewed
Меня настоятельно просили этого не делать, но ... Извините.

2021-04-22 18:11 UTC, MADZEROPIE commented on modules/bulls-n-cows/include/BullsAndCows.h
> +    void setGuess(std::vector<int> guess);
Лучше передавать векторы по ссылке.

2021-04-22 18:11 UTC, MADZEROPIE commented on modules/bulls-n-cows/include/BullsAndCows.h
> +     explicit bullsAndCowsGame(std::vector<int> ans);
Съехал пробел.

2021-04-22 18:11 UTC, MADZEROPIE commented on modules/bulls-n-cows/src/BullsAndCows.cpp
> +    return 0;
может тогда просто
return getAnimals().first == static_cast<int>(getAnswer().size()); 
или
bool res = getAnimals().first == static_cast<int>(getAnswer().size()); 
return res;

2021-04-22 18:11 UTC, MADZEROPIE commented on modules/bulls-n-cows/src/BullsAndCows.cpp
> +#include "include/BullsAndCows.h"
Рекомендуется отделять свои файлы от стандартных пустой строкой.

2021-04-22 18:11 UTC, MADZEROPIE commented on modules/bulls-n-cows/test/test_main.cpp
> +}
А где пустая строка в конце? ЛИНТЕР, ТЫ ТАМ ЖИВОЙ?!

2021-04-22 18:11 UTC, MADZEROPIE commented on modules/bulls-n-cows/test/test_bulls_and_cows.cpp
> +TEST(BullsAndCows, Guessing_2) {
Тесты отделяйте пустой строкой друг от друга, пожалуйста.

2021-04-22 18:32 UTC, MADZEROPIE approved these changes
_**My job here is done**_

2021-04-23 12:41 UTC, dkurt commented
@OnlyDeniko, please review and check if @MADZEROPIE's requests are considered by author.

2021-04-23 12:51 UTC, OnlyDeniko commented on modules/bulls-n-cows/include/BullsAndCows.h
> +    std::vector<int> getGuess();
В геттерах не хватает const
```suggestion
    std::vector<int> getAnswer() const;
    std::pair<int, int> getAnimals() const;
    std::vector<int> getGuess() const;
```

2021-04-23 12:51 UTC, OnlyDeniko commented on modules/bulls-n-cows/src/BullsAndCows.cpp
> +    for (unsigned  int i = 0; i < guess.size(); i++) {
```suggestion
    for (unsigned int i = 0; i < guess.size(); i++) {
```

2021-04-23 12:53 UTC, OnlyDeniko reviewed
Поставь квалификаторы `const` в функциях, в которых ничего не изменяется

2021-04-23 13:23 UTC, OnlyDeniko approved these changes

2021-04-23 13:23 UTC, merged