Параничева Алена. 381806-1. ЛР2.
UNN-ITMM-Software/devtools-course-practice pull request #177
Opened 2021-04-22 17:28 UTC by ParanichevaAlyona

### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [ ] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [ ] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [ ] Get two approve from your fellow students
- [ ] Take a review from one of the administrators

2021-04-24 17:42 UTC, SMolotkova commented on modules/params-triangle/test/test_params_triangle.cpp
> +    EXPECT_DOUBLE_EQ(4.0, sideAB);
Нужно ASSERT_ вместо EXPECT_

2021-04-24 17:49 UTC, SMolotkova approved these changes
Отлично

2021-04-24 18:25 UTC, BelikJulia approved these changes
все хорошо

2021-04-25 03:45 UTC, streltsova-yana requested changes

2021-04-25 03:45 UTC, streltsova-yana commented on modules/params-triangle/src/triangle.cpp
> +    double AC = sqrt((a.second - c.second) * (a.second - c.second) +
По аналогии с вычислением длин других сторон можно из координат точки С вычитать координаты точки А

2021-04-25 03:45 UTC, streltsova-yana commented on modules/params-triangle/test/test_params_triangle.cpp
> +    ASSERT_DOUBLE_EQ(6.0, Area);
Можно попробовать сделать тесты параметрическими

2021-04-25 13:40 UTC, closed without merging