Мишин Илья 381803-2 ЛР2
UNN-ITMM-Software/devtools-course-practice pull request #178
Opened 2021-04-22 19:04 UTC by Iliamish

### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [ ] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [ ] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [ ] Get two approve from your fellow students
- [ ] Take a review from one of the administrators

2021-04-22 19:09 UTC, Iliamish commented
Я не смог придумать что-то сложное в этой задаче. @MADZEROPIE @andrewkin77 @BrandonRTL @TsvetkovMaximPmi3 взгляните, пожалуйста

2021-04-22 19:16 UTC, BrandonRTL requested changes

2021-04-22 19:16 UTC, BrandonRTL commented on modules/euler_func/test/test_Euler.cpp
> +    ASSERT_EQ(0, 0);
А здесь не должно было ASSERT_EQ(0, phi(0)) ?

2021-04-22 19:20 UTC, MADZEROPIE reviewed
Как-то так.

2021-04-22 19:20 UTC, MADZEROPIE commented on modules/euler_func/include/Euler.h
> +
Весь код в .h файле... Мда.
Здесь должен быть только прототип.

2021-04-22 19:20 UTC, MADZEROPIE commented on modules/euler_func/include/Euler.h
> +    if (n == 0) {
Мб лучше сделать int64_t ?

2021-04-22 19:20 UTC, MADZEROPIE commented on modules/euler_func/test/test_Euler.cpp
> +#include "include/Euler.h"
Рекомендуется разделять пустой строкой. (Аналогично в .cpp)

2021-04-22 19:20 UTC, MADZEROPIE commented on modules/euler_func/test/test_Euler.cpp
> +}
Если честно, то тесты слабоваты. По всем заветам TDD (код должен проходить все тесты) это можно сломать напрямую с помощью if'ов. (Enterprise Developer From Hell)
Можно воспользоваться свойством функции Эйлера (u(m*n)=u(m)*u(n)) и добавить проверку с не очень большими рандомными числами.

2021-04-22 19:38 UTC, Iliamish commented on modules/euler_func/test/test_Euler.cpp
> +}
Спасибо за внимательность!

2021-04-22 19:39 UTC, Iliamish commented on modules/euler_func/test/test_Euler.cpp
> +    ASSERT_EQ(0, 0);
Спасибо!

2021-04-22 19:53 UTC, MADZEROPIE approved these changes
_**My job here is done**_

2021-04-22 19:55 UTC, BrandonRTL approved these changes

2021-04-23 08:02 UTC, WerWebWer commented on modules/euler_func/include/Euler.h
> +    for (int i = 2; i * i <= n; ++i)
Если у нас  `int64_t n`, а `int i`, то у нас случаем не будет вечного цикла `for (;;)`?

2021-04-23 12:38 UTC, dkurt commented
@OnlyDeniko, please review and add your comments

2021-04-23 12:44 UTC, OnlyDeniko reviewed
Сделай параметризованные тесты, будет выглядеть гораздо красивее

2021-04-23 13:48 UTC, WerWebWer commented on modules/euler_func/include/Euler.h
> +    for (int i = 2; i * i <= n; ++i)
Думаю тут есть переполнение integer
Положительная часть `int64_t n` намного больше `int i`, даже если тот возведен в степень два. В итоге получаем вечный цикл for при максимальном `int64_t`

2021-04-23 15:32 UTC, MADZEROPIE commented on modules/euler_func/include/Euler.h
> +    for (int i = 2; i * i <= n; ++i)
Скорее неопределенное поведение при переполнении int

2021-04-23 17:30 UTC, OnlyDeniko approved these changes

2021-04-23 17:31 UTC, merged