Скотин Александр - Лабораторная работа 2
UNN-ITMM-Software/devtools-course-practice pull request #186
Opened 2024-04-11 17:54 UTC by Crazy767

2024-04-11 17:56 UTC, Kuznetsov-Artyom commented
@Crazy767 Тегните двух любых студентов из [списка,](https://unn-itmm-software.github.io/devtools-course-practice) чтобы они провели код ревью.

2024-04-11 17:56 UTC, Crazy767 commented
@pozvas, @GERONlMO, можете ревью кода провести)

2024-04-11 19:37 UTC, pozvas approved these changes
Можете сделать тест на не int ключ

2024-04-11 20:38 UTC, Kuznetsov-Artyom requested changes

2024-04-11 20:38 UTC, Kuznetsov-Artyom commented on modules/skotin_a_hashmap/include/hashmap.h
> +};
Используйте правило пяти (rule of five)

2024-04-12 10:19 UTC, Crazy767 commented on modules/skotin_a_hashmap/include/hashmap.h
> +};
Готово

2024-04-12 12:11 UTC, Kuznetsov-Artyom reviewed
LGTM, только поправьте несколько моментов

2024-04-12 12:11 UTC, Kuznetsov-Artyom commented on modules/skotin_a_hashmap/include/hashmap.h
> +     void clear();
```suggestion
     void clear() noexcept;
```

2024-04-12 12:11 UTC, Kuznetsov-Artyom commented on modules/skotin_a_hashmap/include/hashmap.h
> +    }
```suggestion
    if (this != &other) {
        *this = HashMap(other);
    }
```

2024-04-12 12:11 UTC, Kuznetsov-Artyom commented on modules/skotin_a_hashmap/include/hashmap.h
> +void HashMap<KeyType, ValueType>::clear() {
```suggestion
void HashMap<KeyType, ValueType>::clear() noexcept {
```

2024-04-12 12:46 UTC, Kuznetsov-Artyom approved these changes

2024-04-12 12:47 UTC, merged