Шубин Михаил - Лабораторная работа 2
UNN-ITMM-Software/devtools-course-practice pull request #187
Opened 2024-04-12 05:50 UTC by ArchiMikael

2024-04-12 09:19 UTC, Kuznetsov-Artyom commented
@ArchiMikael Тегните двух любых студентов из [списка,](https://unn-itmm-software.github.io/devtools-course-practice) чтобы они провели код ревью.

2024-04-13 16:28 UTC, ArchiMikael commented
@katrin000 @KasimtcevRoman

2024-04-13 23:25 UTC, Kuznetsov-Artyom commented
Добавьте в пр описание вашей задачи

2024-04-14 14:15 UTC, KasimtcevRoman approved these changes
Все устраивает

2024-04-14 16:09 UTC, katrin000 approved these changes
Всё чудесно

2024-04-15 02:56 UTC, Kuznetsov-Artyom requested changes

2024-04-15 02:56 UTC, Kuznetsov-Artyom commented on modules/shubin_m_numeric_systems/include/CustomNSNumber.hpp
> +#define number_t int64_t
Лучше использовать псевдонимы типов (using alias)

2024-04-15 02:56 UTC, Kuznetsov-Artyom commented on modules/shubin_m_numeric_systems/src/CustomNSNumber.cpp
> +  digits = _num.digits;
Параметр `_num` является `l-value`, независимо от того, что его тип ссылка на `r-value`.
По этой причине в данном случае произойдет копирование, вместо ожидаемого перемещения.
```suggestion
  digits = std::move(_num.digits);
```
Поправьте также в операторе присваивания с перемещением

P.S: В вашем классе вовсе не обязательно иметь копирующие и перемещающие операции + деструктор, компилятор сгенерирует необходимые функции-члены самостоятельно

2024-04-15 02:56 UTC, Kuznetsov-Artyom commented on modules/shubin_m_numeric_systems/src/CustomNSNumber.cpp
> +  _num.digits.clear();
```suggestion
```

2024-04-15 02:56 UTC, Kuznetsov-Artyom commented on modules/shubin_m_numeric_systems/src/CustomNSNumber.cpp
> +}
Почему бы не пометить все методы, которые не будут модифицировать объект, как `const`?
Также полезной практикой будет добавление спецификации исключения (`noexcept`), но тут нужно быть осторожным.

2024-04-15 02:56 UTC, Kuznetsov-Artyom commented on modules/shubin_m_numeric_systems/src/CustomNSNumber.cpp
> +}
Зачем создавать временный объект?
Лучше пометить метод `ToDec` как `const` и вызвать напрямую при создании `rhs`.
```suggestion
bool CustomNSNumber::operator==(const CustomNSNumber& _num) const {
  number_t lhs = ToDec();
  number_t rhs = num.ToDec();
  return (lhs == rhs);
}
```
а еще лучше так:
```suggestion
bool CustomNSNumber::operator==(const CustomNSNumber& _num) const {
  return ToDec() == num.ToDec();
}
```
Также поправьте остальные операторы сравнения

2024-04-16 14:48 UTC, Kuznetsov-Artyom approved these changes
Спасибо за внесенные изменения

2024-04-16 14:48 UTC, merged