Безроднов Д.А. 381803-2 ЛР2
UNN-ITMM-Software/devtools-course-practice pull request #190
Opened 2021-04-23 22:33 UTC by dmitrybezro

### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [ ] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [ ] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [ ] Get two approve from your fellow students
- [ ] Take a review from one of the administrators

2021-04-24 20:47 UTC, BrandonRTL requested changes

2021-04-24 20:47 UTC, BrandonRTL commented on modules/Vigener_cipher/include/Vigener.h
> +	int length_abc = 26;
Если длина - это мощность заданного алфавита, может ее константной сделать?

2021-04-25 12:42 UTC, dashachernyh approved these changes

2021-04-25 12:42 UTC, dashachernyh commented on modules/Vigener_cipher/include/Vigener.h
> +    std::string encrypt(const std::string& str_input);
Метод get_key() наверное лучше сделать const

2021-04-25 15:00 UTC, MADZEROPIE commented on modules/Vigener_cipher/include/Vigener.h
> +	int length_abc = 26;
А если учесть, что она одинакова для всех экземпляров класса, ~~(если, конечно, не планируется добавлять другой алфавит,)~~ то можно ещё и static.

2021-04-25 15:01 UTC, MADZEROPIE commented on modules/Vigener_cipher/include/Vigener.h
> +    }
Не лучше ли сделать параметр по умолчанию?

2021-04-25 15:22 UTC, BrandonRTL approved these changes

2021-04-25 16:15 UTC, dmitrybezro commented on modules/Vigener_cipher/include/Vigener.h
> +    }
Да, будет лучше. Спасибо

2021-04-26 06:26 UTC, merged