Александрычев А.С. 381806-2. ЛР2.
UNN-ITMM-Software/devtools-course-practice pull request #191
Opened 2021-04-24 06:58 UTC by Alex-Andr-19

### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [ ] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [ ] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [ ] Get two approve from your fellow students
- [ ] Take a review from one of the administrators

2021-04-25 07:09 UTC, OnlyDeniko commented on modules/grosfeld-cipher/src/grosfeld_cipher.cpp
> +}
При входных параметрах `(1, 1000000000)` это будет работать очень долго, попробуй придумать оптимизацию.

2021-04-26 12:23 UTC, Alex-Andr-19 reviewed
@kustuk1306  @drwff

2021-04-26 14:34 UTC, kustuk1306 commented on modules/grosfeld-cipher/include/grosfeld_cipher.h
> +    std::string keyString = "";
Можно сделать сеттеры для этих полей

2021-04-26 14:38 UTC, drwff commented on modules/grosfeld-cipher/include/grosfeld_cipher.h
> +    int key = 0;
Сделай метод set для этого поля

2021-04-26 15:24 UTC, drwff approved these changes

2021-04-26 15:49 UTC, kustuk1306 approved these changes

2021-04-26 16:39 UTC, Alex-Andr-19 reviewed
@streltsova-yana  , проверь, плз

2021-04-27 08:30 UTC, streltsova-yana requested changes

2021-04-27 08:30 UTC, streltsova-yana commented on modules/grosfeld-cipher/src/grosfeld_cipher.cpp
> +}
Дублирующийся код можно вынести в отдельную приватную функцию, которую потом вызывать

2021-04-27 08:30 UTC, streltsova-yana commented on modules/grosfeld-cipher/test/test_grosfeld_cipher.cpp
> +    std::string sourceString = "gronsfeld";
sourceString не используется

2021-04-27 11:00 UTC, streltsova-yana approved these changes

2021-04-27 11:01 UTC, merged