Напылов Е. И. 381806-2. ЛР2.
UNN-ITMM-Software/devtools-course-practice pull request #194
Opened 2021-04-24 08:46 UTC by Talesard

### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [ ] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [ ] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [ ] Get two approve from your fellow students
- [ ] Take a review from one of the administrators

2021-04-24 09:53 UTC, Talesard commented
@gitlng @katsum25 check, please.

2021-04-24 10:16 UTC, gitlng commented
И протестируйте случаи, когда искомое значение на границе

2021-04-24 10:47 UTC, gitlng requested changes

2021-04-24 10:47 UTC, gitlng commented on modules/interpolation-search/src/interpolation_search.cpp
> +    int lev_gr = 0;
Поменяйте название. Нечитабельно.

2021-04-24 10:47 UTC, gitlng commented on modules/interpolation-search/src/interpolation_search.cpp
> +    int prav_gr = size - 1;
Аналогично

2021-04-24 10:47 UTC, gitlng commented on modules/interpolation-search/src/interpolation_search.cpp
> +#include "include/interpolation_search.h"
Лучше отделить пробелами .h, копирайт и основные библиотеки между собой.

2021-04-24 10:47 UTC, gitlng commented on modules/interpolation-search/include/interpolation_search.h
> +// Copyright 2021 Napylov Evgeniy
Пробел после копирайта

2021-04-24 10:47 UTC, gitlng commented on modules/interpolation-search/test/test_interpolation_search.cpp
> +// Copyright 2021 Napylov Evgeniy
Нужен пробел после копирайта и перед .h

2021-04-24 11:05 UTC, katsum25 commented on modules/interpolation-search/src/interpolation_search.cpp
> +    std::cout << left << right << std::endl;
Уберите дебажный вывод

2021-04-24 11:05 UTC, katsum25 commented on modules/interpolation-search/src/interpolation_search.cpp
> +
чисто из эстетических соображений здесь лучше сделать одну пустую строку

2021-04-24 11:31 UTC, gitlng commented
одобряю

2021-04-24 12:18 UTC, katsum25 approved these changes

2021-04-24 16:19 UTC, gitlng approved these changes
и еще раз одобряю

2021-04-25 04:38 UTC, streltsova-yana approved these changes

2021-04-25 04:38 UTC, merged