Кузнецов Н.С. 381806-3. ЛР2.
UNN-ITMM-Software/devtools-course-practice pull request #195
Opened 2021-04-24 08:59 UTC by kuznetsov-ns

### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [ ] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [ ] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [ ] Get two approve from your fellow students
- [ ] Take a review from one of the administrators

2021-04-24 17:17 UTC, kuznetsov-ns commented
@Vladislavbul @ArtyomGi проверьте, пожалуйста

2021-04-26 06:21 UTC, Vladislavbul commented on modules/btree_out_search/src/btree.cpp
> +#include "include/btree.h"
Заголовочные файлы лучше разделять пустой строкой.

2021-04-26 06:21 UTC, Vladislavbul commented on modules/btree_out_search/test/test-btree_out_search.cpp
> +#include "include/btree.h"
Заголовочные файлы лучше разделять пустой строкой.

2021-04-26 06:21 UTC, Vladislavbul commented on modules/btree_out_search/test/test-btree_out_search.cpp
> +  EXPECT_EQ(result->value, search_value);
Вместо EXPECT_EQ лучше писать ASSERT_EQ, относиться ко всем тестам.

2021-04-26 06:21 UTC, Vladislavbul commented on modules/btree_out_search/test/test-btree_out_search.cpp
> +  EXPECT_NO_THROW(root = addtree(root, 12));
Следует разделить логические части кода по блокам.

2021-04-26 06:21 UTC, Vladislavbul commented on modules/btree_out_search/test/test-btree_out_search.cpp
> +  EXPECT_NO_THROW(root = addtree(root, 8));
Следует разделить логические части кода по блокам.

2021-04-26 06:21 UTC, Vladislavbul commented on modules/btree_out_search/test/test-btree_out_search.cpp
> +  EXPECT_TRUE(NULL != find(root, search_value));
Следует разделить логические части кода по блокам.

2021-04-26 06:21 UTC, Vladislavbul commented on modules/btree_out_search/test/test-btree_out_search.cpp
> +  EXPECT_TRUE(NULL == find(root, search_value));
Следует разделить логические части кода по блокам.

2021-04-26 06:21 UTC, Vladislavbul commented on modules/btree_out_search/src/btree.cpp
> +tnode* find(tnode* r, int d) {
Следует изменить имена, для легкой читаемости кода.

2021-04-26 06:21 UTC, Vladislavbul commented on modules/btree_out_search/src/btree.cpp
> +tnode* addtree(tnode* p, int x) {
Следует изменить имена, для легкой читаемости кода.

2021-04-26 06:38 UTC, Vladislavbul approved these changes
Теперь всё хорошо.

2021-04-26 07:48 UTC, ArtyomGi requested changes

2021-04-26 07:48 UTC, ArtyomGi commented on modules/btree_out_search/test/test-btree_out_search.cpp
> +TEST(BINARY_TREE, CAN_SEARCH2) {
Лучше давать более "говорящие" названия для тестов. Здесь стоит вместо 2 в названии указать, чем этот тест отличается от первого

2021-04-26 07:48 UTC, ArtyomGi commented on modules/btree_out_search/test/test-btree_out_search.cpp
> +TEST(BINARY_TREE, CAN_SEARCH_WHEN_NOT_FOUND2) {
Аналогично замечанию выше. Стоит избавиться от номеров в названиях тестов

2021-04-26 07:48 UTC, ArtyomGi commented on modules/btree_out_search/test/test-btree_out_search.cpp
> +TEST(BINARY_TREE, CORRECT_SEARCH1) {
Аналогично замечаниям выше

2021-04-26 07:48 UTC, ArtyomGi commented on modules/btree_out_search/test/test-btree_out_search.cpp
> +TEST(BINARY_TREE, CORRECT_SEARCH2) {
Аналогично замечаниям выше

2021-04-26 07:48 UTC, ArtyomGi commented on modules/btree_out_search/test/test-btree_out_search.cpp
> +  ASSERT_TRUE(NULL != find(root, search_value));
Здесь лучше использовать приспособленную для сравнений конструкцию ASSERT_NE, чем ASSERT_TRUE со сравнением

2021-04-26 07:48 UTC, ArtyomGi commented on modules/btree_out_search/test/test-btree_out_search.cpp
> +  ASSERT_TRUE(NULL == find(root, search_value));
Аналогично замечанию выше, необходимо использовать ASSERT_EQ

2021-04-26 07:48 UTC, ArtyomGi commented on modules/btree_out_search/test/test-btree_out_search.cpp
> +  ASSERT_TRUE(NULL == find(root, search_value));
Аналогично замечаниям выше

2021-04-26 07:48 UTC, ArtyomGi commented on modules/btree_out_search/test/test-btree_out_search.cpp
> +  ASSERT_TRUE(NULL != find(root, search_value));
Аналогично замечаниям выше

2021-04-26 07:48 UTC, ArtyomGi commented on modules/btree_out_search/test/test-btree_out_search.cpp
> +  ASSERT_TRUE(NULL == find(root, search_value));
Аналогично замечаниям выше

2021-04-26 07:48 UTC, ArtyomGi commented on modules/btree_out_search/test/test-btree_out_search.cpp
> +  ASSERT_EQ(result->value, search_value);
Желательно в проверке ожидаемый результат ставить на первое место, затем полученный

2021-04-26 07:48 UTC, ArtyomGi commented on modules/btree_out_search/test/test-btree_out_search.cpp
> +  ASSERT_TRUE(result == NULL);
Аналогично замечаниям выше

2021-04-26 07:48 UTC, ArtyomGi commented on modules/btree_out_search/src/btree.cpp
> +  if (tree == NULL) {
Здесь в соответствии со стандартом C++11 желательно использовать nullptr для указателя

2021-04-26 07:48 UTC, ArtyomGi commented on modules/btree_out_search/src/btree.cpp
> +    tree->left = tree->right = NULL;
Аналогично замечанию выше

2021-04-26 07:48 UTC, ArtyomGi commented on modules/btree_out_search/src/btree.cpp
> +  if (tree == NULL) {
Аналогично замечанию выше

2021-04-26 07:48 UTC, ArtyomGi commented on modules/btree_out_search/src/btree.cpp
> +    return NULL;
Аналогично

2021-04-26 07:48 UTC, ArtyomGi commented on modules/btree_out_search/src/btree.cpp
> +    if (tree->left != NULL) {
Аналогично

2021-04-26 07:48 UTC, ArtyomGi commented on modules/btree_out_search/src/btree.cpp
> +      return NULL;
Аналогично

2021-04-26 07:48 UTC, ArtyomGi commented on modules/btree_out_search/src/btree.cpp
> +      return NULL;
Аналогично

2021-04-26 21:35 UTC, WerWebWer approved these changes

2021-04-26 21:35 UTC, merged