Крисеев Михаил - Лабораторная работа № 2
UNN-ITMM-Software/devtools-course-practice pull request #195
Opened 2024-04-12 16:13 UTC by KriseevM

2024-04-12 20:19 UTC, Kuznetsov-Artyom commented
@KriseevM Тегните двух любых студентов из [списка,](https://unn-itmm-software.github.io/devtools-course-practice) чтобы они провели код ревью.

2024-04-13 08:53 UTC, KriseevM commented
@Namxobick 
@relby

2024-04-13 08:55 UTC, Namxobick commented on modules/kriseev_m_vector_3d/src/CMakeLists.txt
> +target_link_libraries(${target} ${LIBRARY_DEPS})
отступ

2024-04-13 08:56 UTC, Namxobick commented on modules/kriseev_m_vector_3d/src/vector_3d.cpp
> +  return Vector3d{this->x / factor, this->y / factor, this->z / factor};
factor = 0?

2024-04-13 08:58 UTC, KriseevM commented on modules/kriseev_m_vector_3d/src/vector_3d.cpp
> +  return Vector3d{this->x / factor, this->y / factor, this->z / factor};
В бесконечность уйдёт 
Надо такое отлавливать, согласен

2024-04-13 11:47 UTC, Namxobick approved these changes

2024-04-13 23:26 UTC, Kuznetsov-Artyom commented
Добавьте в пр описание вашей задачи

2024-04-14 15:46 UTC, relby approved these changes

2024-04-14 16:02 UTC, Kuznetsov-Artyom requested changes
Все хорошо, поправьте пару моментов

2024-04-14 16:02 UTC, Kuznetsov-Artyom commented on modules/kriseev_m_vector_3d/src/vector_3d.cpp
> +  return this->x * this->x + this->y * this->y + this->z * this->z;
Не обязательно постоянно писать `this->`, чтобы обратиться к полю класса. Компилятор неявно добавит это за вас.
```suggestion
  return x * x + y * y + z * z;
```
Повышается удобочитаемость кода.
Поправьте пожалуйста также в других местах

2024-04-14 16:02 UTC, Kuznetsov-Artyom commented on modules/kriseev_m_vector_3d/src/vector_3d.cpp
> +    throw std::runtime_error("Attempted division by zero");
По контексту больше подходит тип исключения `std::invalid_argument` (передается некорректный `factor`)

2024-04-15 00:57 UTC, Kuznetsov-Artyom approved these changes

2024-04-15 00:57 UTC, merged