Соболь - Лабораторная работа №2
UNN-ITMM-Software/devtools-course-practice pull request #196
Opened 2024-04-12 17:10 UTC by BlackAngel2108

2024-04-12 20:19 UTC, Kuznetsov-Artyom commented
@BlackAngel2108 Тегните двух любых студентов из [списка,](https://unn-itmm-software.github.io/devtools-course-practice) чтобы они провели код ревью.

2024-04-13 12:57 UTC, BlackAngel2108 commented
@Amazingkivas  @aaldebarann

2024-04-13 23:26 UTC, Kuznetsov-Artyom commented
Добавьте в пр описание вашей задачи

2024-04-14 10:05 UTC, Amazingkivas commented on modules/sobol_l_bitset_lab2/test/test_main.cpp
> +// Copyright 2024 Makhinya Danil
```suggestion
// Copyright 2024 Sobol Lyubov
```

2024-04-14 10:05 UTC, Amazingkivas commented on modules/sobol_l_bitset_lab2/include/tbitfield.h
> +// Copyright 2024 Sobol Liubov
```suggestion
// Copyright 2024 Sobol Lyubov
```

2024-04-14 10:05 UTC, Amazingkivas commented on modules/sobol_l_bitset_lab2/test/test_tbitfield.cpp
> +// Copyright 2024 Sobol Liubov
```suggestion
// Copyright 2024 Sobol Lyubov
```

2024-04-14 10:42 UTC, Amazingkivas approved these changes

2024-04-14 11:47 UTC, aaldebarann approved these changes

2024-04-14 14:37 UTC, Kuznetsov-Artyom requested changes

2024-04-14 14:37 UTC, Kuznetsov-Artyom commented on modules/sobol_l_bitset_lab2/include/tbitfield.h
> +typedef unsigned int TELEM;
C точки зрения эффективности, почему бы тут не использовать `uint8_t`?
Например у нас есть битовая строка из 32 битов (4 байта), то тут все окей, используем выделенную память по максимуму.
Если вам нужно хранить всего 7 элементов, то оставшиеся 25 будут просто не использованы.
В случае с `uint8_t` и с теми же 7 элементами, не задействован будет всего 1.

Другой пример: 
Нужна битовая строка из 33 элементов.
Расход по памяти:
1) `uint8_t`: 5 байт
2) `uint32_t`: 8 байт

2024-04-14 14:37 UTC, Kuznetsov-Artyom commented on modules/sobol_l_bitset_lab2/include/tbitfield.h
> +};
Добавьте семантику перемещения

2024-04-14 14:37 UTC, Kuznetsov-Artyom commented on modules/sobol_l_bitset_lab2/src/tbitfield.cpp
> +        throw -1;
Если пользовательский код будет перехватывать исключение как-то так:
```cpp
try {
  // Код использующий ваш класс TBiyField
} catch (const std::exception& ex) {
  std::cerr << ex.what() << '\n';
}
```
Исключение будет перехвачено?

2024-04-15 14:25 UTC, BlackAngel2108 commented on modules/sobol_l_bitset_lab2/src/tbitfield.cpp
> +        throw -1;
Да, исключение будет перехвачено. Если написать вместо комментария, к примеру, 
TBitField a(-10);
Я собственно так и протестировала, он мне выдал ошибку.

2024-04-15 14:25 UTC, BlackAngel2108 commented on modules/sobol_l_bitset_lab2/include/tbitfield.h
> +typedef unsigned int TELEM;
Это да, это справедливо, исправлю

2024-04-15 15:37 UTC, Kuznetsov-Artyom commented on modules/sobol_l_bitset_lab2/src/tbitfield.cpp
> +        throw -1;
> Да, исключение будет перехвачено. Если написать вместо комментария, к примеру, TBitField a(-10); Я собственно так и протестировала, он мне выдал ошибку.

Возможно вы имеете ввиду, что исключение будет выброшено (судя по тестам). Действительно, это так, но пользовательский код из примера не сможет его отловить, т.к. `int` не является наследником класса `std::exception` + пользователь не подозревает, что необходимо написать еще один обработчик для типа `int` => при раскрутке стека в попытках найти нужный обработчик, программа дойдет до фрейма с функцией `main`, где тоже вряд ли будет написан нужный обработчик и фрейм с функцией `main` будет удален из стека вызовов и программа завершит свою работу аварийно.

https://rextester.com/FLDE66535

2024-04-16 17:03 UTC, BlackAngel2108 commented
@Kuznetsov-Artyom, я добавила перемещающий оператор и конструктор перемещения, а так же тесты для них. Изменила все throw.

2024-04-16 22:06 UTC, Kuznetsov-Artyom approved these changes

2024-04-16 22:06 UTC, merged