Ткачев А.И. 381806-2. ЛР2.
UNN-ITMM-Software/devtools-course-practice pull request #197
Opened 2021-04-24 10:42 UTC by gitlng

### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [ ] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [ ] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [ ] Get two approve from your fellow students
- [ ] Take a review from one of the administrators

2021-04-24 17:11 UTC, gitlng commented
@Talesard , @katsum25 Прошу проверить

2021-04-24 17:23 UTC, Talesard requested changes

2021-04-24 17:23 UTC, Talesard commented on modules/queue/src/queue.cpp
> +}
тут не хватает пустой строки межу методами

2021-04-24 17:23 UTC, Talesard commented on modules/queue/src/queue.cpp
> +double Queue::getLastData() const {
нужно добавить проверку на nullptr (кинуть исключение если пусто и поймать в тесте)

2021-04-24 17:23 UTC, Talesard commented on modules/queue/src/queue.cpp
> +    for (; current.getNext() != nullptr; size++,
обычный while лучше неполного for

2021-04-24 17:29 UTC, katsum25 commented on modules/queue/src/queue.cpp
> +std::string Queue::toStringData() const {
в данном методе добавить пустые строки, разделяющие логические части

2021-04-24 17:29 UTC, katsum25 commented on modules/queue/test/test_queue.cpp
> +    testing_queue->append(25);
В метод append лучше передавать тип double

2021-04-24 17:29 UTC, katsum25 commented on modules/queue/test/test_queue.cpp
> +TEST(queue_test, comparing_2) {
Заменить имя теста на более понятное

2021-04-24 17:29 UTC, katsum25 commented on modules/queue/test/test_queue.cpp
> +
Поставить пустую строку между #include

2021-04-24 18:06 UTC, Talesard approved these changes

2021-04-24 19:57 UTC, katsum25 approved these changes

2021-04-24 20:00 UTC, gitlng commented
Коммит с исправлениями по ревью, если что, сверху. Называется `review fixes`.

2021-04-24 20:08 UTC, gitlng commented
У меня просто время на винде неправильное было ( на 3 часа раньше ), поэтому коммит по ревью идет раньше, чем ревью замечания.

2021-04-26 21:07 UTC, streltsova-yana requested changes

2021-04-27 09:01 UTC, streltsova-yana commented on modules/queue/src/queue.cpp
> +    delete(first);
Для решения этой проблемы необходимо удалить все узлы очереди, а не только первый

2021-04-27 09:02 UTC, streltsova-yana commented on modules/queue/src/queue.cpp
> +        this->first = nullptr;
Аналогично комментарию в деструкторе

2021-04-27 14:05 UTC, gitlng commented
@streltsova-yana , прошу проверить.

2021-04-27 15:30 UTC, streltsova-yana requested changes

2021-04-27 15:30 UTC, streltsova-yana commented on modules/queue/src/queue.cpp
> +    }
```suggestion
    if (other.isEmpty()) {
        while (first != nullptr) {
            Node* next = first->getNext();
            delete first;
            first = next;
        }
        return *this;
    }

    if (!this->isEmpty()) {
        while (first != nullptr) {
            Node* next = first->getNext();
            delete first;
            first = next;
        }
    }
```

2021-04-27 15:30 UTC, streltsova-yana commented on modules/queue/src/queue.cpp
> +    this->last = new Node();
Лишние строки

2021-04-27 15:30 UTC, streltsova-yana commented on modules/queue/src/queue.cpp
> +    }
Старый вариант был верным
```suggestion
    while (other_first_next) {
        this_first->setNext(new Node(*other_first_next));
        this_first = new Node(*other_first_next);
        other_first_next = other_first_next->getNext();
    }
```

2021-04-27 15:41 UTC, gitlng commented on modules/queue/src/queue.cpp
> +    }
Какой смысл в этом, если я встроил механизм рекурсивного удаления. Когда удаляется `first`, он удаляет свой `frist->next`, который удаляет свой `next`, пока не `nullptr`. В отладке я следим за этим всем. Обратите внимание, пожалуйста, на `Node::~Node()`.

2021-04-27 15:43 UTC, gitlng commented on modules/queue/src/queue.cpp
> +    }
@streltsova-yana

2021-04-27 15:43 UTC, gitlng commented on modules/queue/src/queue.cpp
> +    this->last = new Node();
@streltsova-yana

2021-04-27 15:48 UTC, gitlng commented on modules/queue/src/queue.cpp
> +    }
И так, я думаю, более правильно: каждый класс занимается удалением своих объектов автономно. Так и `queue` занимается `~Queue()` занимается удалением только своих полей, а `~Node()` своих рекурсивно до самого последнего в линейном списке.

2021-04-27 15:49 UTC, gitlng commented
@streltsova-yana, посмотрите, пожалуйста, мои комментарии и новые изменения. Спасибо.

2021-04-27 15:53 UTC, streltsova-yana commented on modules/queue/src/queue.cpp
> +    }
Согласна, прошу прощения, не заметила изменения Node::~Node()

2021-04-27 15:55 UTC, streltsova-yana approved these changes

2021-04-27 15:55 UTC, gitlng commented on modules/queue/src/queue.cpp
> +    }
Это исправил

2021-04-27 15:56 UTC, merged