Саратова Марина. Лабораторная работа №2
UNN-ITMM-Software/devtools-course-practice pull request #198
Opened 2024-04-12 18:17 UTC by Marissa696

2024-04-12 20:19 UTC, Kuznetsov-Artyom commented
@Marissa696 Тегните двух любых студентов из [списка,](https://unn-itmm-software.github.io/devtools-course-practice) чтобы они провели код ревью.

2024-04-12 20:46 UTC, Marissa696 commented
@Instmois @Frenetz

2024-04-12 20:50 UTC, Frenetz commented
Необходимо добавить тест для проверки деления на ноль

2024-04-12 20:56 UTC, Instmois commented
Добавь еще один тест на деление

2024-04-13 19:39 UTC, Marissa696 commented
@Kuznetsov-Artyom

2024-04-13 19:57 UTC, Instmois approved these changes

2024-04-13 20:00 UTC, Frenetz approved these changes

2024-04-13 23:04 UTC, Kuznetsov-Artyom requested changes

2024-04-13 23:04 UTC, Kuznetsov-Artyom commented on modules/saratova_m_complex_number_calc/include/complex_number_calc.h
> +    ComplexCalculator divide(const ComplexCalculator& other) const;
Почему бы не перегрузить соответствующие операторы?
Например есть выражение v1 + v2 * (v3 / v4) - v5, то в вашем случае будет нечто следующее:
```cpp
// Сейчас
auto v6 = v1.add(v2.multiply(v3.divide(v4))).substract(v5)

// Могло быть
auto v6 = v1 + v2 * (v3 / v4) - v5
```

2024-04-13 23:04 UTC, Kuznetsov-Artyom commented on modules/saratova_m_complex_number_calc/test/test_compex_number_calc.cpp
Добавьте пожалуйста тесты с дробными значениями

2024-04-13 23:26 UTC, Kuznetsov-Artyom commented on modules/saratova_m_complex_number_calc/test/test_compex_number_calc.cpp
Также добавьте в пр описание вашей задачи

2024-04-14 08:40 UTC, Marissa696 commented
@Kuznetsov-Artyom , готово

2024-04-14 10:10 UTC, Kuznetsov-Artyom approved these changes
Спасибо за внесённые изменения

2024-04-14 10:11 UTC, merged