Шмелев Иван. Лабораторная работа №2.
UNN-ITMM-Software/devtools-course-practice pull request #199
Opened 2024-04-12 20:49 UTC by luchshiy-shmel

2024-04-12 22:07 UTC, Kuznetsov-Artyom commented
@luchshiy-shmel Тегните двух любых студентов из [списка,](https://unn-itmm-software.github.io/devtools-course-practice) чтобы они провели код ревью.

2024-04-13 19:04 UTC, luchshiy-shmel commented
@Frenetz @Marissa696

2024-04-13 20:22 UTC, Frenetz commented
Необходимо использовать именованные константы вместо магических чисел (0, 1 и 2) в результатах функции orientation

2024-04-13 20:45 UTC, Marissa696 commented
Используй константные ссылки для аргументов в функции orientation (для того, чтобы избежать лишнего копирования объектов)

2024-04-13 21:16 UTC, Marissa696 approved these changes

2024-04-13 21:37 UTC, Frenetz approved these changes

2024-04-13 22:44 UTC, Kuznetsov-Artyom requested changes

2024-04-13 22:44 UTC, Kuznetsov-Artyom commented on modules/shmelev_i_graham_algorithm/test/test_graham_algorithm.cpp
> +    std::vector<std::pair<double, double>> points = {{0, 0}};
```suggestion
    std::vector<std::pair<double, double>> points{{0, 0}};
```
Также поправьте в других местах

2024-04-13 22:44 UTC, Kuznetsov-Artyom commented on modules/shmelev_i_graham_algorithm/src/graham_algorithm.cpp
> +    int n = points.size();
Избегайте числовые конверсии
Аналогично в других местах
```suggestion
    size_t n = points.size();
```

2024-04-13 22:44 UTC, Kuznetsov-Artyom commented on modules/shmelev_i_graham_algorithm/include/graham_algorithm.h
> +    static std::vector<std::pair<double, double>> convexHull
Почему бы не дать данному типу (`std::vector<std::pair<double, double>>`) псевдоним?

2024-04-13 22:44 UTC, Kuznetsov-Artyom commented on modules/shmelev_i_graham_algorithm/test/test_graham_algorithm.cpp
Добавьте тест где будет не менее 10 точек

2024-04-13 23:27 UTC, Kuznetsov-Artyom commented on modules/shmelev_i_graham_algorithm/test/test_graham_algorithm.cpp
Также добавьте в пр описание вашей задачи

2024-04-14 14:54 UTC, luchshiy-shmel commented
@Kuznetsov-Artyom , всё исправил

2024-04-14 15:10 UTC, Kuznetsov-Artyom approved these changes

2024-04-14 15:10 UTC, merged