Троегубова - Лабораторная работа #1
UNN-ITMM-Software/devtools-course-practice pull request #20
Opened 2022-03-24 14:11 UTC by Troeg13

2022-03-25 17:16 UTC, Troeg13 commented
@Polina-Petrova07  @MikhailZarubin

2022-03-25 18:12 UTC, Polina-Petrova07 commented
Хорошая работа =)

2022-03-28 08:10 UTC, MikhailZarubin requested changes

2022-03-28 08:10 UTC, MikhailZarubin commented on modules/complex-number/test/test_troegubova_complex_number.cpp
> +// Copyright 2021 Troegubova Alexandra
Неправильный год

2022-03-28 08:10 UTC, MikhailZarubin commented on modules/complex-number/test/test_troegubova_complex_number.cpp
> +    EXPECT_EQ(re, z.getRe());
Для сравнения double нужно использовать другие функции. Например, ASSERT_NEAR(). В последующих тестах аналогично.

2022-03-29 19:06 UTC, Troeg13 commented
@SHVlader

2022-03-29 21:10 UTC, merged