Дерун Андрей - Лабораторная работа №2
UNN-ITMM-Software/devtools-course-practice pull request #200
Opened 2024-04-12 21:09 UTC by AndrewStiks

2024-04-12 22:08 UTC, Kuznetsov-Artyom commented
@AndrewStiks Тегните двух любых студентов из [списка,](https://unn-itmm-software.github.io/devtools-course-practice) чтобы они провели код ревью.

2024-04-13 11:28 UTC, AndrewStiks commented
@LeakMachine  @PlatonovaMariya  увы рандомайзер выбрал вас:)

2024-04-13 11:49 UTC, PlatonovaMariya commented
Всё хорошо, но можно добавить более строгую проверку индексов элементов матрицы в методах setElement и getElement, чтобы исключить выход за пределы массива.

2024-04-13 13:03 UTC, LeakMachine commented
Просмотрел. Всё в порядке.

2024-04-13 13:30 UTC, Kuznetsov-Artyom commented
> Просмотрел. Всё в порядке.

Апрувните реквест, если вас все устраивает

2024-04-13 16:01 UTC, LeakMachine approved these changes
Проверено.

2024-04-13 17:36 UTC, AndrewStiks commented
> Всё хорошо, но можно добавить более строгую проверку индексов элементов матрицы в методах setElement и getElement, чтобы исключить выход за пределы массива.

Сделал

2024-04-13 17:58 UTC, AndrewStiks commented
> Всё хорошо, но можно добавить более строгую проверку индексов элементов матрицы в методах setElement и getElement, чтобы исключить выход за пределы массива.

@PlatonovaMariya сделал

2024-04-13 19:17 UTC, PlatonovaMariya approved these changes
Всё хорошо

2024-04-13 23:25 UTC, Kuznetsov-Artyom commented
Добавьте описание вашей лабораторной работы в пр

2024-04-14 13:00 UTC, AndrewStiks commented
> Добавьте описание вашей лабораторной работы в пр

@Kuznetsov-Artyom сделал в самом верхнем комменте

2024-04-14 15:22 UTC, Kuznetsov-Artyom requested changes

2024-04-14 15:22 UTC, Kuznetsov-Artyom commented on modules/derun_a_bisymmetric/include/bisymmetric.h
Можете пожалуйста вынести реализацию?

2024-04-14 15:22 UTC, Kuznetsov-Artyom commented on modules/derun_a_bisymmetric/include/bisymmetric.h
> +      std::cerr << "Invalid index\n";
При необходимости пользователь воспользуется методом `what()` при перехвате исключения

2024-04-14 15:22 UTC, Kuznetsov-Artyom commented on modules/derun_a_bisymmetric/include/bisymmetric.h
> +      std::cerr << "Invalid index\n";
аналогично в других местах

2024-04-14 15:22 UTC, Kuznetsov-Artyom commented on modules/derun_a_bisymmetric/include/bisymmetric.h
> +    int i0 = convertIndex(i, j, n);
Дайте более информативное имя переменной

2024-04-14 15:22 UTC, Kuznetsov-Artyom commented on modules/derun_a_bisymmetric/include/bisymmetric.h
> +    }
Избавьтесь от блоков, объявив нужные переменные выше

2024-04-14 18:14 UTC, AndrewStiks commented on modules/derun_a_bisymmetric/include/bisymmetric.h
> +      std::cerr << "Invalid index\n";
Сделал

2024-04-14 18:18 UTC, AndrewStiks commented on modules/derun_a_bisymmetric/include/bisymmetric.h
> +    int i0 = convertIndex(i, j, n);
Сделал

2024-04-14 18:20 UTC, AndrewStiks commented on modules/derun_a_bisymmetric/include/bisymmetric.h
> +    }
Сделал

2024-04-14 18:27 UTC, AndrewStiks commented on modules/derun_a_bisymmetric/include/bisymmetric.h
Вынес реализацию вниз файла. Так как класс шаблонный, реализация может быть только в хедере.

2024-04-15 02:19 UTC, Kuznetsov-Artyom approved these changes

2024-04-15 02:19 UTC, merged