Кириллов Максим. Лабораторная работа №2
UNN-ITMM-Software/devtools-course-practice pull request #201
Opened 2024-04-12 23:36 UTC by krllvv

2024-04-13 13:48 UTC, Kuznetsov-Artyom commented
@krllvv Тегните двух любых студентов из [списка,](https://unn-itmm-software.github.io/devtools-course-practice) чтобы они провели код ревью.

2024-04-13 14:58 UTC, krllvv commented
@Instmois @dmitry-vnn

2024-04-13 16:59 UTC, dmitry-vnn reviewed
Вопрос по реализации. При вызове функции поиска решений, результатом является вектор ответов, почему при отсутствии корней было принято решение о выбрасывании исключения, вместо возврата пустого вектора?

2024-04-13 17:07 UTC, Instmois commented
В методе solve можно добавить проверку на то, что дискриминант равен нулю, и в этом случае возвращать один корень, а не два одинаковых корня. Это позволит избежать дублирования кода и упростить тестирование.

2024-04-13 19:07 UTC, Instmois approved these changes

2024-04-13 19:14 UTC, dmitry-vnn approved these changes

2024-04-13 23:23 UTC, Kuznetsov-Artyom requested changes

2024-04-13 23:23 UTC, Kuznetsov-Artyom commented on modules/kirillov_m_quadratic_solution/include/quadratic_solution.h
> +namespace std {
Вы разработчик стандартной библиотеки?😮
Сделайте отдельную хэш функцию используя функцию предоставляемую стандартной библиотекой

2024-04-13 23:23 UTC, Kuznetsov-Artyom commented on modules/kirillov_m_quadratic_solution/include/quadratic_solution.h
> +    std::pair<bool, std::unordered_set<std::complex<double>>>
Может лучше дать данным типам псевдонимы? (using alias)

2024-04-13 23:23 UTC, Kuznetsov-Artyom commented on modules/kirillov_m_quadratic_solution/src/quadratic_solution.cpp
> +            }
```suggestion
           return { c!=0, {}} 
```

2024-04-13 23:23 UTC, Kuznetsov-Artyom commented on modules/kirillov_m_quadratic_solution/test/test_quadratic_solution.cpp
> +    std::unordered_set<double> expectedRoots = {2, 3};
```suggestion
    std::unordered_set<double> expectedRoots{2, 3};
```
Также поправьте пожалуйста в других местах

2024-04-14 12:42 UTC, krllvv commented
@Kuznetsov-Artyom поправил

2024-04-14 13:58 UTC, Kuznetsov-Artyom approved these changes

2024-04-14 13:58 UTC, merged