Юрин С. И. 381806-2. ЛР2.
UNN-ITMM-Software/devtools-course-practice pull request #203
Opened 2021-04-24 17:34 UTC by stasyurin

### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [ ] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [x] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [ ] Get two approve from your fellow students
- [ ] Take a review from one of the administrators

2021-04-24 17:39 UTC, stasyurin commented
@diligentConcernist, @prokofeval, проверьте пожалуйста

2021-04-24 17:59 UTC, prokofeval commented on modules/fraction-calc-by-using-gcd/test/test_fraction-calc.cpp
> +}
В ASSERT_EQ первым аргументом идёт ожидаемый результат, а вторым реальный. В тестах далее аналогично.

2021-04-24 18:17 UTC, diligentConcernist requested changes
Несколько смущает отсутствие скобок в if'ах и while с единичными строками. Конечно, стайл гайд гугла позволяет такую реализацию, но скобки повышают читаемость (пригодится, когда другой человек выберет твою тему для третьей лабораторной работы).

2021-04-24 18:17 UTC, diligentConcernist commented on modules/fraction-calc-by-using-gcd/src/fraction.cpp
> +    return *this;
Нет покрытия кода. Возможно, ситуацию исправит другая реализация: 
```
void &Fraction::operator=(const Fraction &right) {
  numerator = right.numerator;
  denominator = right.denominator;
}
```

2021-04-24 18:17 UTC, diligentConcernist commented on modules/fraction-calc-by-using-gcd/include/fraction.h
> +
Стоит в комментариях добавить пояснения по аббревиатурам на английском: Greatest Commom Divisor и Least Common Multiple.

2021-04-25 07:55 UTC, prokofeval approved these changes
У меня нет замечаний.

2021-04-25 08:13 UTC, diligentConcernist approved these changes
:ok_hand:

2021-04-25 13:44 UTC, stasyurin commented
@OnlyDeniko, проверь пожалуйста

2021-04-25 19:49 UTC, OnlyDeniko requested changes
Реализуй параметрические тесты, будет выглядеть гораздо красивее.

2021-04-25 19:49 UTC, OnlyDeniko commented on modules/fraction-calc-by-using-gcd/src/fraction.cpp
> +    return a + b;
Написано правильно, исправлять не надо, просто покажу как можно написать не используя `if` , вдруг пригодится :)

```
    while (b) {
        a %= b;
        std::swap(a, b);
    }

    return a;
```

2021-04-25 19:49 UTC, OnlyDeniko commented on modules/fraction-calc-by-using-gcd/src/fraction.cpp
> +    return a * b / gcd(a, b);
Здесь аккуратней нужно быть, дело в переполнении. 
```
    return a / gcd(a, b) * b;
```

2021-04-26 11:20 UTC, OnlyDeniko approved these changes
👍

2021-04-26 11:20 UTC, merged