Чирков Р.Д. 381806-2. ЛР2.
UNN-ITMM-Software/devtools-course-practice pull request #204
Opened 2021-04-24 18:13 UTC by ChirkovRoman

### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [ ] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [ ] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [ ] Get two approve from your fellow students
- [ ] Take a review from one of the administrators

2021-04-24 20:46 UTC, ChirkovRoman commented
@WolfCub15  @stasyurin проверьте, пожалуйста.

2021-04-25 13:36 UTC, stasyurin approved these changes
👌

2021-04-25 15:01 UTC, WolfCub15 requested changes

2021-04-25 15:01 UTC, WolfCub15 commented on modules/reverse-polish-notation/test/test_rpn.cpp
> +
Стандартная библиотека должна идти перед .h файлом Вашего проекта  [пример](https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes)

2021-04-25 15:14 UTC, ChirkovRoman commented on modules/reverse-polish-notation/test/test_rpn.cpp
> +
Благодарю. Поменял порядок и скобки

2021-04-25 15:21 UTC, WolfCub15 approved these changes

2021-04-26 06:44 UTC, dkurt commented on lab-guide/topics.md
> +| Обратная польская запись |Чирков Р.Д. 381806-2| |
Please remove this file from PR

2021-04-27 10:21 UTC, streltsova-yana approved these changes

2021-04-27 10:22 UTC, merged