Виничук Тимофей. Лабораторная работа №2.
UNN-ITMM-Software/devtools-course-practice pull request #207
Opened 2024-04-13 12:32 UTC by V-inTim

Реализация шаблонной функции бинарного поиска в отсортированном массиве на c++.

2024-04-13 13:48 UTC, Kuznetsov-Artyom commented
@V-inTim Тегните двух любых студентов из [списка,](https://unn-itmm-software.github.io/devtools-course-practice) чтобы они провели код ревью.

2024-04-13 15:36 UTC, V-inTim commented
@dmitry-vnn @Awenger444

2024-04-13 16:04 UTC, Awenger444 approved these changes

2024-04-13 16:27 UTC, dmitry-vnn reviewed
Есть замечания по включению заголовочного файла с тестами:
Вместо `#include "../../../3rdparty/gtest/gtest.h"`, следует использовать
`#include <gtest/gtest.h>`.
И ещё, поменяй копирайт в файле с точной входа в тесты

2024-04-14 10:23 UTC, V-inTim commented
> Обратите внимание на включение заголовочного файла с тестами: Вместо `#include "../../../3rdparty/gtest/gtest.h"`, следует использовать `#include <gtest/gtest.h>`. И ещё, поменяй копирайт в файле с точным входом в тесты

поправил

2024-04-15 09:36 UTC, V-inTim commented
@Kuznetsov-Artyom  Привет, ты меня мержить будешь?

2024-04-15 10:51 UTC, dmitry-vnn approved these changes

2024-04-15 22:23 UTC, Kuznetsov-Artyom requested changes

2024-04-15 22:23 UTC, Kuznetsov-Artyom commented on modules/vinichuk_t_binary_search/include/BinarySearch.h
> +    return -1;
Задокументируйте константу -1

2024-04-15 22:23 UTC, Kuznetsov-Artyom commented on modules/vinichuk_t_binary_search/test/test_Vinichuk_Timofey_binary_search.cpp
> +    std::vector<int> v = {1, 2, 3, 4, 5, 6, 7};
```suggestion
    std::vector<int> v{1, 2, 3, 4, 5, 6, 7};
```
Также поправьте пожалуйста в других местах

2024-04-15 22:23 UTC, Kuznetsov-Artyom commented on modules/vinichuk_t_binary_search/test/test_Vinichuk_Timofey_binary_search.cpp
> +    std::vector<int> v1 = { };
```suggestion
    std::vector<int> v1;
```

2024-04-15 22:23 UTC, Kuznetsov-Artyom commented on modules/vinichuk_t_binary_search/test/test_Vinichuk_Timofey_binary_search.cpp
> +    std::vector<int> v1 = { };
Аналогично в других местах

2024-04-18 06:42 UTC, V-inTim commented on modules/vinichuk_t_binary_search/include/BinarySearch.h
> +    return -1;
@Kuznetsov-Artyom Что ты подразумеваешь под задокументировать? Вынести как константу? ты уверен, что её нужно выносить как константу?

2024-04-19 08:55 UTC, Kuznetsov-Artyom commented on modules/vinichuk_t_binary_search/include/BinarySearch.h
> +    return -1;
> @Kuznetsov-Artyom Что ты подразумеваешь под задокументировать? Вынести как константу? ты уверен, что её нужно выносить как константу?

Организуйте что-то наподобие `npos`)
При этом обернув свою функцию и константу в свое пространство имен

В пользовательском коде встреча `именованных констант` дает большую ясность, чем голое `магическое число`, с которым будет сравниваться результат функции

2024-04-20 08:50 UTC, V-inTim commented on modules/vinichuk_t_binary_search/include/BinarySearch.h
> +    return -1;
@Kuznetsov-Artyom я изменил. У меня выпадает ошибка на Linux.
Указывает на то, что libc6-dbg не может быть загружен, потому что указанный URL-адрес не найден.

явно, этот косяк не связан с моим кодом. Что мне делать?

2024-04-21 10:42 UTC, Kuznetsov-Artyom approved these changes

2024-04-21 10:42 UTC, merged

2024-04-21 14:42 UTC, V-inTim commented on modules/vinichuk_t_binary_search/test/test_Vinichuk_Timofey_binary_search.cpp
> +    std::vector<int> v1 = { };
@Kuznetsov-Artyom Все сделал. Смерджи, пожалуйста

2024-04-21 14:48 UTC, Kuznetsov-Artyom commented on modules/vinichuk_t_binary_search/test/test_Vinichuk_Timofey_binary_search.cpp
> +    std::vector<int> v1 = { };
> @Kuznetsov-Artyom Все сделал. Смерджи, пожалуйста

Днём вмержил)