Тушенцова Карина - Лабораторная работа №2
UNN-ITMM-Software/devtools-course-practice pull request #210
Opened 2024-04-13 14:31 UTC by karrin0chka

**Генератор всевозможных перестановок массива**
Алгоритм решения задачи. 
Дана исходная последовательность чисел.
Для получения каждой следующей перестановки необходимо выполнить следующие шаги:

- Смотрим текущую перестановку справа налево и следим за тем, чтобы каждый следующий элемент перестановки был не более чем предыдущий. Как только данное соотношение будет нарушено необходимо остановиться и отметить текущее число.
- Снова смотрим пройденный путь пока не дойдем до первого числа, которое больше чем отмеченное на предыдущем шаге.
- Меняем местами два полученных элемента.
- Теперь в части массива, которая размещена справа от текущего элемента надо отсортировать все числа в порядке возрастания. Поскольку до этого они все были уже записаны в порядке убывания необходимо эту часть подпоследовательность просто перевернуть.

Таким образом мы получили новую последовательность, которая будет рассматриваться в качестве исходной на следующем шаге.

2024-04-13 20:30 UTC, Kuznetsov-Artyom commented
@karrin0chka Тесты должны покрывать 100% написанного функционала, пожалуйста поправьте

Также тегните двух любых студентов из [списка,](https://unn-itmm-software.github.io/devtools-course-practice) чтобы они провели код ревью.

2024-04-14 19:12 UTC, karrin0chka commented
@SokolovaDaria @SmDar1a

2024-04-14 19:15 UTC, SmDar1a commented
Добавь, пожалуйста, тест с массивом из одного элемента

2024-04-14 19:28 UTC, SokolovaDaria commented
@karrin0chka, добавь, пожалуйста, тест, где входной массив содержит положительные и отрицательные значения

2024-04-14 19:34 UTC, SmDar1a approved these changes

2024-04-14 19:35 UTC, SokolovaDaria approved these changes

2024-04-15 03:03 UTC, Kuznetsov-Artyom requested changes

2024-04-15 03:03 UTC, Kuznetsov-Artyom commented on modules/tushentsova_k_permut_generator/src/permut_generator.cpp
> +        throw std::string("invalid value");
Лучше использовать типы исключений предоставляемые стандартной библиотекой. В вашем случае отлично подойдет `std::invalid_argument`

2024-04-15 03:03 UTC, Kuznetsov-Artyom commented on modules/tushentsova_k_permut_generator/src/permut_generator.cpp
> +    std::string result = "";
```suggestion
    std::string result;
```

2024-04-15 03:03 UTC, Kuznetsov-Artyom commented on modules/tushentsova_k_permut_generator/src/permut_generator.cpp
> +}
Для чего тут возвращаемый тип `bool`? Если в конечном итоге результат будет всегда `true`

2024-04-15 03:03 UTC, Kuznetsov-Artyom commented on modules/tushentsova_k_permut_generator/src/permut_generator.cpp
> +        throw std::string("invalid value");
также поправьте в других местах, выбрав подходящие по смыслу типы исключений

2024-04-15 03:03 UTC, Kuznetsov-Artyom commented on modules/tushentsova_k_permut_generator/test/test_permut_generator.cpp
> +    int a[size] = { 0 };
```suggestion
    int a[size]{ 0 };
```
Также пожалуйста поправьте в других местах

2024-04-15 07:35 UTC, karrin0chka commented on modules/tushentsova_k_permut_generator/test/test_permut_generator.cpp
> +    int a[size] = { 0 };
Все поправки внесены

2024-04-15 08:42 UTC, Kuznetsov-Artyom approved these changes
Спасибо за внесенные изменения

2024-04-15 08:43 UTC, merged