Иванченко Алексей - Лабораторная работа #2
UNN-ITMM-Software/devtools-course-practice pull request #211
Opened 2024-04-13 14:41 UTC by aaldebarann

Метрики в пространстве float векторов (L1, L2, L3, L4, Linf)

2024-04-13 20:28 UTC, Kuznetsov-Artyom commented
@aaldebarann Тегните двух любых студентов из [списка,](https://unn-itmm-software.github.io/devtools-course-practice) чтобы они провели код ревью.

2024-04-14 10:30 UTC, aaldebarann commented
@ismukhin 
@Amazingkivas

2024-04-14 11:11 UTC, Amazingkivas requested changes

2024-04-14 11:11 UTC, Amazingkivas commented on modules/ivanchenko_a_metrics/src/metrics.cpp
> +float metrics::l1(std::vector<float> v1, std::vector<float> v2) {
Лучше передавать векторы по константной ссылке (const reference), чтобы избежать копирования
```suggestion
float metrics::l1(const std::vector<float>& v1, const std::vector<float>& v2) {
```

Аналогично для остальных функций

2024-04-14 11:11 UTC, Amazingkivas commented on modules/ivanchenko_a_metrics/src/metrics.cpp
> +        throw std::invalid_argument("vectors have different sizes");
Можно вынести проверку размеров векторов в отдельную функцию, чтобы уменьшить дублирование кода

2024-04-14 13:38 UTC, ismukhin commented on modules/ivanchenko_a_metrics/test/test_metrics.cpp
> +}
Для лучшего чтения кода лучше тест кейсы отделять пустыми строками.

2024-04-17 08:08 UTC, Amazingkivas approved these changes

2024-04-17 08:34 UTC, ismukhin approved these changes

2024-04-17 10:27 UTC, Kuznetsov-Artyom approved these changes

2024-04-17 10:27 UTC, merged