init
UNN-ITMM-Software/devtools-course-practice pull request #212
Opened 2024-04-13 15:17 UTC by IgorKonovalovAleks

2024-04-13 20:28 UTC, Kuznetsov-Artyom commented
@IgorKonovalovAleks Тегните двух любых студентов из [списка,](https://unn-itmm-software.github.io/devtools-course-practice) чтобы они провели код ревью.

2024-04-13 21:10 UTC, IgorKonovalovAleks commented
@relby @slx52  Проведите ревью, пожалуйста

2024-04-14 09:51 UTC, Amazingkivas commented on modules/konovalov_i_euler_f_lab2/test/test_konovalov_i_euler_f.cpp
> +  std::uniform_int_distribution<std::mt19937::result_type> dist6(1, 1000);
`euler` и `euler_naive` выдают разные значения при аргументе, равном единице. Тест в таком случае может не пройти
```suggestion
  std::uniform_int_distribution<std::mt19937::result_type> dist6(2, 1000);
```

2024-04-14 09:51 UTC, Amazingkivas commented on modules/konovalov_i_euler_f_lab2/test/test_konovalov_i_euler_f.cpp
Следует добавить следующие тесты:

1. Выбрасывание исключения при входном значении, равном нулю, в функции `euler`
2. Выбрасывание исключения при входном значении, равным нулю и меньше нуля, в функции `euler_naive`
3. Проверка выходного значения при минимально возможном значении аргумента из функции `euler_naive`

2024-04-14 15:12 UTC, mada40 commented
👍

2024-04-14 15:19 UTC, Amazingkivas approved these changes

2024-04-14 15:22 UTC, mada40 approved these changes

2024-04-14 15:22 UTC, IgorKonovalovAleks commented
@mada40  @Amazingkivas  спасибо

2024-04-14 15:32 UTC, Kuznetsov-Artyom requested changes

2024-04-14 15:32 UTC, Kuznetsov-Artyom commented on modules/konovalov_i_euler_f_lab2/src/konovalov_i_euler_f.cpp
> +bool EulerFunction::contains_divider(int n, std::vector<int>& v) {
```suggestion
bool EulerFunction::contains_divider(int n, const std::vector<int>& v) {
```
Также добавьте пожалуйста `const` в объявлении

2024-04-14 15:32 UTC, Kuznetsov-Artyom commented on modules/konovalov_i_euler_f_lab2/src/konovalov_i_euler_f.cpp
> +  }
```suggestion
  for (const int& i : v) {
    if (n % i == 0)
      return true;
  }
```

2024-04-14 15:32 UTC, Kuznetsov-Artyom commented on modules/konovalov_i_euler_f_lab2/src/konovalov_i_euler_f.cpp
> +    throw std::runtime_error("invalid number for euler function");
По контексту больше подходит тип исключения `std::invalid_argument`
Аналогично в других местах

2024-04-14 15:49 UTC, Kuznetsov-Artyom approved these changes
Спасибо за внесенные изменения

2024-04-14 15:49 UTC, merged