Пронькин Д. А. 381806-1 ЛР2
UNN-ITMM-Software/devtools-course-practice pull request #213
Opened 2021-04-25 07:17 UTC by r01and3

### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [ ] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [ ] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [ ] Get two approve from your fellow students
- [ ] Take a review from one of the administrators

2021-04-25 07:25 UTC, r01and3 commented
@vla5924 @taktaev-artyom Сделайте ревью, пожалуйста

2021-04-25 08:11 UTC, taktaev-artyom commented on modules/wave-algorithm/include/wave_algorithm.h
> +namespace WaveLib{
Отсутствует пробел перед фигурной скобкой

2021-04-25 08:11 UTC, taktaev-artyom commented on modules/wave-algorithm/include/wave_algorithm.h
> +#include <stdexcept>
Можно отсортировать по алфавиту.

2021-04-25 08:11 UTC, taktaev-artyom commented on modules/wave-algorithm/src/wave_algorithm.cpp
> +#include <algorithm>
Можно отсортировать по алфавиту.

2021-04-25 08:48 UTC, vla5924 requested changes

2021-04-25 08:48 UTC, vla5924 commented on modules/wave-algorithm/include/wave_algorithm.h
> +#define FREE -1
Лучше использовать constexpr или вообще хранить эти константы в enum

2021-04-25 08:48 UTC, vla5924 commented on modules/wave-algorithm/include/wave_algorithm.h
> +using point = std::pair<int, int>;
Имена типов в этом контексте написаны с большой буквы, значит и здесь тоже так нужно.

2021-04-25 08:48 UTC, vla5924 commented on modules/wave-algorithm/include/wave_algorithm.h
> +};  // namespace WaveLib
```suggestion
}  // namespace WaveLib
```

2021-04-25 15:51 UTC, r01and3 commented on modules/wave-algorithm/include/wave_algorithm.h
> +namespace WaveLib{
Исправил

2021-04-25 15:52 UTC, r01and3 commented on modules/wave-algorithm/include/wave_algorithm.h
> +#include <stdexcept>
Исправил

2021-04-25 15:52 UTC, r01and3 commented on modules/wave-algorithm/src/wave_algorithm.cpp
> +#include <algorithm>
Исправил

2021-04-25 15:52 UTC, r01and3 commented on modules/wave-algorithm/include/wave_algorithm.h
> +#define FREE -1
Исправил, решил воспользоваться constexpr

2021-04-25 15:53 UTC, r01and3 commented on modules/wave-algorithm/include/wave_algorithm.h
> +using point = std::pair<int, int>;
Исправил

2021-04-27 10:37 UTC, streltsova-yana commented
Для ускорения прохождения ревью вы можете пригласить сокурсников посмотреть ваш PR, упомянув их в комментариях (или попросить тех, кто уже смотрел, снова посмотреть новые изменения и их заапрувить)

2021-04-27 11:03 UTC, taktaev-artyom approved these changes

2021-04-28 06:32 UTC, r01and3 commented
@vla5924 Внес правки, можешь посмотреть?

2021-04-28 08:23 UTC, vla5924 approved these changes

2021-05-03 15:18 UTC, streltsova-yana requested changes

2021-05-03 15:18 UTC, streltsova-yana commented on modules/wave-algorithm/test/wave_algorithm_test.cpp
> +        WaveLib::Point(2, 0)
testPath не используется

2021-05-03 17:01 UTC, streltsova-yana approved these changes

2021-05-03 17:01 UTC, merged