Власов М. С. 381806-1 ЛР3
UNN-ITMM-Software/devtools-course-practice pull request #214
Opened 2021-04-25 08:44 UTC by vla5924

### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [ ] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [ ] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [ ] Get two approve from your fellow students
- [ ] Take a review from one of the administrators

2021-04-25 09:46 UTC, vlad-gogov requested changes

2021-04-25 09:46 UTC, vlad-gogov commented on modules/qsort/src/qsorter.cpp
> +        return "[ERROR] Unable to sort. " + std::string(e);
Лучше ловить и бросать std::exception

2021-04-25 09:50 UTC, vla5924 commented on modules/qsort/src/qsorter.cpp
> +        return "[ERROR] Unable to sort. " + std::string(e);
Fixed

2021-04-25 09:51 UTC, vlad-gogov approved these changes

2021-04-25 09:56 UTC, MaksimShagov requested changes

2021-04-25 09:56 UTC, MaksimShagov commented on modules/qsort/src/qsorter.cpp
> +        result += " " + std::to_string(numbers[i]);
Можно использовать stringstream

2021-04-25 09:59 UTC, vla5924 commented on modules/qsort/src/qsorter.cpp
> +        result += " " + std::to_string(numbers[i]);
Fixed

2021-04-25 10:00 UTC, MaksimShagov approved these changes

2021-05-05 17:07 UTC, dkurt approved these changes

2021-05-05 17:07 UTC, merged