Куликов Артём. Лабораторная работа №2.
UNN-ITMM-Software/devtools-course-practice pull request #215
Opened 2024-04-13 18:46 UTC by AveZorgen

library provides static method to find largest common subsequence

2024-04-13 19:07 UTC, AveZorgen commented
@Gr0miLa

2024-04-13 19:08 UTC, Kuznetsov-Artyom commented
@Atikin-NT проведите код ревью своего товарища 😄

2024-04-13 19:10 UTC, AveZorgen commented
@catk1ller007

2024-04-13 19:25 UTC, catk1ller007 approved these changes

2024-04-13 19:25 UTC, Atikin-NT commented
Ваши тесты не обеспечивают полное покрытие. Добавьте пожалуйста следующие случаи:

1) Пустая строка и непустая строка
2) Строки с одинаковыми символами, но в разном порядке.
3) Строки с пробельными символами

2024-04-13 19:28 UTC, AveZorgen commented
> Ваши тесты не обеспечивают полное покрытие. Добавьте пожалуйста следующие случаи:
> 
> 1. Пустая строка и непустая строка
> 2. Строки с одинаковыми символами, но в разном порядке.
> 3. Строки с пробельными символами

Полное покрытие кода тестами достоверно утверждает Codecov. Ваше же предложение демонстрирует вашу неопытность в данной задаче.

2024-04-13 19:31 UTC, Atikin-NT commented
@AveZorgen, понимаю вашу позицию, однако полное покрытие кода тестами не всегда гарантирует отсутствие ошибок. Добавление дополнительных тестовых случаев позволяет более полно проверить функциональность алгоритма и обнаружить потенциальные проблемы. Если у вас есть какие-то опасения или предложения по улучшению тестов, буду рад услышать их.

2024-04-13 19:38 UTC, AveZorgen commented
> @AveZorgen, понимаю вашу позицию, однако полное покрытие кода тестами не всегда гарантирует отсутствие ошибок. Добавление дополнительных тестовых случаев позволяет более полно проверить функциональность алгоритма и обнаружить потенциальные проблемы. Если у вас есть какие-то опасения или предложения по улучшению тестов, буду рад услышать их.

Понимаю вашу точку зрения и ценю ваше внимание к качеству тестирования. Однако, у нас есть временные и организационные ограничения, которые не позволяют нам охватить все потенциальные случаи тестирования. Добавление бесконечного количества тестовых случаев может затянуть процесс разработки и противоречить нашей текущей задаче. Мы всё-таки ориентированы на конкретные цели курса и изучаемые нами концепции, так что внесение дополнительных тестовых случаев, выходящих за рамки обучения, может отвлечь нас от основной цели.

2024-04-13 19:42 UTC, catk1ller007 commented
@AveZorgen, Я чувствую некоторое разочарование и недоумение по этому поводу, так как замечания и заметки играют важную роль в нашей работе и помогают нам улучшить процесс и результаты. Было бы замечательно, если бы вы проявили больше ответственности и внимания к деталям, чтобы мы могли эффективнее работать в команде и достигать поставленных целей.

2024-04-13 19:45 UTC, AveZorgen commented
> @AveZorgen, Я чувствую некоторое разочарование и недоумение по этому поводу, так как замечания и заметки играют важную роль в нашей работе и помогают нам улучшить процесс и результаты. Было бы замечательно, если бы вы проявили больше ответственности и внимания к деталям, чтобы мы могли эффективнее работать в команде и достигать поставленных целей.

Ваши замечание не являются конструктивными - я позволю себе проигнорировать их.

2024-04-13 19:51 UTC, Kuznetsov-Artyom commented
@catk1ller007 
@Atikin-NT 
Если вас все устраивает - апрувните 😺 
Если нет - change request

2024-04-13 19:52 UTC, Atikin-NT commented
> > @AveZorgen, понимаю вашу позицию, однако полное покрытие кода тестами не всегда гарантирует отсутствие ошибок. Добавление дополнительных тестовых случаев позволяет более полно проверить функциональность алгоритма и обнаружить потенциальные проблемы. Если у вас есть какие-то опасения или предложения по улучшению тестов, буду рад услышать их.
> 
> Понимаю вашу точку зрения и ценю ваше внимание к качеству тестирования. Однако, у нас есть временные и организационные ограничения, которые не позволяют нам охватить все потенциальные случаи тестирования. Добавление бесконечного количества тестовых случаев может затянуть процесс разработки и противоречить нашей текущей задаче. Мы всё-таки ориентированы на конкретные цели курса и изучаемые нами концепции, так что внесение дополнительных тестовых случаев, выходящих за рамки обучения, может отвлечь нас от основной цели.

Вы ошибаетесь.

1) Временные ограничения были поставлены заблаговременно с учетом ревью кода и если вы не успеваете, то это ваша проблема. 
2) Я вас не прошу писать бесконечное число тестов, а только 3. И за то время пока вы противитесь уже могли бы всё поправить.
3) Основная цель курса - обучение, а не выполнение задач бизнеса, где горят сроки. И в данный момент вы противитесь этой цели, которая является основной.

2024-04-13 19:54 UTC, AveZorgen commented
> > > @AveZorgen, понимаю вашу позицию, однако полное покрытие кода тестами не всегда гарантирует отсутствие ошибок. Добавление дополнительных тестовых случаев позволяет более полно проверить функциональность алгоритма и обнаружить потенциальные проблемы. Если у вас есть какие-то опасения или предложения по улучшению тестов, буду рад услышать их.
> > 
> > 
> > Понимаю вашу точку зрения и ценю ваше внимание к качеству тестирования. Однако, у нас есть временные и организационные ограничения, которые не позволяют нам охватить все потенциальные случаи тестирования. Добавление бесконечного количества тестовых случаев может затянуть процесс разработки и противоречить нашей текущей задаче. Мы всё-таки ориентированы на конкретные цели курса и изучаемые нами концепции, так что внесение дополнительных тестовых случаев, выходящих за рамки обучения, может отвлечь нас от основной цели.
> 
> Вы ошибаетесь.
> 
> 1. Временные ограничения были поставлены заблаговременно с учетом ревью кода и если вы не успеваете, то это ваша проблема.
> 2. Я вас не прошу писать бесконечное число тестов, а только 3. И за то время пока вы противитесь уже могли бы всё поправить.
> 3. Основная цель курса - обучение, а не выполнение задач бизнеса, где горят сроки. И в данный момент вы противитесь этой цели, которая является основной.

Наша дискуссия заходит в тупик. Пожалуйста, прислушайтесь к @Kuznetsov-Artyom

2024-04-13 19:57 UTC, Atikin-NT commented
@AveZorgen, @Kuznetsov-Artyom меня сам вызвал и попросил вас проверить. Собственно я и выполняю свою роль. Продублирую свои замечания, если вы их потеряли в процессе диалога


Добавьте пожалуйста следующие случаи:

1) Пустая строка и непустая строка
2) Строки с одинаковыми символами, но в разном порядке.
3) Строки с пробельными символами

2024-04-13 20:01 UTC, Kuznetsov-Artyom commented
> @AveZorgen, @Kuznetsov-Artyom меня сам вызвал и попросил вас проверить. Собственно я и выполняю свою роль. Продублирую свои замечания, если вы их потеряли в процессе диалога
> 
> Добавьте пожалуйста следующие случаи:
> 
> 1. Пустая строка и непустая строка
> 2. Строки с одинаковыми символами, но в разном порядке.
> 3. Строки с пробельными символами

Ну так я и написал, кидайте запрос на изменение, или аппрув :)

2024-04-13 20:04 UTC, Atikin-NT requested changes
Добавьте пожалуйста следующие случаи в тесты:

1) Пустая строка и непустая строка
2) Строки с одинаковыми символами, но в разном порядке.
3) Строки с пробельными символами

2024-04-13 20:05 UTC, catk1ller007 commented
> > @AveZorgen, Я чувствую некоторое разочарование и недоумение по этому поводу, так как замечания и заметки играют важную роль в нашей работе и помогают нам улучшить процесс и результаты. Было бы замечательно, если бы вы проявили больше ответственности и внимания к деталям, чтобы мы могли эффективнее работать в команде и достигать поставленных целей.
> 
> Ваши замечание не являются конструктивными - я позволю себе проигнорировать их.

Я понимаю, что мои замечания могут показаться вам неконструктивными, но они основаны на моем опыте и желании улучшить нашу работу. Буду рад обсудить с вами любые возможные улучшения и найти компромиссное решение, которое будет удовлетворительным для всех сторон. Однако, мой коллега также обратил ваше внимание на некоторые аспекты, не могли бы вы уделить им внимание и внести необходимые коррективы?

2024-04-13 20:06 UTC, Kuznetsov-Artyom commented on modules/kulikov_a_lab2/include/lcs.h
> +class LCS {
Дайте более информативное название классу или добавьте brief

2024-04-13 20:08 UTC, AveZorgen commented
> > > @AveZorgen, Я чувствую некоторое разочарование и недоумение по этому поводу, так как замечания и заметки играют важную роль в нашей работе и помогают нам улучшить процесс и результаты. Было бы замечательно, если бы вы проявили больше ответственности и внимания к деталям, чтобы мы могли эффективнее работать в команде и достигать поставленных целей.
> > 
> > 
> > Ваши замечание не являются конструктивными - я позволю себе проигнорировать их.
> 
> Я понимаю, что мои замечания могут показаться вам неконструктивными, но они основаны на моем опыте и желании улучшить нашу работу. Буду рад обсудить с вами любые возможные улучшения и найти компромиссное решение, которое будет удовлетворительным для всех сторон. Однако, мой коллега также обратил ваше внимание на некоторые аспекты, не могли бы вы уделить им внимание и внести необходимые коррективы?

Извините за путаницу, вот исправленная версия кода:

2024-04-13 20:12 UTC, Gr0miLa commented
Я считаю всё круто

2024-04-13 20:12 UTC, Gr0miLa approved these changes

2024-04-13 22:49 UTC, Kuznetsov-Artyom commented
> @AveZorgen, @Kuznetsov-Artyom меня сам вызвал и попросил вас проверить. Собственно я и выполняю свою роль. Продублирую свои замечания, если вы их потеряли в процессе диалога
> 
> Добавьте пожалуйста следующие случаи:
> 
> 1. Пустая строка и непустая строка
> 2. Строки с одинаковыми символами, но в разном порядке.
> 3. Строки с пробельными символами

@AveZorgen

2024-04-13 23:16 UTC, Kuznetsov-Artyom approved these changes

2024-04-13 23:16 UTC, merged

2024-04-14 18:17 UTC, Atikin-NT reviewed
Cool