Гогов В.И. 381806-1 ЛР3
UNN-ITMM-Software/devtools-course-practice pull request #215
Opened 2021-04-25 09:19 UTC by vlad-gogov

### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [ ] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [ ] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [ ] Get two approve from your fellow students
- [ ] Take a review from one of the administrators

2021-04-25 09:42 UTC, vlad-gogov commented
@vla5924 @taktaev-artyom

2021-04-25 09:46 UTC, vla5924 requested changes

2021-04-25 09:46 UTC, vla5924 commented on modules/30_rule/src/cellular_state_application.cpp
> +#include <vector>
Заголовки можно отсортировать.

2021-04-25 09:46 UTC, vla5924 commented on modules/30_rule/src/cellular_state_application.cpp
> +            throw std::runtime_error(" invalid arguments");
```suggestion
            throw std::runtime_error("invalid arguments");
```

2021-04-25 09:46 UTC, vla5924 commented on modules/30_rule/src/cellular_state_application.cpp
> +            throw std::runtime_error(" invalid arguments");
```suggestion
            throw std::runtime_error("invalid arguments");
```

2021-04-25 09:55 UTC, vla5924 approved these changes

2021-04-25 10:00 UTC, taktaev-artyom commented on modules/30_rule/src/cellular_state_application.cpp
> +           "Please provide arguments in the following format:\n\n$ " +
Достаточно будет одного \n

2021-04-25 10:04 UTC, taktaev-artyom approved these changes
супер класс

2021-04-25 10:42 UTC, dkurt commented on modules/30_rule/application/main.cpp
> +    std::cout << app(argc, argv);
`std::cout << app(argc, argv) << std::endl;`

Just not to rely on app's flush. Because if there is no `\n` at the output string, there won't be terminal print.

2021-04-25 10:44 UTC, dkurt commented on modules/30_rule/include/cellular_state_application.h
> +};
public methods should go first (user-friendly API practice)

2021-04-25 10:45 UTC, dkurt commented on modules/30_rule/src/cellular_state_application.cpp
> +#include <cstring>
Do we really need this include?

2021-04-25 10:46 UTC, dkurt commented on modules/30_rule/src/cellular_state_application.cpp
> +#include <iostream>
Do we need this include? Seems like there is no `cout` inside

2021-04-25 10:47 UTC, dkurt commented on modules/30_rule/src/cellular_state_application.cpp
> +    }
Let's avoid code duplication and create a separate inline function inside this `.cpp` file.

2021-04-25 10:47 UTC, dkurt commented on modules/30_rule/src/cellular_state_application.cpp
> +    unsigned int cols = static_cast<unsigned int>(std::strlen(argv[3]));
`uint32_t`

2021-04-25 10:52 UTC, dkurt commented on modules/30_rule/src/cellular_state_application.cpp
> +    }
As for me, it's better to show help message in any case. User won't understand from `ERROR: Should be 4 arguments.` anything.

Also, return of help message is not a part of method definition, so I'd suggest this:

```
if (argc != 4) {
  throw std::runtime_error(help(argv[0]));
}
```

2021-04-25 10:53 UTC, dkurt commented on modules/30_rule/src/cellular_state_application.cpp
> +        for (unsigned int j = 0; j < cols; j++) {
Why rows is `int` but `cols` is uint?

2021-04-25 10:55 UTC, dkurt commented on modules/30_rule/src/cellular_state_application.cpp
> +                                                                     : "D");
Please keep `get_state` outside the for loops. Otherwise it's ineffective to call function every time.

2021-04-25 10:56 UTC, dkurt commented on modules/30_rule/src/cellular_state_application.cpp
> +        stream << "\n";
`stream << std::endl;`

Because `\n` is for Linux. Windows rely on `\r\n`

2021-04-25 14:27 UTC, vlad-gogov commented on modules/30_rule/src/cellular_state_application.cpp
> +    }
У вас в примере сделано так же
https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/c89f1b711f7af6c2f39f34cb371ffe95c3cd6161/modules/complex-number/src/complex_calculator.cpp#L70

2021-04-26 05:46 UTC, dkurt commented on modules/30_rule/src/cellular_state_application.cpp
> +    }
Still actual

2021-04-26 05:47 UTC, dkurt commented on modules/30_rule/src/cellular_state_application.cpp
> +    }
Ok

2021-04-26 10:49 UTC, dkurt approved these changes

2021-04-26 10:49 UTC, merged