Шагов М.А. 381806-1. ЛР3
UNN-ITMM-Software/devtools-course-practice pull request #216
Opened 2021-04-25 09:36 UTC by MaksimShagov

### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [ ] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [ ] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [ ] Get two approve from your fellow students
- [ ] Take a review from one of the administrators

2021-04-25 09:55 UTC, vla5924 requested changes

2021-04-25 09:55 UTC, vla5924 commented on modules/vector/include/vector_calculator.h
> +//! @}
```suggestion
```

2021-04-25 09:55 UTC, vla5924 commented on modules/vector/src/vector_calculator.cpp
> +          "and <operation> is one of 'norm', 'dot', '*', 'normalize'.\n";
```suggestion
        std::string(message) +
          "This is a vector calculator application.\n\n" \
          "Please provide arguments in the following format:\n\n" \
          "  $ " + appname + " <v1_x> <v1_y> <v1_z> " \
          "<v2_x> <v2_y> <v2_z> <operation>\n\n" \
          "Where all arguments are double-precision numbers, " \
          "and <operation> is one of 'norm', 'dot', '*', 'normalize'.\n";
```

2021-04-25 09:57 UTC, MaksimShagov commented
@taktaev-artyom

2021-04-25 10:02 UTC, vla5924 requested changes

2021-04-25 10:02 UTC, vla5924 commented on modules/vector/include/vector_calculator.h
> +    } Arguments;
```suggestion
    struct Arguments {
        Vector v_1;
        Vector v_2;
        char operation;
    };
```

2021-04-25 10:04 UTC, vla5924 approved these changes

2021-04-25 10:05 UTC, taktaev-artyom commented on modules/vector/src/vector_calculator.cpp
> +          "Please provide arguments in the following format:\n\n" \
Достаточно будет одного \n

2021-04-25 10:21 UTC, taktaev-artyom approved these changes
for Maksim_Shagov

2021-05-05 18:38 UTC, streltsova-yana approved these changes

2021-05-05 18:38 UTC, merged