Виденева - Лабораторная работа #2.
UNN-ITMM-Software/devtools-course-practice pull request #216
Opened 2024-04-13 20:16 UTC by katrin000

2024-04-13 20:27 UTC, Kuznetsov-Artyom commented
@katrin000 Тегните двух любых студентов из [списка,](https://unn-itmm-software.github.io/devtools-course-practice) чтобы они провели код ревью.

2024-04-13 20:29 UTC, AveZorgen commented
Предлагаю @Atikin-NT, очень авторитетный ревьюер

2024-04-13 20:54 UTC, katrin000 commented
@KasimtcevRoman 
@alesyacurtis 
Проверьте пожалуйста код

2024-04-13 23:29 UTC, Kuznetsov-Artyom commented
Добавьте пожалуйста в пр описание вашей задачи

2024-04-14 14:12 UTC, KasimtcevRoman commented
Все устраивает

2024-04-14 14:16 UTC, KasimtcevRoman approved these changes
Все устраивает

2024-04-14 17:28 UTC, alesyacurtis approved these changes
Все хорошо

2024-04-15 06:28 UTC, Kuznetsov-Artyom requested changes

2024-04-15 06:28 UTC, Kuznetsov-Artyom commented on modules/videneva_polynomial_calculator/include/polynomial_calculator.h
Добавьте пожалуйста перемещающие операции (конструктор перемещения + оператор присваивания с перемещением) и копирующий оператор присваивания.

P.S: В вашем классе вовсе не обязательно объявлять все копирующие и перемещающие операции, а также деструктор. Компилятор может добавить их самостоятельно. 

Также зачем вам класс, со всем открытым функционалом? Можно ли поле `coeff_a` поместить в private секцию?

2024-04-15 06:28 UTC, Kuznetsov-Artyom commented on modules/videneva_polynomial_calculator/src/polynomial_calculator.cpp
> +}
Зачем вам тут очистка вектора? Как вы зайдете в блок конструктора по умолчанию, поле вашего класса (вектор) уже будет проинициализировано конструктором по умолчанию и вектор будет пустым.

2024-04-15 06:28 UTC, Kuznetsov-Artyom commented on modules/videneva_polynomial_calculator/src/polynomial_calculator.cpp
> +}
В вашем классе лучше объявить деструктор как `= default`

2024-04-15 06:28 UTC, Kuznetsov-Artyom commented on modules/videneva_polynomial_calculator/src/polynomial_calculator.cpp
> +    coeff_a.clear();
```suggestion
```

2024-04-15 06:28 UTC, Kuznetsov-Artyom commented on modules/videneva_polynomial_calculator/src/polynomial_calculator.cpp
> +polynomial_calculator(std::vector<double> coeff_a_, int len) {
Передавайте вектор через const ref

2024-04-15 06:28 UTC, Kuznetsov-Artyom commented on modules/videneva_polynomial_calculator/src/polynomial_calculator.cpp
> +    coeff_a.clear();
```suggestion
```

2024-04-15 06:28 UTC, Kuznetsov-Artyom commented on modules/videneva_polynomial_calculator/src/polynomial_calculator.cpp
> +    int size = coeff_a_.size();
Избегайте сужающие преобразования

2024-04-15 06:28 UTC, Kuznetsov-Artyom commented on modules/videneva_polynomial_calculator/src/polynomial_calculator.cpp
> +        throw "The number of coefficients does not correspond to the length!";
Лучше использовать типы исключений, предоставляемые стандартной библиотекой, в вашем примере отлично подойдет тип `std::invalid_argument`

2024-04-15 06:28 UTC, Kuznetsov-Artyom commented on modules/videneva_polynomial_calculator/src/polynomial_calculator.cpp
> +int polynomial_calculator::GetSize() const {
```suggestion
size_t polynomial_calculator::GetSize() const {
```

2024-04-15 06:28 UTC, Kuznetsov-Artyom commented on modules/videneva_polynomial_calculator/src/polynomial_calculator.cpp
> +}
```suggestion
polynomial_calculator::
polynomial_calculator(const polynomial_calculator& _Polynom) : coeff_a(_Polynom.coeff_a) {}
```

2024-04-15 06:28 UTC, Kuznetsov-Artyom commented on modules/videneva_polynomial_calculator/src/polynomial_calculator.cpp
> +}
```suggestion
bool polynomial_calculator::operator !=
(const polynomial_calculator& _Polynom) const {
   return !(*this == _Polynom);
}
```

2024-04-18 10:27 UTC, Kuznetsov-Artyom approved these changes
Спасибо за внесённые изменения

2024-04-18 10:27 UTC, merged