Колесин А.С. 381806-2 ЛР2
UNN-ITMM-Software/devtools-course-practice pull request #217
Opened 2021-04-25 10:49 UTC by palisarbaro

### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [ ] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [ ] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [ ] Get two approve from your fellow students
- [ ] Take a review from one of the administrators

2021-04-25 11:04 UTC, palisarbaro commented
@ChirkovRoman @diligentConcernist проверьте пожалуйста

2021-04-25 11:06 UTC, palisarbaro commented
@dkurt Это вторая лаба, а не третья.

2021-04-25 11:17 UTC, diligentConcernist requested changes

2021-04-25 11:17 UTC, diligentConcernist commented on modules/complex-calc/test/test_main.cpp
> +    ASSERT_DOUBLE_EQ(3.1, comp.getReal());
Здесь и далее нет видимого разделения на Arrange, Act, Assert
Стоит заменить на:
```
double expectedReal = 3.1;
double actualReal;
Complex comp(expectedReal);

actualReal = comp.getReal();

ASSERT_DOUBLE_EQ(expectedReal, actualReal);
```

2021-04-25 11:30 UTC, ChirkovRoman commented on modules/complex-calc/src/complex_number.cpp
> +}
Во всех функциях возвращается Complex(re, im)
Тут сделал бы так же. Удобно видеть чему действительно равны реальная и мнимая части.

2021-04-25 11:38 UTC, ChirkovRoman approved these changes
Всё отлично

2021-04-25 11:40 UTC, diligentConcernist approved these changes
👍🏻

2021-04-25 20:11 UTC, OnlyDeniko requested changes

2021-04-25 20:11 UTC, OnlyDeniko commented on modules/complex-calc/src/complex_number.cpp
> +    double d = comp.real * comp.real + comp.imag * comp.imag;
Здесь можно воспользоваться функцией из STL
```suggestion
    double d = std::hypot(comp.real, comp.imag);
```

2021-04-25 20:11 UTC, OnlyDeniko commented on modules/complex-calc/src/complex_number.cpp
> +    double re = (real * comp.real + imag * comp.imag) / d;
А вдруг `d == 0` ?

2021-04-26 03:29 UTC, palisarbaro commented on modules/complex-calc/src/complex_number.cpp
> +    double d = comp.real * comp.real + comp.imag * comp.imag;
hypot это корень из суммы квадратов, а не просто сумма квадратов

2021-04-26 05:16 UTC, OnlyDeniko approved these changes

2021-04-26 05:16 UTC, merged