Макарычев Сергей. 381806-3. ЛР2.
UNN-ITMM-Software/devtools-course-practice pull request #219
Opened 2021-04-25 11:57 UTC by sergey-makarichev

### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [ ] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [ ] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [ ] Get two approve from your fellow students
- [ ] Take a review from one of the administrators

2021-04-25 19:09 UTC, sergey-makarichev commented
@zaitcev-andrey @Nikita23456 посмотрите, пожалуйста

2021-04-25 20:23 UTC, OnlyDeniko commented on modules/Pqueue/src/Pqueue.cpp
> +    throw "queue is full";
Объясни, пожалуйста, почему решил реализовать очередь фиксированного размера?
Что мне делать если я захочу добавить элементов больше, чем размер очереди?

2021-04-26 05:16 UTC, sergey-makarichev commented on modules/Pqueue/src/Pqueue.cpp
> +    throw "queue is full";
Потому что в задании не было сказано, какую именно приоритетную очередь нужно сделать. Для добавления элементов, количество которых больше, чем размер очереди, нужно или перевыделять память или переделывать через std::vector

2021-04-26 05:25 UTC, OnlyDeniko commented on modules/Pqueue/src/Pqueue.cpp
> +    throw "queue is full";
Переделаешь?

2021-04-26 06:01 UTC, sergey-makarichev commented on modules/Pqueue/src/Pqueue.cpp
> +    throw "queue is full";
Хорошо

2021-04-26 08:38 UTC, zaitcev-andrey commented on modules/Pqueue/test/test_Pqueue.cpp
> +  for (size_t i = 0; i < 5; i++)
Лучше вместо значения 5 как размера массива подставлять el1.size(), а на 109 строке вообще не указывать конкретный размер равный 5, так как если ты захочешь в PriorityQueueElem el1 убрать какие-то элементы или добавить новые, то изменится и размер массива, а значит придётся заменять 5 везде, где она есть, на новый размер, что неудобно и требует лишней траты времени.

2021-04-26 08:38 UTC, zaitcev-andrey commented on modules/Pqueue/test/test_Pqueue.cpp
> +  for (size_t i = 0; i < 5; i++)
Аналогично комментарию выше.

2021-04-26 11:08 UTC, zaitcev-andrey approved these changes
Замечаний больше нет 👍

2021-04-26 11:29 UTC, Nikita23456 commented on modules/Pqueue/test/test_Pqueue.cpp
> +  PriorityQueueElem e2 { 3, 78.9 };
Тут лучше использовать uniform инициализацию

2021-04-26 11:29 UTC, Nikita23456 commented on modules/Pqueue/test/test_Pqueue.cpp
> +  PriorityQueueElem e2 = { 4, 980 };
Тут лучше использовать uniform инициализацию

2021-04-26 11:29 UTC, Nikita23456 commented on modules/Pqueue/test/test_Pqueue.cpp
> +  PriorityQueueElem e2 = { 9, 12.4 };
Аналогично.

2021-04-26 11:29 UTC, Nikita23456 commented on modules/Pqueue/test/test_Pqueue.cpp
> +  PriorityQueueElem e2 = { 12, 231.5 };
Аналогично.

2021-04-26 11:52 UTC, Nikita23456 approved these changes
Все хорошо

2021-04-26 16:40 UTC, sergey-makarichev commented on modules/Pqueue/src/Pqueue.cpp
> +    throw "queue is full";
Исправил

2021-04-27 18:26 UTC, streltsova-yana requested changes

2021-04-27 18:26 UTC, streltsova-yana commented on modules/Pqueue/src/Pqueue.cpp
> +}
При таких данных тест падает

```cpp
std::vector<PriorityQueueElem> arrEl1{ {1, 4}, {2, 3},
    {3, 1}, {4, 10}, {5, 11} };
    PQueue q1(arrEl1.size());
    for (size_t i = 0; i < arrEl1.size(); i++)
        q1.Push(arrEl1[i]);
    q1.Push(PriorityQueueElem({ 3, 45 }));

    std::vector<PriorityQueueElem> arrEl2{ {1, 4}, {2, 3},
    {3, 1}, {3, 45}, {4, 10}, {5, 11} };
    PQueue q2(arrEl2.size());
    for (size_t i = 0; i < arrEl2.size(); i++)
        q2.Push(arrEl2[i]);

    ASSERT_TRUE(q1 == q2);
```

2021-04-28 20:27 UTC, sergey-makarichev commented on modules/Pqueue/src/Pqueue.cpp
> +}
исправил

2021-04-29 14:28 UTC, sergey-makarichev commented
@streltsova-yana посмотри, пожалуйста

2021-05-03 16:35 UTC, streltsova-yana commented
Для удовлетворения codecov можно сделать следующее:

`git checkout main`
`git remote add upstream https://github.com/UNN-ITMM-Software/devtools-course-practice`
`git pull upstream main`
`git rebase main my_branch_name`
`git push origin -f my_branch_name`

2021-05-05 17:33 UTC, streltsova-yana approved these changes

2021-05-05 17:34 UTC, merged