Касимцев Роман - Лабораторная работа №2
UNN-ITMM-Software/devtools-course-practice pull request #220
Opened 2024-04-14 13:04 UTC by KasimtcevRoman

Обратная польская запись - форма записи математических и логических операций, в которой операнды расположены перед знаками операций.

2024-04-14 15:25 UTC, Kuznetsov-Artyom commented
@KasimtcevRoman Тегните двух любых студентов из [списка,](https://unn-itmm-software.github.io/devtools-course-practice) чтобы они провели код ревью.

2024-04-14 16:07 UTC, KasimtcevRoman commented
@ArchiMikael @Alexfrom38 
Проверьте код

2024-04-14 16:09 UTC, Alexfrom38 approved these changes

2024-04-14 18:05 UTC, ArchiMikael approved these changes

2024-04-15 06:50 UTC, Kuznetsov-Artyom requested changes

2024-04-15 06:50 UTC, Kuznetsov-Artyom commented on modules/kasimtcev_r_polskaya_zapis/include/stack.h
Добавьте перемещающие операции (конструктор, оператор присваивания)

2024-04-15 06:50 UTC, Kuznetsov-Artyom commented on modules/kasimtcev_r_polskaya_zapis/src/lex.cpp
> +    if (_t == operation && _val != -1) throw "Error";
Используйте один из типов исключений стандартной библиотекой.

2024-04-21 10:44 UTC, Kuznetsov-Artyom approved these changes

2024-04-21 10:44 UTC, merged