Олюнин Александр - Лабораторная работа №2
UNN-ITMM-Software/devtools-course-practice pull request #221
Opened 2022-04-24 17:33 UTC by PureEvil-UselessMan

2022-04-24 18:37 UTC, PureEvil-UselessMan commented
@ITrickStar

2022-04-24 18:37 UTC, ITrickStar commented
Добавь вызов исключения в случае деления на ноль и тесты вызывающие это исключение

2022-04-24 18:38 UTC, PureEvil-UselessMan commented
@KirillYashin

2022-04-24 18:44 UTC, ITrickStar requested changes
Добавь вызов исключения в случае деления на ноль и тесты вызывающие это исключение

2022-04-24 19:52 UTC, PureEvil-UselessMan commented
> Добавь вызов исключения в случае деления на ноль и тесты вызывающие это исключение

Done.

2022-04-24 19:52 UTC, ITrickStar approved these changes
Good job!

2022-04-25 15:13 UTC, KirillYashin requested changes
Пожалуйста, добавь комментарии к функциям

2022-04-25 17:22 UTC, PureEvil-UselessMan commented
> Пожалуйста, добавь комментарии к функциям

Done.

2022-04-25 17:33 UTC, KirillYashin approved these changes

2022-04-25 18:42 UTC, merged