Новожилова Е. М. 381806-2. ЛР2
UNN-ITMM-Software/devtools-course-practice pull request #223
Opened 2021-04-25 14:28 UTC by delarinq

### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [ ] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [ ] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [ ] Get two approve from your fellow students
- [ ] Take a review from one of the administrators

2021-04-25 19:56 UTC, OnlyDeniko reviewed
Опиши, пожалуйста, в чем состоит модификация стека своими словами

2021-04-25 20:07 UTC, OnlyDeniko requested changes

2021-04-25 20:07 UTC, OnlyDeniko commented on modules/modified_stack_minimums/src/modified_stack_minimums.cpp
> +        last++;
```suggestion
        mem[++last] = std::make_pair(el, el);
```

2021-04-25 20:07 UTC, OnlyDeniko commented on modules/modified_stack_minimums/src/modified_stack_minimums.cpp
> +            mem[last] = elem;
```suggestion
        double last_min = mem[last].second;
        if (last_min > el) {
            mem[++last] = std::make_pair(el, el);
        } else if (last_min < el) {
            mem[++last] = std::make_pair(el, last_min);
```

2021-04-25 20:07 UTC, OnlyDeniko commented on modules/modified_stack_minimums/src/modified_stack_minimums.cpp
> +    return false;
```suggestion
    return !this->operator==(tmp);
```

2021-04-25 20:18 UTC, OnlyDeniko commented on modules/modified_stack_minimums/include/modified_stack_minimums.h
> +    bool isFull();
```suggestion
    bool isFull() const;
```

2021-04-25 20:18 UTC, OnlyDeniko commented on modules/modified_stack_minimums/include/modified_stack_minimums.h
> +    bool isEmpty();
```suggestion
    bool isEmpty() const;
```

2021-04-25 20:18 UTC, OnlyDeniko commented on modules/modified_stack_minimums/include/modified_stack_minimums.h
> +    double getMin();
```suggestion
    double getTop() const;

    double getMin() const;
```

2021-04-25 20:18 UTC, OnlyDeniko commented on modules/modified_stack_minimums/include/modified_stack_minimums.h
> +    bool operator!=(const ModifiedStack& tmp);
```suggestion
    bool operator==(const ModifiedStack& tmp) const;

    bool operator!=(const ModifiedStack& tmp) const;
```

2021-04-25 20:18 UTC, OnlyDeniko commented on modules/modified_stack_minimums/include/modified_stack_minimums.h
> +    int getLast();
```suggestion
    int getSize() const;
    int getLast() const;
```

2021-04-26 04:56 UTC, delarinq commented
> Опиши, пожалуйста, в чем состоит модификация стека своими словами

Каждый элемент моего модифицированного стека - структура pair, где значение первого поля - число, т. е. как в обычном стеке, а значение второго - минимум из всех первых полей этого стека, добавленных до текущего момента. С помощью метода getMin() можно получить минимум из всех чисел стека.

Нужно ещё подробнее? Расписать получше в readme?

2021-04-26 05:22 UTC, OnlyDeniko commented
> > Опиши, пожалуйста, в чем состоит модификация стека своими словами
> 
> Каждый элемент моего модифицированного стека - структура pair, где значение первого поля - число, т. е. как в обычном стеке, а значение второго - минимум из всех первых полей этого стека, добавленных до текущего момента. С помощью метода getMin() можно получить минимум из всех чисел стека.
> 
> Нужно ещё подробнее? Расписать получше в readme?

Мне понятно, ничего расписывать не надо

2021-04-26 05:23 UTC, OnlyDeniko commented
Приглашайте двух студентов на ревью

2021-04-26 05:52 UTC, delarinq commented
@netweel @OlgaMakesThings сделайте пожалуйста ревью

2021-04-26 11:40 UTC, netweel reviewed
1. Выровняй, пожалуйста, код. Исправь наличие или отсутствие пустых строк.
2. Добавь для вариативности тест, где ты используешь цикл для заполнения.

2021-04-26 12:25 UTC, netweel approved these changes

2021-04-26 16:54 UTC, OlgaMakesThings commented
Обработай пожалуйста случай, когда размер стека отрицательный. К тому же к этому случаю нужен будет тест

2021-04-26 16:56 UTC, OlgaMakesThings reviewed
Обработай пожалуйста случай, когда размер стека отрицательный. К тому же к этому случаю нужен будет тест

2021-04-26 17:13 UTC, OlgaMakesThings approved these changes
Спасибо!

2021-04-26 18:11 UTC, delarinq commented
@OnlyDeniko аппрувы получены

2021-04-26 18:45 UTC, OnlyDeniko approved these changes

2021-04-26 18:45 UTC, merged