Смирнова Дарья. Лабораторная работа №2
UNN-ITMM-Software/devtools-course-practice pull request #225
Opened 2024-04-14 15:41 UTC by SmDar1a

**Калькулятор дробей (с использованием НОД)**

Код реализует калькулятор для работы с дробями. FractionCalculator класс, который предоставляет методы и операторы для работы с дробями. Конструкторы класса FractionCalculator для инициализации объектов класса с определенными значениями числителя и знаменателя.

Также реализован метод для нахождения НОД (наибольшего общего делителя) используется для сокращения дроби до простейшего вида после выполнения арифметических операций. Для выполнения арифметических операций перегружены операторы +, -, * и /, которые позволяют выполнять эти операции между двумя дробями. В коде есть проверки на корректность ввода данных (нельзя установить знаменатель равный нулю). В случае некорректных операций выбрасываются соответствующие исключения для обработки ошибок.

2024-04-14 17:21 UTC, SmDar1a commented
@karrin0chka @Instmois

2024-04-14 17:27 UTC, karrin0chka commented
Убери лишние комментарии в тестах

2024-04-14 17:28 UTC, Instmois commented
Добавь тест на проверку умножения дробей и убери лишний комментарий в `TEST(FractionCalculatorTest, Find_NOD_Different_Numbers)`

2024-04-14 17:31 UTC, Instmois commented
Тест на проверку умножения дробей. Например, создать две дроби 2/3 и 3/4 и проверить, что их произведение равно 1/2

2024-04-14 17:51 UTC, Instmois approved these changes

2024-04-14 17:52 UTC, karrin0chka approved these changes

2024-04-14 17:59 UTC, SmDar1a commented
@Kuznetsov-Artyom

2024-04-15 06:54 UTC, Kuznetsov-Artyom requested changes
Все хорошо, поправьте пару моментов

2024-04-15 06:54 UTC, Kuznetsov-Artyom commented on modules/smirnova_d_fraction_calculator/src/fraction_calculator.cpp
> +        throw std::string("Denominator cannot be a zero");
Используйте один из типов исключений стандартной библиотеки. В вашем случае подходит тип исключения `std::invalid_argument`

2024-04-15 06:54 UTC, Kuznetsov-Artyom commented on modules/smirnova_d_fraction_calculator/src/fraction_calculator.cpp
> +        throw std::string("Denominator cannot be a zero");
Также поправьте пожалуйста и в других местах

2024-04-16 07:12 UTC, SmDar1a commented on modules/smirnova_d_fraction_calculator/src/fraction_calculator.cpp
> +        throw std::string("Denominator cannot be a zero");
готово

2024-04-16 11:05 UTC, Kuznetsov-Artyom approved these changes

2024-04-16 11:05 UTC, merged