Соловьев А.Ю. 381806-1. ЛР2
UNN-ITMM-Software/devtools-course-practice pull request #225
Opened 2021-04-25 15:43 UTC by Alexandr-Solovev

### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [ ] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [ ] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [ ] Get two approve from your fellow students
- [ ] Take a review from one of the administrators

2021-04-25 16:05 UTC, RustamovAzer requested changes

2021-04-25 16:05 UTC, RustamovAzer commented on modules/batcher-mergesort/src/mergesort.cpp
> +    if (vec_size %2 != 0) throw "Vector's size must be even";
Лучше вместо строки в данных исключениях кидать объект класса **std::runtime_error**

2021-04-25 16:17 UTC, r01and3 commented on modules/batcher-mergesort/src/mergesort.cpp
> +#include <iostream>
Функции данной библиотеки не используются, можно убрать этот include

2021-04-25 16:26 UTC, Alexandr-Solovev commented on modules/batcher-mergesort/src/mergesort.cpp
> +    if (vec_size %2 != 0) throw "Vector's size must be even";
исправил

2021-04-25 16:26 UTC, Alexandr-Solovev commented on modules/batcher-mergesort/src/mergesort.cpp
> +#include <iostream>
исправил

2021-04-25 16:28 UTC, RustamovAzer approved these changes

2021-04-25 16:37 UTC, taktaev-artyom commented on modules/batcher-mergesort/include/mergesort.h
> +#include <vector>
Почему не в ifndef?

2021-04-25 16:37 UTC, taktaev-artyom commented on modules/batcher-mergesort/include/mergesort.h
> +    void LocalSort(std::vector<double> *a, int l, int r);
Функции, которые не должны быть использованы пользователем, не нуждаются в объявлении в заголовочном файле.

2021-04-25 16:37 UTC, taktaev-artyom commented on modules/batcher-mergesort/src/mergesort.cpp
> +#include <stdexcept>
Для красоты можно отсортировать в алфавитном порядке.

2021-04-25 16:37 UTC, taktaev-artyom commented on modules/batcher-mergesort/src/mergesort.cpp
> +}
Переменную vec_size лучше сделать типа size_t, чтобы не было неявного преобразования типа в конструкторе с параметром у vector.

2021-04-25 16:37 UTC, taktaev-artyom commented on modules/batcher-mergesort/src/mergesort.cpp
> +    for (i = l, j =0; i <= r; i += 2, j++) {
```suggestion
    for (i = l, j = 0; i <= r; i += 2, j++) {
```

2021-04-25 16:37 UTC, taktaev-artyom commented on modules/batcher-mergesort/test/test_batchersort.cpp
> +TEST(BatcherSort_Test, Test_Creating_Vector_Exception) {
```suggestion
TEST(MergeSort_Test, Test_Creating_Vector_Exception) {
```
и так во всех тестах, так как сортировка называется "Сортировка слиянием"

2021-04-25 16:50 UTC, Alexandr-Solovev commented on modules/batcher-mergesort/include/mergesort.h
> +#include <vector>
исправил

2021-04-25 16:50 UTC, Alexandr-Solovev commented on modules/batcher-mergesort/include/mergesort.h
> +    void LocalSort(std::vector<double> *a, int l, int r);
исправил

2021-04-25 16:50 UTC, Alexandr-Solovev commented on modules/batcher-mergesort/src/mergesort.cpp
> +#include <stdexcept>
исправил

2021-04-25 16:50 UTC, Alexandr-Solovev commented on modules/batcher-mergesort/src/mergesort.cpp
> +}
исправил

2021-04-25 16:51 UTC, Alexandr-Solovev commented on modules/batcher-mergesort/src/mergesort.cpp
> +    for (i = l, j =0; i <= r; i += 2, j++) {
исправил, спасибо

2021-04-25 16:53 UTC, Alexandr-Solovev commented on modules/batcher-mergesort/test/test_batchersort.cpp
> +TEST(BatcherSort_Test, Test_Creating_Vector_Exception) {
исправил на Batcher_Merge_Sort_Test

2021-04-25 17:14 UTC, taktaev-artyom commented on modules/batcher-mergesort/test/test_batchersort.cpp
> +    int n = 10;
Здесь и далее нужно сделать n типа size_t.

2021-04-25 17:15 UTC, taktaev-artyom commented on modules/batcher-mergesort/test/test_batchersort.cpp
> +    for (int i = 0; i < n; i++) {
i тоже надо сделать типа size_t здесь и далее

2021-04-25 18:12 UTC, Alexandr-Solovev commented on modules/batcher-mergesort/test/test_batchersort.cpp
> +    for (int i = 0; i < n; i++) {
исправил

2021-04-25 18:12 UTC, Alexandr-Solovev commented on modules/batcher-mergesort/test/test_batchersort.cpp
> +    int n = 10;
исправил

2021-04-25 18:14 UTC, taktaev-artyom approved these changes

2021-04-26 07:13 UTC, r01and3 approved these changes

2021-04-26 12:38 UTC, Alexandr-Solovev commented
@WerWebWer посмотри, пожалуйста

2021-04-26 15:08 UTC, WerWebWer approved these changes

2021-04-26 15:08 UTC, merged