Лебедев А. В. 381803-2. ЛР2
UNN-ITMM-Software/devtools-course-practice pull request #228
Opened 2021-04-25 17:13 UTC by andrewkin77

### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [ ] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [ ] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [ ] Get two approve from your fellow students
- [ ] Take a review from one of the administrators

2021-04-25 17:34 UTC, alxndrvna commented
@andrewkin77 Добавь const в методы, где ничего не меняешь

2021-04-25 17:49 UTC, alxndrvna approved these changes

2021-04-25 19:58 UTC, BrandonRTL requested changes

2021-04-25 19:58 UTC, BrandonRTL commented on modules/deposit_calc/test/test_deposit_calc.cpp
> +    ASSERT_EQ(267, x.getNumberOfDays());
Два асерта в тесте, осуждениенеодобрение.

2021-04-25 20:52 UTC, BrandonRTL approved these changes

2021-04-25 20:52 UTC, BrandonRTL commented
Одобрениенеосуждение.

2021-04-25 21:18 UTC, MADZEROPIE commented on modules/deposit_calc/src/DepositCalc.cpp
> +}
Наверное было бы неплохо иметь конструктор со всеми нужными параметрами?
А чтобы сохранять DRY, вызывать из него set'еры ?

2021-04-25 21:18 UTC, MADZEROPIE commented on modules/deposit_calc/src/DepositCalc.cpp
> +#include "include/DepositCalc.h"
Рекомендуется разделять пустой строкой. ~~(я уже сбился со счёта, сколько раз я это пишу. Зачем я это пишу?!)~~

2021-04-25 21:37 UTC, andrewkin77 commented on modules/deposit_calc/src/DepositCalc.cpp
> +#include "include/DepositCalc.h"
Без проблем, сейчас исправлю

2021-04-26 06:33 UTC, WerWebWer approved these changes

2021-04-26 06:37 UTC, WerWebWer reviewed
Может переделать тесты в параметризованные? для лучшей читаемости, красоты

2021-04-26 09:05 UTC, merged