Лукьянченко И.А. 381806-2. ЛР2
UNN-ITMM-Software/devtools-course-practice pull request #229
Opened 2021-04-25 18:28 UTC by LaQerty

2021-04-25 19:28 UTC, LaQerty commented
@drwff, @splashbros30

2021-04-25 19:28 UTC, drwff commented on modules/number_to_word/test/test_number_to_word.cpp
> +    ASSERT_EQ(res, res);
Сравниваются два одинаковых значения

2021-04-25 19:31 UTC, splashbros30 reviewed
Увеличь числа до миллионов

2021-04-25 19:33 UTC, drwff approved these changes

2021-04-25 20:14 UTC, OnlyDeniko requested changes

2021-04-25 20:14 UTC, OnlyDeniko commented on modules/number_to_word/include/number_to_word.h
> +    std::string get_word();
```suggestion
    std::string get_word() const;
```

2021-04-25 20:14 UTC, OnlyDeniko commented on modules/number_to_word/src/number_to_word.cpp
> +    }
Поправь отступ

2021-04-25 20:28 UTC, LaQerty commented on modules/number_to_word/src/number_to_word.cpp
> +    }
Сейчас все поправлю

2021-04-25 21:13 UTC, splashbros30 approved these changes

2021-04-26 05:12 UTC, OnlyDeniko approved these changes

2021-04-26 05:12 UTC, merged