Булычев В. Д. 381806-3. ЛР2
UNN-ITMM-Software/devtools-course-practice pull request #231
Opened 2021-04-25 20:01 UTC by Vladislavbul

### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [ ] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [ ] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [ ] Get two approve from your fellow students
- [ ] Take a review from one of the administrators

2021-04-26 05:56 UTC, Vladislavbul commented
@Nikita23456 @gurylev-nikita

2021-04-26 06:57 UTC, Nikita23456 commented on modules/conv-and-calc/test/test_bulychev_v_convert_calc.cpp
> +    EXPECT_EQ("8", conv.GetNumberInHex());
Лучше использовать ASSERT_EQ.

2021-04-26 06:57 UTC, Nikita23456 commented on modules/conv-and-calc/test/test_bulychev_v_convert_calc.cpp
> +    EXPECT_EQ("36", conv.GetNumberInHex());
Аналогично выше сказанному.

2021-04-26 06:57 UTC, Nikita23456 commented on modules/conv-and-calc/test/test_bulychev_v_convert_calc.cpp
> +    EXPECT_EQ("8", conv.GetNumberInHex());
Аналогично выше сказанному. Исправь в остальных тестах.

2021-04-26 06:57 UTC, Nikita23456 commented on modules/conv-and-calc/src/NumConvCalc.cpp
> +#include "include/NumConvCalc.h"
Лучше разделять заголовочные файлы пустой строкой.

2021-04-26 08:05 UTC, gurylev-nikita commented on modules/conv-and-calc/test/test_bulychev_v_convert_calc.cpp
> +}
Следует разделить логические части кода для лучшего восприятия.

2021-04-26 08:05 UTC, gurylev-nikita commented on modules/conv-and-calc/test/test_bulychev_v_convert_calc.cpp
> +}
Аналогично в тестах далее.

2021-04-26 08:51 UTC, Nikita23456 approved these changes

2021-04-26 08:53 UTC, gurylev-nikita approved these changes

2021-05-05 17:27 UTC, streltsova-yana requested changes

2021-05-05 17:27 UTC, streltsova-yana commented on modules/conv-and-calc/CMakeLists.txt
> +# include("CTestTests.txt")
Необходимо добавить пустую строку в конец файла

2021-05-05 17:27 UTC, streltsova-yana commented on modules/conv-and-calc/src/NumConvCalc.cpp
> +    }
```suggestion
std::string::iterator it = bin.end();
    do{
        --it;
        cur_digit = *(it) == '0' ? 0 : 1;
        dec_sum = dec_sum + cur_digit * pow(2, p);
        p++;
    } while(it != bin.begin());
```

2021-05-05 17:27 UTC, streltsova-yana commented on modules/conv-and-calc/src/NumConvCalc.cpp
> +        }
```suggestion
        bin_digit_char = bin_digit == 0 ? '0' : '1';
```

2021-05-06 08:08 UTC, streltsova-yana approved these changes

2021-05-06 08:08 UTC, merged