Галкин В.А. 381806-2. ЛР2
UNN-ITMM-Software/devtools-course-practice pull request #232
Opened 2021-04-25 20:01 UTC by Galkin-Vladislav

2021-04-25 22:20 UTC, Galkin-Vladislav commented
@drwff , @Alex-Andr-19

2021-04-26 12:13 UTC, Alex-Andr-19 reviewed
Нет функций получения строк по отдельности

2021-04-27 18:15 UTC, drwff commented on modules/pseudographics/test/test_galkin_vladislav_pseudographics.cpp
> +    ASSERT_EQ(graph.get_Up_graph(), vec_strUp);
Сначала должно идти ожидаемое значение, затем реальное

2021-04-27 18:23 UTC, drwff approved these changes

2021-04-27 19:52 UTC, Alex-Andr-19 approved these changes

2021-04-27 20:26 UTC, OnlyDeniko requested changes

2021-04-27 20:26 UTC, OnlyDeniko commented on modules/pseudographics/include/Pseudographics.h
> +    std::vector<char> get_Down_graph();
```suggestion
    std::vector<char> get_graph() const;
    std::vector<char> get_Up_graph() const;
    std::vector<char> get_Mid_graph() const;
    std::vector<char> get_Down_graph() const;
```

2021-04-27 20:26 UTC, OnlyDeniko commented on modules/pseudographics/include/Pseudographics.h
> +    std::vector<char> vecUp, vecMid, vecDown;
Почему не std::string ?

2021-04-27 20:26 UTC, OnlyDeniko commented on modules/pseudographics/src/Pseudographics.cpp
> +}
Почему не просто `return vecUp;` ?
Вопрос касается всех геттеров

2021-04-27 20:33 UTC, Galkin-Vladislav commented on modules/pseudographics/src/Pseudographics.cpp
> +}
в векторах vecUp/Mid/Down на конце стоит # - определитель конца вектора. Он ставится для общего вектора, чтобы в нем можно было различить строки

2021-04-27 20:35 UTC, Galkin-Vladislav commented on modules/pseudographics/include/Pseudographics.h
> +    std::vector<char> vecUp, vecMid, vecDown;
на векторах более нагляднее выразил grid 3x3 для каждой цифры.

2021-04-28 05:45 UTC, OnlyDeniko approved these changes

2021-04-28 05:48 UTC, merged