Кутарин Александр. Лабораторная работа №2. Двухсторонняя очередь
UNN-ITMM-Software/devtools-course-practice pull request #233
Opened 2024-04-14 19:30 UTC by AleksandrKutarin

2024-04-14 19:53 UTC, GERONlMO commented
Добавь тест на проверку порядка элементов

2024-04-14 20:16 UTC, ekistrimova commented
Напиши тест для проверки работы с большим количеством элементов

2024-04-14 21:49 UTC, ekistrimova approved these changes

2024-04-14 21:49 UTC, GERONlMO approved these changes

2024-04-15 07:14 UTC, Kuznetsov-Artyom requested changes

2024-04-15 07:14 UTC, Kuznetsov-Artyom commented on modules/kutarin_a_lab2/include/deque.h
Переделайте пожалуйста ваш класс под шаблон и допишите тесты на другом типе данных например `double` `std::string` и т.д.

2024-04-15 07:14 UTC, Kuznetsov-Artyom commented on modules/kutarin_a_lab2/include/deque.h
> +};
Что будет, если я напишу нечно следующее:
```cpp
int main() {
  Deque deqOne;
  // Работа с deqOne
  Deque deqTwo = deqOne;
  // Какой-то код
  return 0;
}

2024-04-15 07:14 UTC, Kuznetsov-Artyom commented on modules/kutarin_a_lab2/include/deque.h
Также было бы неплохо добавить метод, позволяющий узнать текущее количество элементов в очереди (например `size()`)

2024-04-15 07:14 UTC, Kuznetsov-Artyom commented on modules/kutarin_a_lab2/test/test_kutarin_a_deque.cpp
Добавьте тесты на копирующие и перемещающие операции (конструкторы, операторы присваивания)

2024-04-15 10:59 UTC, AleksandrKutarin commented on modules/kutarin_a_lab2/include/deque.h
> +};
Код вызовет ошибку компиляции, потому что класс Deque не имеет определенного конструктора копирования.

2024-04-15 15:55 UTC, Kuznetsov-Artyom commented on modules/kutarin_a_lab2/include/deque.h
> +};
> Код вызовет ошибку компиляции, потому что класс Deque не имеет определенного конструктора копирования.

На самом деле все успешно скомпилируется, тут проблема в другом. При создании объекта из другого, в вашем случае, компилятор сгенерирует конструктор копирования за вас, а это и является корнем проблемы. Конструктор копирования сгенерированный компилятором выполняет `поверхностное копирование`, это означает, что все поля создаваемого объекта будут в точности скопированы из исходного. 

Если полем являлся бы например `std::vector`, то проблем не будет, т.к у создаваемого вектора будет вызван конструктор копирования, а у вас в качестве полей используются указатели которые в точности скопируют адреса указателей исходного объекта. Затем при выходе из области видимости объекты будут уничтожены, вызвав деструкторы. Второй объект все успешно уничтожит, затем будет удаляться первый и при попытке очистить память будет `segmentation fault`.

2024-04-15 16:03 UTC, Kuznetsov-Artyom commented on modules/kutarin_a_lab2/test/test_kutarin_a_deque.cpp
@AleksandrKutarin Добавьте пожалуйста семантику перемещения (конструктор перемещения + перемещающий оператор присваивания)

2024-04-16 07:04 UTC, AleksandrKutarin commented on modules/kutarin_a_lab2/test/test_kutarin_a_deque.cpp
Готово

2024-04-16 22:11 UTC, Kuznetsov-Artyom approved these changes

2024-04-16 22:11 UTC, merged