Podyachikh Mikhail. Lab 2
UNN-ITMM-Software/devtools-course-practice pull request #235
Opened 2024-04-14 21:12 UTC by MuUJa

## Chessboard
Described in:
- Size of board `n * n`
- Set of cell which is blocked. Obstacle cells.
  - Cell is described in a pair of numbers. Each coordinate can take values from `[0, n)` interval
## Distance
Found by BFS (Breadth-First Search). If there are no ways between two point on the board, returns `-1`

2024-04-15 16:47 UTC, MuUJa commented
@MorgachevStepan
@Instmois 
Please review PR

2024-04-15 17:19 UTC, MorgachevStepan approved these changes

2024-04-15 17:29 UTC, Instmois approved these changes

2024-04-15 22:31 UTC, Kuznetsov-Artyom requested changes
Все хорошо, поправьте несколько моментов

2024-04-15 22:31 UTC, Kuznetsov-Artyom commented on modules/podyachikh_knight_moves_lab2/include/chess_board.h
> +  explicit ChessBoard(int size = 8, const std::set<Point> &obstacles = {})
Задокументируйте пожалуйста константу 8

2024-04-15 22:31 UTC, Kuznetsov-Artyom commented on modules/podyachikh_knight_moves_lab2/src/chess_board.cpp
> +    throw std::string("Start point is not available");
Если пользовательский код будет перехватывать исключение как-то так:
```cpp
try {
  // Код использующий ваш класс
} catch (const std::exception& ex) {
  std::cerr << ex.what() << '\n';
}
```
Исключение будет перехвачено?

2024-04-15 22:31 UTC, Kuznetsov-Artyom commented on modules/podyachikh_knight_moves_lab2/test/test_Podyachikh_knight_dist.cpp
> +  std::pair<int, int> available = {2, 5};
```suggestion
  std::pair<int, int> available{2, 5};
```
Поправьте пожалуйста в других местах

2024-04-16 21:16 UTC, MuUJa commented on modules/podyachikh_knight_moves_lab2/src/chess_board.cpp
> +    throw std::string("Start point is not available");
Теперь будет

2024-04-17 11:54 UTC, MuUJa commented on modules/podyachikh_knight_moves_lab2/src/chess_board.cpp
> +    throw std::string("Start point is not available");
Теперь будет

2024-04-17 12:09 UTC, Kuznetsov-Artyom approved these changes

2024-04-17 12:09 UTC, merged