Новостроев Иван. Лабораторная работа №2. Линейный односвязный список
UNN-ITMM-Software/devtools-course-practice pull request #236
Opened 2024-04-14 21:29 UTC by GERONlMO

2024-04-14 21:46 UTC, GERONlMO commented
@AleksandrKutarin @esthete014

2024-04-14 21:50 UTC, esthete014 commented
Напиши в pull request описание твоей задачи

2024-04-14 21:54 UTC, AleksandrKutarin commented
Добавь тест на добавление элемента в пустой список

2024-04-14 22:01 UTC, GERONlMO commented
Все готово

2024-04-14 22:06 UTC, AleksandrKutarin approved these changes

2024-04-14 22:07 UTC, esthete014 approved these changes

2024-04-15 22:46 UTC, Kuznetsov-Artyom requested changes

2024-04-15 22:46 UTC, Kuznetsov-Artyom commented on modules/novostroev_i_linear_single_list/include/linked_list.h
Переделайте пожалуйста ваш класс под шаблон

2024-04-15 22:46 UTC, Kuznetsov-Artyom commented on modules/novostroev_i_linear_single_list/include/linked_list.h
> +};
Если пользователь напишет нечто следующее:
```cpp
int main() {
  LinkedList listOne;
  // Работа с линейным списком
  auto listTwo = listOne;
  // Какой-то код
  return 0;
}
```
Все ли будет корректно работать?

2024-04-15 22:46 UTC, Kuznetsov-Artyom commented on modules/novostroev_i_linear_single_list/test/test_linked_list.cpp
Добавьте тесты для копирующих и перемещающий операций (конструкторы, операторы присваивания)

2024-04-24 14:34 UTC, GERONlMO commented on modules/novostroev_i_linear_single_list/test/test_linked_list.cpp
Готово

2024-04-25 07:22 UTC, Kuznetsov-Artyom commented on modules/novostroev_i_linear_single_list/include/linked_list.h
Все хорошо, только не увидел оператор присваивания с копированием и перемещением.
Также вынесите реализацию в конец файла, оставив в объявлении класса только сигнатуры

2024-04-27 12:43 UTC, Kuznetsov-Artyom commented on modules/novostroev_i_linear_single_list/include/linked_list.h
@GERONlMO, доработайте пожалуйста свою работы

2024-04-28 12:31 UTC, GERONlMO commented
@Kuznetsov-Artyom Не совсем понимаю, почему не проходит codecov/project — 93.46% (-6.54%) compared to e387327

2024-04-28 12:57 UTC, Kuznetsov-Artyom commented
Обновите пожалуйста ветку, сейчас разберемся

2024-04-28 13:17 UTC, GERONlMO commented
@Kuznetsov-Artyom Все тоже самое

2024-04-28 21:19 UTC, GERONlMO commented
@Kuznetsov-Artyom Перепробовал все варианты решения проблемы, к сожалению, она не решается

2024-04-28 21:24 UTC, Kuznetsov-Artyom commented
> @Kuznetsov-Artyom Перепробовал все варианты решения проблемы, к сожалению, она не решается

Спасибо, что тегнули. Сейчас посмотрю

2024-04-28 21:26 UTC, Kuznetsov-Artyom commented
@GERONlMO Вы вытягивали актуальные изменения с main ветки?

2024-04-28 21:27 UTC, GERONlMO commented
@Kuznetsov-Artyom Перед добавлением операторов нет

2024-04-28 21:28 UTC, Kuznetsov-Artyom commented
> @Kuznetsov-Artyom Перед добавлением операторов нет

Обновите тогда для начала ветку, а там уже посмотрим

2024-04-28 21:57 UTC, GERONlMO commented
@Kuznetsov-Artyom Все готово, все работает

2024-04-28 22:03 UTC, Kuznetsov-Artyom approved these changes

2024-04-28 22:03 UTC, merged