Troitskiy a lab2
UNN-ITMM-Software/devtools-course-practice pull request #239
Opened 2024-04-14 22:03 UTC by drinkwr

2024-04-14 22:44 UTC, drinkwr commented
@mada40 
@Mishaizlesa

2024-04-14 22:45 UTC, Mishaizlesa commented
добавь еще тест на последовательные удаление и добавление элемента

2024-04-14 22:46 UTC, mada40 approved these changes

2024-04-14 22:48 UTC, mada40 commented
добавь тест на удаление из пустой кучи

2024-04-14 22:51 UTC, Mishaizlesa reviewed
четко

2024-04-14 22:52 UTC, Mishaizlesa approved these changes
четко

2024-04-14 22:54 UTC, mada40 approved these changes

2024-04-15 22:54 UTC, Kuznetsov-Artyom requested changes

2024-04-15 22:54 UTC, Kuznetsov-Artyom commented on modules/troitskiy_a_lab2/include/lab2.h
Вынесите реализацию методов вне класса

2024-04-20 21:35 UTC, drinkwr commented
@Kuznetsov-Artyom в чем проблема ?)

2024-04-27 12:44 UTC, Kuznetsov-Artyom commented
> @Kuznetsov-Artyom в чем проблема ?)

Обновите пожалуйста ветку

2024-04-27 15:12 UTC, merged