Романюк С. С. 381806-2. ЛР2.
UNN-ITMM-Software/devtools-course-practice pull request #241
Opened 2021-04-26 07:59 UTC by Sergo567

### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [ ] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [ ] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [ ] Get two approve from your fellow students
- [ ] Take a review from one of the administrators

2021-04-26 13:04 UTC, Sergo567 commented
@drwff @splashbros30 посмотрите пожалуйста

2021-04-26 13:54 UTC, drwff commented on modules/permutation_generator/test/test.cpp
> +for (int i = 0; i < 4; i++) {
Поправь табуляцию

2021-04-26 13:54 UTC, mercy131 commented on modules/permutation_generator/src/permutation.cpp
> +    int s = a[i];
Разумнее использовать std::swap()...

2021-04-26 13:55 UTC, drwff commented on modules/permutation_generator/src/permutation.cpp
> +    int s = a[i];
Согласен

2021-04-26 14:21 UTC, mercy131 approved these changes

2021-04-26 14:26 UTC, drwff approved these changes

2021-04-26 15:55 UTC, OnlyDeniko requested changes
Сделай параметризированные тесты, здесь будет в тему.

Предлагаю сделать тест, который будет смотреть на все возможные перестановки. Это можно сделать с помощью std::next_permutation. Будет выглядеть примерно так

``` cpp
Permutation p;
int n = 10;
int* test_permutation = new int[n];
test_permutation = p.get_arr(n);
int* true_permutation = new int[n];
true_permutation = p.get_arr(n);

do{
    for (int i = 0;i < n;i++){
        ASSERT_EQ(true_permutation[i], test_permutation[i]);
    }
    p.NextSet(test_permutation, n);
}while(std::next_permutation(true_permutation, true_permutation + n));
```

2021-04-26 17:29 UTC, Sergo567 commented
@OnlyDeniko можешь посмотреть пожалуйста

2021-04-26 18:44 UTC, OnlyDeniko commented
Это не параметризованные тесты. У тебя два последних теста отличаются лишь одной переменной, остальные тесты отличаются массивами.
Пример тут: [https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/modules/complex-number/test/test_simple.cpp#L14](url)

2021-04-27 07:15 UTC, OnlyDeniko commented on modules/permutation_generator/test/test.cpp
> +}
Пример параметризированного теста
```suggestion
typedef testing::TestWithParam<std::tuple<double, double>>
Permutation_Generate_Param;
TEST_P(Permutation_Generate_Param, Test9_Param) {
    Permutation p;

    int n = std::get<0>(GetParam());
    int iterations = std::get<1>(GetParam());

    int* a = new int[n];
    int* checker = new int[n];
    a = p.get_arr(n1);
    checker = p.get_arr(n);
    for (int i = 0; i < iterations;++i){
        for(int j = 0;j < n;++j) ASSERT_EQ(a[j], checker[j]);
        p.NextSet(a, n);
        std::next_permutation(checker, checker + n);
    }
}
```

2021-04-27 20:16 UTC, OnlyDeniko approved these changes

2021-04-27 20:16 UTC, merged