Кистримова Екатерина. Лабораторная работа №2. Модифицированный стек
UNN-ITMM-Software/devtools-course-practice pull request #242
Opened 2024-04-14 23:32 UTC by ekistrimova

2024-04-14 23:39 UTC, esthete014 commented
Добавь тест на переполнение

2024-04-14 23:45 UTC, esthete014 approved these changes

2024-04-14 23:57 UTC, GERONlMO commented
Напиши тест на неверные входные данные

2024-04-15 00:09 UTC, GERONlMO approved these changes

2024-04-15 12:29 UTC, FirewallGR requested changes
Добавь тесты с различными типами данных а не только с <int>

2024-04-17 12:45 UTC, FirewallGR approved these changes

2024-04-17 12:45 UTC, merged