Киселева А.С 381806-2. ЛР2.
UNN-ITMM-Software/devtools-course-practice pull request #242
Opened 2021-04-26 09:05 UTC by netweel

### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [ ] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [ ] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [ ] Get two approve from your fellow students
- [ ] Take a review from one of the administrators

2021-04-26 11:29 UTC, netweel commented
@ChirkovRoman

2021-04-26 11:36 UTC, netweel commented
@delarinq

2021-04-26 11:51 UTC, ChirkovRoman commented on modules/matrix_operations/include/matrix_operations.h
> +    Matrix Transpose();
Поскольку меняется не объект матрицы, а возвращаемый объект, для ясности стоит добавить get в название функции.

2021-04-26 11:51 UTC, ChirkovRoman commented on modules/matrix_operations/test/test_matrix_operations.cpp
> +    Matrix exept(2, 2);
По смыслу тут и далее ожидаемая матрица (expected)
Поэтому названия стоит поменять

2021-04-26 11:51 UTC, ChirkovRoman commented on modules/matrix_operations/src/matrix_operations.cpp
> +}
Подозреваю, что для матрицы с разными длинами сторон, результат не будет квадратным
И, видимо, опечатка в названии i_row_j_col**s**

2021-04-26 12:23 UTC, netweel commented on modules/matrix_operations/src/matrix_operations.cpp
> +}
Данная функция удаляет i строку и j столбец из матрицы.

2021-04-26 12:37 UTC, delarinq commented on modules/matrix_operations/include/matrix_operations.h
> + public:
```suggestion
    std::vector<std::vector<double>> data;


 public:
```
Будет достаточно одной пустой строки перед спецификатором public, выглядит неаккуратно с 3мя.

2021-04-26 12:43 UTC, ChirkovRoman commented on modules/matrix_operations/src/matrix_operations.cpp
> +}
Да, и поэтому i_row_j_col
И размер матрицы нужно поменять
Если мы применим функцию к матрице 6x3, мы должны получить матрицу 5x2, а сейчас матрица обрезается до квадратной

2021-04-26 12:44 UTC, delarinq commented on modules/matrix_operations/include/matrix_operations.h
> +    void set_data(std::vector < std::vector < double>> new_data);
```suggestion
    void set_data(std::vector<std::vector<double>> new_data);
```
Кодстайл разрешает запись без пробелов, и без них метод будет выглядеть приятнее.

2021-04-26 12:51 UTC, netweel commented on modules/matrix_operations/src/matrix_operations.cpp
> +}
Это вспомогательная функция для нахождения детерминанта функции, следовательно всегда будут использоваться квадратные матрицы. Название поменяю. спасибо

2021-04-26 12:59 UTC, ChirkovRoman commented on modules/matrix_operations/src/matrix_operations.cpp
> +}
Хорошо

2021-04-26 13:19 UTC, delarinq approved these changes

2021-04-26 13:20 UTC, ChirkovRoman approved these changes
Замечания учтены

2021-04-27 12:09 UTC, OnlyDeniko requested changes

2021-04-27 12:09 UTC, OnlyDeniko commented on modules/matrix_operations/include/matrix_operations.h
> +    Matrix operator-(Matrix A);
```suggestion
    Matrix operator-(const Matrix& A);
```

2021-04-27 12:09 UTC, OnlyDeniko commented on modules/matrix_operations/include/matrix_operations.h
> +    int Get_Rows();
```suggestion
    int Get_Rows() const;
```

2021-04-27 12:09 UTC, OnlyDeniko commented on modules/matrix_operations/include/matrix_operations.h
> +    int Get_Cols();
```suggestion
    int Get_Cols() const ;
```

2021-04-27 12:09 UTC, OnlyDeniko commented on modules/matrix_operations/include/matrix_operations.h
> +    Matrix Get_Transpose();
```suggestion
    Matrix Get_Transpose() const;
```

2021-04-27 12:09 UTC, OnlyDeniko commented on modules/matrix_operations/include/matrix_operations.h
> +    Matrix GetMatrWithout_i_row_j_col(unsigned int i, unsigned int j);
```suggestion
    Matrix GetMatrWithout_i_row_j_col(unsigned int i, unsigned int j) const;
```

2021-04-27 12:09 UTC, OnlyDeniko commented on modules/matrix_operations/include/matrix_operations.h
> +    double Determinant();
```suggestion
    double Determinant() const;
```

2021-04-27 12:09 UTC, OnlyDeniko commented on modules/matrix_operations/include/matrix_operations.h
> +    void Inverse();
```suggestion
    void Inverse() const;
```

2021-04-27 12:09 UTC, OnlyDeniko commented on modules/matrix_operations/src/matrix_operations.cpp
> +}
Оператор присваивания реализован неверно. Он должен возвращать ссылку на объект класса, а не указатель. Также нужно сделать проверку на самоприсваивание. И снова константная ссылка на аргумент...
```suggestion
Matrix& Matrix::operator=(const Matrix& A) {
    if (this == &A) return *this;
    rows = A.rows;
    cols = A.cols;
    data = A.data;
    return *this;
}
```

2021-04-27 12:09 UTC, OnlyDeniko commented on modules/matrix_operations/src/matrix_operations.cpp
> +}
А вот здесь ты всё сделала правильно, странно, что в других функциях такого нет

2021-04-27 12:09 UTC, OnlyDeniko commented on modules/matrix_operations/include/matrix_operations.h
> +    void set_data(std::vector<std::vector< double>> new_data);
```suggestion
    void set_data(const std::vector<std::vector< double>>& new_data);
```

2021-04-27 13:25 UTC, OnlyDeniko approved these changes

2021-04-27 13:25 UTC, merged