Бодров Даниил. Лабораторная работа 2. Fibonacci Heap
UNN-ITMM-Software/devtools-course-practice pull request #248
Opened 2024-04-15 20:39 UTC by overinvest

В данной лабораторной работе был реализован алгоритм Fibonacci Heap в классе `FibonacciHeap`, который представляет собой структуру данных для эффективной реализации кучи. Алгоритм был реализован с использованием следующих основных функций:

1. Вставка элемента: `insert`
2. Слияние куч: `merge`
3. Извлечение минимального элемента: `extractMin`
4. Уменьшение ключа элемента: `decreaseKey`
5. Удаление элемента: `deleteNode`

Кроме того, были добавлены Google тесты для проверки основных случаев использования класса FibonacciHeap, что позволяет убедиться в корректности реализации алгоритма и его функциональности.

2024-04-15 22:12 UTC, overinvest commented
@catk1ller007

2024-04-15 22:16 UTC, Manymoera approved these changes

2024-04-15 22:22 UTC, catk1ller007 approved these changes

2024-04-15 22:59 UTC, Kuznetsov-Artyom requested changes

2024-04-15 22:59 UTC, Kuznetsov-Artyom commented on modules/bodrov_daniil_fibonacci_heap/include/fibonacci_heap.h
> +  // :)
❓ :)

2024-04-15 23:01 UTC, Kuznetsov-Artyom commented on modules/bodrov_daniil_fibonacci_heap/include/fibonacci_heap.h
> +  // :)
Память сама себя не очистит

2024-04-16 19:07 UTC, Kuznetsov-Artyom commented on modules/bodrov_daniil_fibonacci_heap/include/fibonacci_heap.h
> +  void release(FibonacciHeapNode<T>* heapNode);
Переименуйте пожалуйста имя методу, чтоб оно отображало свою суть (например `clear` или `free`)

2024-04-16 19:15 UTC, Kuznetsov-Artyom approved these changes

2024-04-16 19:18 UTC, catk1ller007 approved these changes

2024-04-16 19:18 UTC, Manymoera approved these changes

2024-04-16 19:25 UTC, merged