Мухин Иван 3821Б1ПМоп3. Лабораторная работа №2. Численное интегрирование.
UNN-ITMM-Software/devtools-course-practice pull request #255
Opened 2024-04-17 11:42 UTC by ismukhin

2024-04-17 12:29 UTC, ismukhin commented
@Amazingkivas 
@aaldebarann

2024-04-17 18:01 UTC, Amazingkivas requested changes

2024-04-17 18:01 UTC, Amazingkivas commented on modules/mukhin_i_numerical_integration/src/integration_methods.cpp
> +    double step = std::abs(xn - x0) / n;
Так как параметр `n` используется в дальнейшем в качестве количества итераций цикла, то лучше его привести к типу _double_ только при вычислении `step` 
```suggestion
    double step = std::abs(xn - x0) / static_cast<double>(n);
 ```

2024-04-17 18:01 UTC, Amazingkivas commented on modules/mukhin_i_numerical_integration/src/integration_methods.cpp
> +    double step = std::abs(xn - x0) / n;
Аналогично
```suggestion
    double step = std::abs(xn - x0) / static_cast<double>(n);
 ```

2024-04-17 18:01 UTC, Amazingkivas commented on modules/mukhin_i_numerical_integration/src/integration_methods.cpp
Можно добавить проверку на корректные аргументы функций

2024-04-17 19:43 UTC, dkurt commented
@ismukhin, сниму delayed после merge - иначе бот её снова поставит.

2024-04-17 19:59 UTC, ismukhin commented on modules/mukhin_i_numerical_integration/src/integration_methods.cpp
> +    double step = std::abs(xn - x0) / n;
Исправлено

2024-04-17 20:00 UTC, ismukhin commented on modules/mukhin_i_numerical_integration/src/integration_methods.cpp
> +    double step = std::abs(xn - x0) / n;
Исправлено

2024-04-17 20:00 UTC, ismukhin commented on modules/mukhin_i_numerical_integration/src/integration_methods.cpp
Добавил проверку на положительность числа разбиений

2024-04-17 20:07 UTC, Amazingkivas approved these changes

2024-04-18 10:03 UTC, aaldebarann commented on modules/mukhin_i_numerical_integration/src/integration_methods.cpp
> +    for (int i = 0; i < n; i++) {
Итерироваться по участкам разбиений лучше с ипользованием переменной типа size_t
То же касается переменной n. Если это число разбиений (как я понял), лучше объявить его size_t

2024-04-19 16:16 UTC, ismukhin commented on modules/mukhin_i_numerical_integration/src/integration_methods.cpp
> +    for (int i = 0; i < n; i++) {
Готово

2024-04-19 16:20 UTC, ismukhin commented
@dkurt, падает один из actions, там не может установить либы, видимо сервер упал, потому что не может айпи найти.

2024-04-19 16:21 UTC, ismukhin commented
```
Suggested packages:
  gdb-doc gdbserver valgrind-dbg valgrind-mpi kcachegrind alleyoop valkyrie
The following NEW packages will be installed:
  gdb libbabeltrace1 libboost-regex1.71.0 libc6-dbg libipt2
  libsource-highlight-common libsource-highlight4v5 libxxhash0 valgrind
0 upgraded, 9 newly installed, 0 to remove and 13 not upgraded.
Need to get 44.4 MB of archives.
After this operation, 135 MB of additional disk space will be used.
Get:1 file:/etc/apt/apt-mirrors.txt Mirrorlist [[14](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions/runs/8756598423/job/24033414838?pr=255#step:5:15)2 B]
Get:2 http://azure.archive.ubuntu.com/ubuntu focal/main amd64 libbabeltrace1 amd64 1.5.8-1build1 [[15](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions/runs/8756598423/job/24033414838?pr=255#step:5:16)6 kB]
Get:10 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu focal/main amd64 gdb amd64 10.2-0ubuntu1~20.04~1 [3282 kB]
Get:3 http://azure.archive.ubuntu.com/ubuntu focal/universe amd64 libipt2 amd64 2.0.1-1 [42.8 kB]
Get:4 http://azure.archive.ubuntu.com/ubuntu focal/universe amd64 libsource-highlight-common all 3.1.8-1.2build5 [50.7 kB]
Get:5 http://azure.archive.ubuntu.com/ubuntu focal/universe amd64 libboost-regex1.71.0 amd64 1.71.0-6ubuntu6 [471 kB]
Get:6 http://azure.archive.ubuntu.com/ubuntu focal/universe amd64 libsource-highlight4v5 amd64 3.1.8-1.2build5 [232 kB]
Get:7 http://azure.archive.ubuntu.com/ubuntu focal/universe amd64 libxxhash0 amd64 0.7.3-1 [15.3 kB]
Ign:8 http://azure.archive.ubuntu.com/ubuntu focal-updates/main amd64 libc6-dbg amd64 2.31-0ubuntu9.14
Get:9 http://azure.archive.ubuntu.com/ubuntu focal-updates/main amd64 valgrind amd64 1:3.15.0-1ubuntu9.1 [20.3 MB]
Ign:8 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libc6-dbg amd64 2.31-0ubuntu9.14
Ign:8 http://security.ubuntu.com/ubuntu focal-updates/main amd64 libc6-dbg amd64 2.31-0ubuntu9.14
Err:8 mirror+file:/etc/apt/apt-mirrors.txt focal-updates/main amd64 libc6-dbg amd64 2.31-0ubuntu9.14
  404  Not Found [IP: 40.81.13.82 80]
E: Failed to fetch mirror+file:/etc/apt/apt-mirrors.txt/pool/main/g/glibc/libc6-dbg_2.31-0ubuntu9.14_amd64.deb  404  Not Found [IP: 40.81.13.82 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Fetched 24.6 MB in 8s (3[19](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions/runs/8756598423/job/24033414838?pr=255#step:5:20)0 kB/s)
Error: Process completed with exit code 100.
```

2024-04-19 20:09 UTC, aaldebarann approved these changes

2024-04-20 17:27 UTC, dkurt commented
@ismukhin, можете попробовать изменить в https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/.github/workflows/main.yml в рамказ своего PR `ubuntu-20.04` на `ubuntu-latest`?

2024-04-20 17:38 UTC, ismukhin commented
@dkurt, добавил apt update, вроде получилось

2024-04-20 17:47 UTC, ismukhin commented
@dkurt, судя по логам, Coverage падает из-за невозможности сбилдить один из модулей 
```
In file included from /home/runner/work/devtools-course-practice/devtools-course-practice/modules/kiselev_i_billinear_interpolation/src/Billinear_interpolation.cpp:3:
/home/runner/work/devtools-course-practice/devtools-course-practice/modules/kiselev_i_billinear_interpolation/include/Billinear_interpolation.h:11:23: error: ‘size_t’ has not been declared
   11 |     Color Calculation(size_t x1, size_t y1, size_t x2, size_t y2);
      |                       ^~~~~~
```

2024-04-20 17:57 UTC, dkurt commented
@ismukhin, давайте тогда `ubuntu-20.04` + `apt update`, чтобы со старым компилятором

2024-04-20 18:01 UTC, ismukhin commented
> @ismukhin, давайте тогда `ubuntu-20.04` + `apt update`, чтобы со старым компилятором

Ок, позже сделаю

2024-04-20 20:06 UTC, ismukhin commented
@dkurt

2024-04-21 08:09 UTC, merged

2024-04-21 10:37 UTC, ismukhin commented
@dkurt, бот вернул метку delayed :(