Соколова Дарья. Лабораторная работа №2. Очередь.
UNN-ITMM-Software/devtools-course-practice pull request #260
Opened 2024-04-18 17:15 UTC by SokolovaDaria

В данной работе я реализовала класс очередь. Он поддерживает основные операции, такие как добавление элемента, извлечение элемента, проверка на пустоту и заполненность, доступ к элементам в начале и конце очереди, а также получение текущего размера очереди.

2024-04-18 17:47 UTC, SokolovaDaria commented
@MorgachevStepan, @karrin0chka, прошу ревью

2024-04-18 17:54 UTC, MorgachevStepan commented on modules/sokolova_d_queue/include/queue.h
> +    explicit Queue(size_t size = 10);
Вынесите число 10 в отдельную константу

2024-04-18 17:54 UTC, MorgachevStepan commented on modules/sokolova_d_queue/include/queue.h
> +        throw std::runtime_error("Queue is full");
Измените ошибку на std::out_of_range. Аналогично в других методах

2024-04-18 18:03 UTC, karrin0chka commented
Добавь тест на проверку выбрасывания исключения при извлечении из пустой очереди

2024-04-18 18:13 UTC, MorgachevStepan approved these changes

2024-04-18 18:29 UTC, karrin0chka approved these changes

2024-04-21 10:47 UTC, Kuznetsov-Artyom requested changes
Все отлично, только поправьте пару моментов

2024-04-21 10:47 UTC, Kuznetsov-Artyom commented on modules/sokolova_d_queue/include/queue.h
Добавьте пожалуйста перемещающие операции (конструктор перемещения, перемещающий оператор присваивания)

2024-04-27 12:50 UTC, Kuznetsov-Artyom commented on modules/sokolova_d_queue/include/queue.h
@SokolovaDaria доработайте пожалуйста свою работу

2024-04-27 16:29 UTC, Kuznetsov-Artyom approved these changes
Спасибо за внесенные изменения

2024-04-27 16:29 UTC, merged