Чистов В.М. 381806-2. ЛР2.
UNN-ITMM-Software/devtools-course-practice pull request #261
Opened 2021-04-26 20:58 UTC by mark0wka

### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [ ] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [ ] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [ ] Get two approve from your fellow students
- [ ] Take a review from one of the administrators

2021-04-27 08:01 UTC, mark0wka commented
@kirill-korniakov не понимаю с чем связана ошибка. Перечисленные там операции используются как в тестах, так и в самом коде.

2021-04-27 10:57 UTC, dkurt commented
@mark0wka, наблюдается взаимосвязь между объявлением методов `friend` и ошибками `The function is never used`. Можете избавиться от `friend`?

2021-04-27 11:23 UTC, mark0wka commented
@dkurt, оператор == тоже обладает ключевым словом friend, но с ним проблем нет, как показывает лог.

2021-04-27 11:25 UTC, dkurt commented on modules/long-arithmetic/src/long_arithmetic.cpp
> +bool operator ==(const bigInt& left, const bigInt& right) {
`bool bigInt::operator ==(const bigInt& left, const bigInt& right) {`

2021-04-27 11:25 UTC, dkurt commented on modules/long-arithmetic/src/long_arithmetic.cpp
> +bool operator <(const bigInt& left, const bigInt& right) {
`bool bigInt::operator <(const bigInt& left, const bigInt& right) {`

2021-04-27 11:26 UTC, dkurt commented
@mark0wka, да, действительно. Ошибка в потерянных `bigInt::` в `.cpp` файле

2021-04-27 11:40 UTC, mark0wka commented
@dkurt, студия пишет, что такая запись некорректна и из-за этого появляются ошибки. И что в случае с оператором ==, что в случае с оператором < - запись одинаковая, но тест на линуксе выводит в логи все операторы с ключевым словом friend, кроме ==.

2021-04-27 11:41 UTC, dkurt commented
@mark0wka, приложите текст ошибки пожалуйста и изменения

2021-04-27 11:48 UTC, mark0wka commented
@dkurt, `bool bigInt::operator ==(const bigInt& left, const bigInt& right) {`, класс "bigInt" не содержит члена "operator=="

2021-04-27 11:49 UTC, dkurt commented
А от `friend` есть возможность отказаться? Зачем нужен?

2021-04-27 16:15 UTC, mark0wka commented
@dkurt, если в лоб убирать, то на операторе вылетает ошибка, что слишком много параметров для этой функции оператора. Конечно, можно попробовать переписать эти функции под один параметр, но это займет много времени.

2021-04-27 16:19 UTC, dkurt commented
@mark0wka, нужно задизайнить без `friend` - сейчас эти операторы просто висят вне класса. Займёт не так много времени, поскольку потребуется лишь заменить первый операнд на `this`.

2021-04-27 19:11 UTC, mark0wka commented
@Galkin-Vladislav  @LaQerty

2021-04-27 19:23 UTC, LaQerty reviewed
Убери лишний код и почисти ненужные комменты.

2021-04-27 19:29 UTC, Galkin-Vladislav commented on modules/long-arithmetic/test/test_long_arithmetic.cpp
> +    ASSERT_EQ(bi3, bi2);
Поменяй везде, где нужно, местами результаты в assert, чтобы было по схеме ASSERT_EQ (ожидаемый, фактический);

2021-04-27 19:38 UTC, LaQerty approved these changes

2021-04-27 19:45 UTC, Galkin-Vladislav approved these changes

2021-04-27 20:15 UTC, OnlyDeniko requested changes

2021-04-27 20:15 UTC, OnlyDeniko commented on modules/long-arithmetic/src/long_arithmetic.cpp
> +const bool bigInt::operator==(const bigInt& right) const {
Зачем тут и везде далее возвращать константные переменные?

2021-04-27 20:15 UTC, OnlyDeniko commented on modules/long-arithmetic/src/long_arithmetic.cpp
> +    }
почему нельзя так? не только здесь, но и в других операторах
```suggestion
    if (left.negFlag && right.negFlag) {
        return left - right;
    } else if (right.negFlag) {
        return left + right;
    }
```

2021-04-27 20:15 UTC, OnlyDeniko commented on modules/long-arithmetic/src/long_arithmetic.cpp
> +    int carry = 0;
`carry` может переполниться?

2021-04-27 20:15 UTC, OnlyDeniko commented on modules/long-arithmetic/src/long_arithmetic.cpp
> +        - 1; i >= 0; --i) {
?
```suggestion
    for (size_t i = left.storage.size() - 1; i >= 0; --i) {
```

2021-04-27 20:15 UTC, OnlyDeniko commented on modules/long-arithmetic/src/long_arithmetic.cpp
> +    this->storage.push_back(this->storage[this->storage.size() - 1]);
```suggestion
    this->storage.push_back(this->storage.back());
```

2021-04-27 20:15 UTC, OnlyDeniko commented on modules/long-arithmetic/src/long_arithmetic.cpp
> +        this->storage[i] = this->storage[i - 1];
Minor: Здесь можно воспользоваться `std::rotate`

2021-04-27 20:15 UTC, OnlyDeniko commented on modules/long-arithmetic/src/long_arithmetic.cpp
> +    }
Вынеси константы типа `0` и `2` за цикл, чтобы они инициализировались только 1 раз, много лишней работы делается

2021-04-27 20:15 UTC, OnlyDeniko commented on modules/long-arithmetic/test/test_long_arithmetic.cpp
> +}
Тест проверяет два абсолютно разных случая, разнеси на два теста

2021-04-27 20:15 UTC, OnlyDeniko commented on modules/long-arithmetic/test/test_long_arithmetic.cpp
> +}
Что проверяет этот тест? Сделай хотя бы проверку на `bi5`

2021-04-27 20:37 UTC, mark0wka commented on modules/long-arithmetic/src/long_arithmetic.cpp
> +}
Просто парная функция с функцией, возвращающей отрицательное значение бигИнта. Но по сути она бесполезна - уберу

2021-04-27 20:44 UTC, mark0wka commented on modules/long-arithmetic/test/test_long_arithmetic.cpp
> +}
Он бесполезный - забыл его убрать

2021-04-28 11:37 UTC, mark0wka commented on modules/long-arithmetic/src/long_arithmetic.cpp
> +    }
Потому что в крайних случаях вылезает ошибка с необработанным исключением. Например, если рассмотреть такие выражения:
 `bigInt c("999999999999999999999"), b("99999999999999999999");
	cout << c + b << endl;
	cout << -c + (-b) << endl;
	cout << -c + b << endl;
cout << c + (-b) << endl;`
Аналогично с оператором "-"

2021-04-28 11:52 UTC, mark0wka commented on modules/long-arithmetic/src/long_arithmetic.cpp
> +        - 1; i >= 0; --i) {
Происходит выход за пределы вектора с сопутствующей ошибкой

2021-04-28 11:55 UTC, mark0wka commented on modules/long-arithmetic/src/long_arithmetic.cpp
> +        for (int64_t i = str.length(); i > 0; i -= 9) {
В данном случае использование size_t приводит к ошибке с выходом за границы. Где было можно - поправил

2021-04-28 15:51 UTC, mark0wka commented on modules/long-arithmetic/test/test_long_arithmetic.cpp
> +}
Исправлено

2021-04-28 15:51 UTC, mark0wka commented on modules/long-arithmetic/src/long_arithmetic.cpp
> +    }
Исправлено

2021-04-28 15:52 UTC, mark0wka commented on modules/long-arithmetic/src/long_arithmetic.cpp
> +    this->storage.push_back(this->storage[this->storage.size() - 1]);
Исправлено

2021-04-28 15:52 UTC, mark0wka commented on modules/long-arithmetic/src/long_arithmetic.cpp
> +const bool bigInt::operator==(const bigInt& right) const {
Исправлено

2021-04-28 15:52 UTC, mark0wka commented on modules/long-arithmetic/src/long_arithmetic.cpp
> +    return true;
Исправлено

2021-04-28 15:52 UTC, mark0wka commented on modules/long-arithmetic/src/long_arithmetic.cpp
> +            return false;
Исправлено

2021-04-28 15:57 UTC, mark0wka commented on modules/long-arithmetic/src/long_arithmetic.cpp
> +    int carry = 0;
Нет, тк BASE 1000000000, что меньше INT_MAX

2021-04-29 12:11 UTC, OnlyDeniko approved these changes

2021-04-29 12:11 UTC, merged