initial commit
UNN-ITMM-Software/devtools-course-practice pull request #267
Opened 2024-04-21 14:23 UTC by AndrewStiks

2024-04-21 15:24 UTC, AndrewStiks commented
@LeakMachine @PlatonovaMariya

2024-04-21 15:34 UTC, PlatonovaMariya approved these changes

2024-04-23 12:25 UTC, LeakMachine approved these changes
Проверено

2024-04-26 21:03 UTC, Kuznetsov-Artyom requested changes

2024-04-26 21:03 UTC, Kuznetsov-Artyom commented on modules/ivanchenko_a_metrics/src/metrics_app.cpp
> +}
Сколько в вашем случае будет вызвана конкатенация строк? (а вместе с ней перевыделение)
Воспользуйтесь `std::stringstream`

2024-04-26 21:03 UTC, Kuznetsov-Artyom commented on modules/ivanchenko_a_metrics/src/metrics_app.cpp
> +  } catch (std::exception& e) {
```suggestion
  } catch (const std::exception& e) {
```

2024-04-26 21:03 UTC, Kuznetsov-Artyom commented on modules/ivanchenko_a_metrics/src/metrics_app.cpp
> +  }
Воспользуйтесь одним из типой исключений стандартной библиотеки

2024-04-30 21:28 UTC, AndrewStiks commented on modules/ivanchenko_a_metrics/src/metrics_app.cpp
> +}
Поправил

2024-04-30 21:28 UTC, AndrewStiks commented on modules/ivanchenko_a_metrics/src/metrics_app.cpp
> +  } catch (std::exception& e) {
Поправил

2024-04-30 21:28 UTC, AndrewStiks commented on modules/ivanchenko_a_metrics/src/metrics_app.cpp
> +  }
Поправил

2024-04-30 23:42 UTC, Kuznetsov-Artyom approved these changes
LGTM

2024-04-30 23:42 UTC, merged