Борисов Савелий - Лабораторная работа #3
UNN-ITMM-Software/devtools-course-practice pull request #268
Opened 2024-04-21 21:30 UTC by Amazingkivas

Реализовано приложение для демонстрации работы алгоритма бинарного поиска.
Информацию о работе с приложением можно узнать, запустив его с флагом `--help`.

2024-04-21 21:45 UTC, Amazingkivas commented
@aaldebarann @BlackAngel2108

2024-04-28 08:41 UTC, aaldebarann requested changes
Нужно добавить тесты исходного модуля, например тестирование бинарного поиска на случайном наборе данных

2024-04-29 19:48 UTC, aaldebarann approved these changes

2024-04-30 10:42 UTC, Kuznetsov-Artyom approved these changes
LGTM

2024-04-30 10:43 UTC, merged