Козлов Михаил - 3 лаба
UNN-ITMM-Software/devtools-course-practice pull request #269
Opened 2024-04-22 09:43 UTC by Mishaizlesa

2024-04-27 12:55 UTC, Kuznetsov-Artyom commented
@Mishaizlesa Добавьте пожалуйста описание вашей лабораторной работы.
Также тегните двух любых студентов из [списка,](https://unn-itmm-software.github.io/devtools-course-practice) чтобы они провели код ревью.

2024-04-27 12:58 UTC, Mishaizlesa commented
@mada40  @drinkwr

2024-04-27 13:02 UTC, mada40 commented
Добавьте пожалуйста ctest на вывод справки

2024-04-27 13:57 UTC, drinkwr commented
добавь тест кучи на добавление одинаковых элементов

2024-04-27 14:21 UTC, mada40 approved these changes

2024-04-27 14:25 UTC, Mishaizlesa commented
@Kuznetsov-Artyom  это вообще как понимать, тест есть а софтина его не видит?

2024-04-27 14:40 UTC, drinkwr approved these changes

2024-04-27 14:43 UTC, Kuznetsov-Artyom commented
> @Kuznetsov-Artyom это вообще как понимать, тест есть а софтина его не видит?

Разбираемся, спасибо, что тегнули

2024-04-27 14:48 UTC, Kuznetsov-Artyom reviewed
Зачем вы сделали отдельную папку для 3 лабы? По заданию необходимо взять `готовый модуль` и доработать его

2024-04-27 14:50 UTC, Mishaizlesa commented
> Зачем вы сделали отдельную папку для 3 лабы? По заданию необходимо взять `готовый модуль` и доработать его

Понял. А что делать, если модуль еще не добавлен в основной репозиторий?

2024-04-27 15:05 UTC, Kuznetsov-Artyom commented
> > Зачем вы сделали отдельную папку для 3 лабы? По заданию необходимо взять `готовый модуль` и доработать его
> 
> Понял. А что делать, если модуль еще не добавлен в основной репозиторий?



> > Зачем вы сделали отдельную папку для 3 лабы? По заданию необходимо взять `готовый модуль` и доработать его
> 
> Понял. А что делать, если модуль еще не добавлен в основной репозиторий?



> > Зачем вы сделали отдельную папку для 3 лабы? По заданию необходимо взять `готовый модуль` и доработать его
> 
> Понял. А что делать, если модуль еще не добавлен в основной репозиторий?

Работа вашего коллеги находится ниже в пр. Она готова к мержу, но нам нужно поправить Ci с покрытием кода.
По поводу сдачи не волнуйтесь, работа отправлена в срок, поэтому просрочек не будет.

2024-04-27 15:13 UTC, Kuznetsov-Artyom commented
@Mishaizlesa модуль вмержен. Перенесите реализацию туда.

2024-04-27 20:38 UTC, Mishaizlesa commented
@Kuznetsov-Artyom та же ошибка, непонятно, что делать

2024-04-28 11:28 UTC, Kuznetsov-Artyom commented
Обновите пожалуйста ветку

2024-04-28 13:09 UTC, Kuznetsov-Artyom requested changes
Все хорошо, поправьте пару моментов

2024-04-28 13:09 UTC, Kuznetsov-Artyom commented on modules/troitskiy_a_lab2/src/Heap_app.cpp
> +  }
Используйте пожалуйста типы исключений из стандартной библиотеки.
Также поправьте обработчики.

2024-04-28 15:28 UTC, Kuznetsov-Artyom approved these changes

2024-04-28 15:28 UTC, merged