Храмов Иван. Лабораторная работа №3.
UNN-ITMM-Software/devtools-course-practice pull request #272
Opened 2024-04-22 21:14 UTC by At0mn1yIvan

Было реализовано консольное приложение для работы с алгоритмом для проверки попадания точки в треугольник.
Всю необходимую информацию можно узнать, запустив приложение с флагом --help.

### Usage:
        ./khodyrev_f_point_hits_a_triangle <x1> <y1> <x2> <y2> <x3> <y3> <point_x> <point_y>
Where:
        <x1>, <y1>, <x2>, <y2>, <x3>, <y3> are coord-s of triangle vertices.
        <point_x>, <point_y> are coord-s of point.

2024-04-23 15:50 UTC, At0mn1yIvan commented
@pozvas @Frenetz , проведите ревью, пожалуйста

2024-04-23 16:13 UTC, Frenetz commented
Добавь один тест (на свой выбор)

2024-04-23 16:15 UTC, pozvas approved these changes

2024-04-23 16:15 UTC, pozvas commented on modules/khodyrev_f_point_hits_a_triangle/src/point_hits_a_triangle_app.cpp
> +    } else if (argc != 9) {
Дай имя константе 9

2024-04-23 16:16 UTC, pozvas approved these changes

2024-04-23 16:16 UTC, pozvas commented on modules/khodyrev_f_point_hits_a_triangle/src/point_hits_a_triangle_app.cpp
> +        return false;
Дай имя константе 9

2024-04-23 18:57 UTC, At0mn1yIvan commented
@Kuznetsov-Artyom

2024-04-23 19:39 UTC, Kuznetsov-Artyom requested changes

2024-04-23 19:39 UTC, Kuznetsov-Artyom commented on modules/khodyrev_f_point_hits_a_triangle/include/point_hits_a_triangle.h
> +  Point() = default;
Зачем вам конструктор по умолчанию? Если конструктор который вы объявили (`Point::Point(double x_coord = 0, double y_coord = 0) : x(x_coord), y(y_coord) {}`) уже выполняет его функцию.

2024-04-23 20:05 UTC, At0mn1yIvan commented on modules/khodyrev_f_point_hits_a_triangle/include/point_hits_a_triangle.h
> +  Point() = default;
Без двух этих конструкторов вызов дефолтного конструктора класса приложения будет считаться удалённым.

2024-04-23 21:02 UTC, Kuznetsov-Artyom commented on modules/khodyrev_f_point_hits_a_triangle/include/point_hits_a_triangle.h
> +  Point() = default;
> Без двух этих конструкторов вызов дефолтного конструктора класса приложения будет считаться удалённым.

Зачем в таком случае вы переделали другой конструктор, который по своему поведению эквивалентен первому?

Пример:
https://rextester.com/HENT84113

Если убрать параметры по умолчанию во втором конструкторе, все будет отлично компилироваться и проблем не будет. Аналогично в случае если закомментировать конструктор по умолчанию, который вы объявили как `=default`.

В примере который я отправил, если попытаться создать экземпляр класса `Item` по умолчанию, то в момент создания ему будут удовлетворять `2 кандидата`, `1` который вы объявили как `=default`, `второй` который вы объявили самостоятельно (но т.к. там все параметры по умолчанию, то в случае если мы ничего не передаем, его поведение будет эквивалентно конструктору по умолчанию). Поэтому компилятор не сможет никаким образом определить, какой нужно произвести вызов, и будет ошибка компиляции.

P.S: Лучше указывать параметры по умолчанию в самом объявлении
https://rextester.com/SRIBC95707

2024-04-23 21:03 UTC, At0mn1yIvan commented on modules/khodyrev_f_point_hits_a_triangle/include/point_hits_a_triangle.h
> +  Point() = default;
В данном случае конструкторы классов Point и Triangle с параметрами по умолчанию не являются конструкторами по умолчанию, что и вызывает ошибку.

2024-04-23 21:11 UTC, At0mn1yIvan commented on modules/khodyrev_f_point_hits_a_triangle/include/point_hits_a_triangle.h
> +  Point() = default;
Да, я понимаю, о чём идёт речь. Я уже попробовал закомментировать конструкторы по умолчанию, дабы вызывались именно конструкторы с параметрами по умолчанию. Однако в функции main, где создаётся экземпляр класса, возникает ошибка, что класс является удалённым.

2024-04-23 21:16 UTC, At0mn1yIvan commented on modules/khodyrev_f_point_hits_a_triangle/include/point_hits_a_triangle.h
> +  Point() = default;
Попробую вынести параметры по умолчанию в хэдер, спасибо.

2024-04-23 21:24 UTC, At0mn1yIvan commented on modules/khodyrev_f_point_hits_a_triangle/include/point_hits_a_triangle.h
> +  Point() = default;
Это помогло, спасибо. Не знал, что параметры по умолчанию должны располагаться в хэдере.

2024-04-24 15:41 UTC, Kuznetsov-Artyom commented on modules/khodyrev_f_point_hits_a_triangle/include/point_hits_a_triangle.h
> +  Point() = default;
> Это помогло, спасибо. Не знал, что параметры по умолчанию должны располагаться в хэдере.

На деле вам никто не запрещает сделать параметры по умолчанию в самой реализации, только это не всегда бывает оправдано, как пример ваша ситуация.

Если рассмотреть работу компилятора, то когда вы подключаете заголовочный файл, компилятор видит только объявление класса со всеми его сигнатурами методов. И тут начинается самое интересное.
1) Например вы оставили оставили параметры по умолчанию в самой реализации, т.е. при подключении заголовочного файла, описанная сигнатура будет иметь вид `Point(double x_coord, double y_coord)`. Затем когда вы попытаетесь создать экземпляр по умолчанию, компилятор будет пытаться найти кандидата, который выполнял бы поведение конструктора по умолчанию. Но т.к. объявление конструктора с двумя параметрами не имеет параметров по умолчанию, то компилятор отбрасывает его и идет дальше. Далее вступает правило языка, если вы объявили хотя бы один из конструкторов, то конструктор по умолчанию не будет генерироваться компилятором автоматически (т.е. формально он считается удаленным). Поэтому компилятор после безуспешного поиска, выбросит ошибку компиляции, т.к. не найдет подходящего конструктора.
2) В случае если вы оставили параметры по умолчанию в объявлении конструктора самого класса, то компилятор когда будет пытаться создать объект по умолчанию увидит `Point(double x_coord = 0, double y_coord = 0)` и будет использовать его.

2024-04-24 15:45 UTC, At0mn1yIvan commented on modules/khodyrev_f_point_hits_a_triangle/include/point_hits_a_triangle.h
> +  Point() = default;
Теперь разобрался) Спасибо! Теперь в работе всё хорошо?

2024-04-24 15:49 UTC, Kuznetsov-Artyom approved these changes

2024-04-24 15:50 UTC, merged