Беляев Илья - Лабораторная№2
UNN-ITMM-Software/devtools-course-practice pull request #278
Opened 2022-04-27 20:36 UTC by 2784859334

2022-04-27 21:08 UTC, 2784859334 commented
@ITrickStar

2022-04-27 21:11 UTC, ITrickStar requested changes
Добавь комментарии к вспомогательным функциям

2022-04-27 21:33 UTC, 2784859334 commented
@gordushha

2022-04-27 21:35 UTC, ITrickStar approved these changes
Good job!

2022-04-28 10:27 UTC, gordushha approved these changes

2022-04-28 10:32 UTC, 2784859334 commented
@SHVlader

2022-04-28 10:34 UTC, merged