Musaev ilgar - лабораторная работа №1
UNN-ITMM-Software/devtools-course-practice pull request #278
Opened 2024-04-24 17:05 UTC by GitIlgar

2024-04-27 12:51 UTC, Kuznetsov-Artyom requested changes
Добавьте пожалуйста тест с проверкой деления на 0

2024-04-28 11:28 UTC, Kuznetsov-Artyom commented
@GitIlgar доработайте

2024-04-30 10:44 UTC, Kuznetsov-Artyom commented
@GitIlgar

2024-05-14 20:24 UTC, Kuznetsov-Artyom commented
@GitIlgar доработайте пожалуйста свою работу

2024-05-15 07:40 UTC, GitIlgar commented
Доработал

2024-05-15 13:39 UTC, Kuznetsov-Artyom approved these changes

2024-05-15 13:39 UTC, merged