Сафаров Нурлан. Лабораторная работа №3.
UNN-ITMM-Software/devtools-course-practice pull request #295
Opened 2024-04-26 16:58 UTC by safarov-nm

На основе модуля одного из моих коллег — было реализовано приложение для работы с алгоритмом Дейкстры для нахождения кратчайшего пути из стартовой вершины до требуемой. Флаг --help используется в командной строке для отображения справочной информации о приложении. Когда вы запускаете приложение с флагом --help, оно должно отобразить краткое описание программы, её возможностей, а также информацию о доступных аргументах командной строки и их использовании.

2024-04-27 14:49 UTC, Kuznetsov-Artyom commented
@safarov-nm Добейтесь пожалуйста полного покрытия кода.
Также тегните двух любых студентов из [списка,](https://unn-itmm-software.github.io/devtools-course-practice) чтобы они провели код ревью.

2024-04-28 10:47 UTC, Kuznetsov-Artyom commented
@safarov-nm, не обращайте внимание на последний CI. Тегните участников для дальнейшего ревью

2024-04-28 10:47 UTC, safarov-nm commented
@mada40 @Manymoera

2024-04-28 10:50 UTC, mada40 approved these changes

2024-04-28 10:53 UTC, safarov-nm commented
У CI, видимо, весеннее обострение. Помянем.

2024-04-28 11:02 UTC, Manymoera approved these changes

2024-04-28 11:25 UTC, Kuznetsov-Artyom commented
Обновите пожалуйста ветку

2024-04-28 13:15 UTC, safarov-nm commented
Итого — 26 боёв. Из них — 25 поражений и лишь 1 победа. Помянем: [тык](https://www.youtube.com/watch?v=fdvof0iRJf8&ab_channel=%D0%9A%D0%B8%D0%BD%D0%BE%D0%9A%D1%80%D0%BE%D1%82)

2024-04-28 14:31 UTC, Kuznetsov-Artyom requested changes

2024-04-28 14:31 UTC, Kuznetsov-Artyom commented on modules/makhinya_d_dijkstra_algorithm/include/dijkstra_algoritm.h
> +    //     throw std::invalid_argument("vertex must be less N!");
Зачем вы закомментировали данный фрагмент?
Также в остальных местах

2024-04-28 16:28 UTC, safarov-nm commented on modules/makhinya_d_dijkstra_algorithm/include/dijkstra_algoritm.h
> +    //     throw std::invalid_argument("vertex must be less N!");
Мы не нуждается в подобных проверках, так как корректность значений переменных, с которыми будут работать функции add_directed_edge и find_shortest_path, гарантируется функцией validate, описанная в файле dijkstra_algoritm_app.cpp.

2024-04-28 21:10 UTC, Kuznetsov-Artyom commented on modules/makhinya_d_dijkstra_algorithm/include/dijkstra_algoritm.h
> +    //     throw std::invalid_argument("vertex must be less N!");
> Мы не нуждаемся в подобных проверках, так как корректность значений переменных, с которыми будут работать функции add_directed_edge и find_shortest_path, гарантируется функцией validate, описанная в файле dijkstra_algoritm_app.cpp.

В вашем случае да, но если какой-то пользователь захочет воспользоваться данной библиотекой, без использования консольного приложения, а непосредственно `в своем коде`, то к хорошему это не приведет. Вы должны разработать консольное приложение `не ломая` структуру основного модуля. Разрешается только дорабатывать/модернизировать, но ни в коем случае `не переписывать` модуль под собственные нужды.

Пожалуйста, переделайте 🧑‍🚀

2024-04-29 15:10 UTC, safarov-nm commented on modules/makhinya_d_dijkstra_algorithm/include/dijkstra_algoritm.h
> +    //     throw std::invalid_argument("vertex must be less N!");
[Ответ](https://www.youtube.com/watch?v=mhOVZhA2Mb0&ab_channel=%D0%9D%D0%B0%D1%80%D0%B5%D0%B7%D0%BA%D0%B8%D0%B4%D0%BB%D1%8F%D0%92%D0%B0%D1%88%D0%B8%D1%85%D1%80%D0%BE%D0%BB%D0%B8%D0%BA%D0%BE%D0%B2)

2024-04-29 15:46 UTC, safarov-nm commented on modules/makhinya_d_dijkstra_algorithm/include/dijkstra_algoritm.h
> +    //     throw std::invalid_argument("vertex must be less N!");
Готово. Не паникуй ;)

2024-04-30 14:56 UTC, Kuznetsov-Artyom approved these changes

2024-04-30 14:56 UTC, merged