Гапон А.К. 381806-3. ЛР2
UNN-ITMM-Software/devtools-course-practice pull request #297
Opened 2021-05-06 16:59 UTC by Andrey0948

### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [ ] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [ ] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [ ] Get two approve from your fellow students
- [ ] Take a review from one of the administrators

2021-05-06 17:55 UTC, Andrey0948 commented
@dkurt, добрый вечер, у меня покрытие тестами не загружается на сайт
https://app.codecov.io/gh/UNN-ITMM-Software/devtools-course-practice/pulls?page=1&state=open&order=-pullid

2021-05-06 19:20 UTC, dkurt commented
@Andrey0948, ошибка компиляции:

```
[ 25%] Built target lib_polygon
/home/runner/work/devtools-course-practice/devtools-course-practice/modules/polinomial_calculation/src/Polinom.cpp: In member function ‘Polinom Polinom::operator*(const Polinom&)’:
/home/runner/work/devtools-course-practice/devtools-course-practice/modules/polinomial_calculation/src/Polinom.cpp:376:26: error: ‘*’ in boolean context, suggest ‘&&’ instead [-Werror=int-in-bool-context]
             if (t2->coef * t3->coef) {
                 ~~~~~~~~~^~~~~~~~~~
```

2021-05-06 19:23 UTC, dkurt commented on modules/polinomial_calculation/src/Polinom.cpp
> +            if (t2->coef * t3->coef) {
Compare with zero by epsilon:
```cpp
if (abs(t2->coef * t3->coef) < 1e-6)
```

2021-05-09 19:52 UTC, Andrey0948 commented
@dkurt, добрый вечер, на сайте показывает, что не покрыт сам класс, что делать в этом случае?

2021-05-12 09:34 UTC, Andrey0948 commented
@dkurt

2021-05-13 15:36 UTC, dkurt commented
@Andrey0948, достаточно сделать rebase с последней версией main ветки. Ну или дождаться, пока PR будет принят и если codecov покажет слабое покрытие - попросим улучшить.

На данный момент, нужно позвать на ревью двух однокурсников

2021-05-15 10:50 UTC, Andrey0948 commented
@ArtyomGi @Vladislavbul  Сделайте ревью, пожалуйста

2021-05-17 15:33 UTC, Andrey0948 commented
@ArtyomGi @kuznetsov-ns Сделайте ревью, пожалуйста

2021-05-18 07:23 UTC, ArtyomGi requested changes

2021-05-18 07:23 UTC, ArtyomGi commented on modules/polinomial_calculation/test/test_polonom.cpp
> +    std::vector<std::string> var;
Неиспользуемая переменная, необходимо ее убрать

2021-05-18 07:23 UTC, ArtyomGi commented on modules/polinomial_calculation/test/test_polonom.cpp
> +    std::vector<std::string> var;
Неиспользуемая переменная, необходимо ее убрать

2021-05-18 07:23 UTC, ArtyomGi commented on modules/polinomial_calculation/test/test_polonom.cpp
> +    Polinom res("9+4*y^3-7*x^5*z^3", var, 20);
Результат лучше определять в секции Arrange, чтобы в секции Act был только один полином

2021-05-18 07:23 UTC, ArtyomGi commented on modules/polinomial_calculation/test/test_polonom.cpp
> +    EXPECT_EQ(p2, p);
Ожидаемое значение лучше ставить на первое место. В данном случае ожидаемое значение p. Желательно еще переменным дать более "говорящие" названия

2021-05-18 07:23 UTC, ArtyomGi commented on modules/polinomial_calculation/test/test_polonom.cpp
> +    EXPECT_EQ(p1, p);
Аналогично комментарию выше

2021-05-18 07:23 UTC, ArtyomGi commented on modules/polinomial_calculation/test/test_polonom.cpp
> +    Polinom res("4*x*y^2", var, 20);
Определение результата лучше в Act перенести

2021-05-18 07:23 UTC, ArtyomGi commented on modules/polinomial_calculation/test/test_polonom.cpp
> +    Polinom res("-6*x^2+3*x^3+3*y*z+20*x^5*y^3*z^10-3", var, 20);
Аналогично

2021-05-18 07:23 UTC, ArtyomGi commented on modules/polinomial_calculation/test/test_polonom.cpp
> +    Polinom res("-6*x^2+3*x^3+3*y*z+20*x^5*y^3*z^10-3", var, 20);
Аналогично

2021-05-18 07:23 UTC, ArtyomGi commented on modules/polinomial_calculation/test/test_polonom.cpp
> +    Polinom res("-18*a^2-3*a^3+3*b*c-20*a^5*b^3*c^10+11", var, 20);
Аналогично

2021-05-18 07:23 UTC, ArtyomGi commented on modules/polinomial_calculation/test/test_polonom.cpp
> +    Polinom res("18*a^2+3*a^3-3*b*c+20*a^5*b^3*c^10-11", var, 20);
Аналогично

2021-05-18 07:23 UTC, ArtyomGi commented on modules/polinomial_calculation/test/test_polonom.cpp
> +    Polinom res(
Аналогично

2021-05-18 07:23 UTC, ArtyomGi commented on modules/polinomial_calculation/test/test_polonom.cpp
> +    Polinom res("36*a^2-9*b*c-12", var, 20);
Аналогично

2021-05-18 07:28 UTC, kuznetsov-ns requested changes

2021-05-20 07:56 UTC, ArtyomGi approved these changes

2021-05-20 08:20 UTC, kuznetsov-ns approved these changes

2021-05-20 11:20 UTC, Andrey0948 commented
@streltsova-yana замержи, пожалуйста

2021-05-20 12:06 UTC, streltsova-yana commented
Нет деструкторов, происходит утечка памяти

2021-05-23 10:45 UTC, Andrey0948 commented
@streltsova-yana исправил

2021-05-23 10:52 UTC, streltsova-yana requested changes

2021-05-23 10:52 UTC, streltsova-yana commented on modules/polinomial_calculation/test/test_polonom.cpp
> +    EXPECT_TRUE(p1 == p2);
Здесь и везде ниже надо поменять EXPECT на ASSERT

2021-05-23 11:08 UTC, Andrey0948 commented
@streltsova-yana исправил

2021-05-23 11:09 UTC, streltsova-yana approved these changes

2021-05-23 11:10 UTC, merged