Зайцев А.Р. 381806-3. ЛР3.
UNN-ITMM-Software/devtools-course-practice pull request #299
Opened 2021-05-07 11:29 UTC by zaitcev-andrey

### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [ ] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [x] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [x] Get two approve from your fellow students
- [x] Take a review from one of the administrators

2021-05-10 18:38 UTC, streltsova-yana commented
Для ускорения прохождения ревью вы можете пригласить сокурсников посмотреть ваш PR, упомянув их в комментариях.

[See more details](https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-3-application.md#%D1%80%D0%B5%D0%B2%D1%8C%D1%8E-%D0%BA%D0%BE%D0%B4%D0%B0)

2021-05-11 14:20 UTC, zaitcev-andrey commented
@Nikita23456 @sergey-makarichev Сделайте ревью, пожалуйста.

2021-05-13 05:52 UTC, sergey-makarichev commented on modules/batcher-mergesort/src/mergesort_application.cpp
> +        size = argc - 1;
можно было бы объединить 2 блока try catch в один

2021-05-13 08:13 UTC, Nikita23456 commented on modules/batcher-mergesort/include/mergesort_application.h
> +     std::string help(const std::string& filename) const;
Эти функции в cpp файле реализованы не по порядку. Лучше синхронизироваться, чтобы было легче ориентироваться по коду.

2021-05-13 10:53 UTC, zaitcev-andrey commented
Всё исправил

2021-05-13 11:00 UTC, Nikita23456 approved these changes
Все хорошо!

2021-05-13 11:02 UTC, sergey-makarichev approved these changes

2021-05-17 07:25 UTC, streltsova-yana requested changes

2021-05-17 07:25 UTC, streltsova-yana commented on modules/batcher-mergesort/src/mergesort_application.cpp
> +        return true;
```suggestion
    return true;
```

2021-05-17 13:01 UTC, streltsova-yana approved these changes

2021-05-17 13:02 UTC, merged