Молоткова С.С. 381806-1. ЛР3.
UNN-ITMM-Software/devtools-course-practice pull request #303
Opened 2021-05-10 10:27 UTC by SMolotkova

### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [ ] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [ ] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [ ] Get two approve from your fellow students
- [ ] Take a review from one of the administrators

2021-05-11 18:11 UTC, BelikJulia approved these changes
Все отлично

2021-05-17 07:49 UTC, streltsova-yana requested changes

2021-05-17 07:49 UTC, streltsova-yana commented on modules/params-triangle/CMakeLists.txt
> +include("CTestTests.txt")
Необходимо добавить пустую строку в конец файла

2021-05-17 07:49 UTC, streltsova-yana commented on modules/params-triangle/application/CMakeLists.txt
> +endif (UNIX)
Необходимо добавить пустую строку в конец файла

2021-05-17 08:09 UTC, SMolotkova commented on modules/params-triangle/CMakeLists.txt
> +include("CTestTests.txt")
Добавила

2021-05-17 08:09 UTC, SMolotkova commented on modules/params-triangle/application/CMakeLists.txt
> +endif (UNIX)
Добавила

2021-05-17 08:32 UTC, streltsova-yana approved these changes

2021-05-17 08:33 UTC, merged