Бодров Даниил. Лабораторная работа №3
UNN-ITMM-Software/devtools-course-practice pull request #305
Opened 2024-04-27 21:25 UTC by overinvest

2024-04-28 11:26 UTC, Kuznetsov-Artyom commented
Обновите пожалуйста ветку

2024-04-28 17:39 UTC, overinvest commented
@catk1ller007 @Manymoera

2024-04-28 18:34 UTC, Manymoera approved these changes

2024-04-28 18:35 UTC, catk1ller007 approved these changes

2024-04-28 20:55 UTC, Kuznetsov-Artyom requested changes

2024-04-28 20:55 UTC, Kuznetsov-Artyom commented on modules/kiselev_i_billinear_interpolation/src/Billinear_interpolation.cpp
> -    Color h2 = Color(0, 0, 0);  // Helper 2
Верните пожалуйста комментарии. Благодаря им, было понятно, почему автор решил назвать переменные именно так

2024-04-28 20:55 UTC, Kuznetsov-Artyom commented on modules/kiselev_i_billinear_interpolation/test/test_kiselev_i_billinear_interpolation.cpp
> +  // Проверка конструктора от вектора
Пишите комментарии на одном языке (раннее были комментарии на английском)

2024-04-28 20:58 UTC, Kuznetsov-Artyom commented
@ISK7 проверьте пожалуйста все изменения в вашем модуле, которые были внесены.

2024-04-29 09:11 UTC, ISK7 approved these changes
Изменения в большей степени направлены на улучшение читаемости кода.

2024-04-29 10:00 UTC, Kuznetsov-Artyom approved these changes

2024-04-29 10:00 UTC, merged