Напылов Е.И. 381806-2. ЛР3.
UNN-ITMM-Software/devtools-course-practice pull request #306
Opened 2021-05-11 10:15 UTC by Talesard

### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [ ] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [ ] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [ ] Get two approve from your fellow students
- [ ] Take a review from one of the administrators

2021-05-11 13:09 UTC, gitlng requested changes

2021-05-11 13:09 UTC, gitlng commented on modules/queue/src/queue.cpp
> +    unsigned int size = 0;  // it was 1
Убери комментарий, в истории комитов и так видно, что было

2021-05-11 13:09 UTC, gitlng commented on modules/queue/test/test_queue_app.cpp
> +    const int argc = 1;
Тут и везде дальше заменить `argc` на `argv.size()`

2021-05-11 13:09 UTC, gitlng commented on modules/queue/test/test_queue_app.cpp
> +    std::string correct = "invalid arg";
Тут и везде лучше `const std::string` для результата для стабильности и корректности

2021-05-11 13:53 UTC, katsum25 commented
Добавить тест, который проверяет добавление после удаления и тест, который проверяет удаление всех элементов

2021-05-12 12:32 UTC, katsum25 approved these changes

2021-05-13 15:01 UTC, gitlng approved these changes
Одобряю

2021-05-17 06:31 UTC, OnlyDeniko approved these changes

2021-05-17 06:32 UTC, merged