Рустамов А.З. 381806-1. ЛР3.
UNN-ITMM-Software/devtools-course-practice pull request #307
Opened 2021-05-11 17:41 UTC by RustamovAzer

### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [ ] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [ ] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [ ] Get two approve from your fellow students
- [ ] Take a review from one of the administrators

2021-05-11 19:53 UTC, dkurt commented on modules/polygon/include/polygon_area_calculator.h
> +// Copyright 2021 Rustamov Azer
Please use C++-like header extension: `.hpp`. There is no technical issue here but just more convenient.

2021-05-11 20:10 UTC, RustamovAzer commented on modules/polygon/include/polygon_area_calculator.h
> +// Copyright 2021 Rustamov Azer
Should I also change the extension of `polygon.h`?

2021-05-12 11:06 UTC, BFDestroyeer requested changes

2021-05-12 11:06 UTC, BFDestroyeer commented on modules/polygon/src/polygon_area_calculator.cpp
> +    if (retcode)
Корректнее всё же сравнивать с nullptr

2021-05-12 16:07 UTC, RustamovAzer commented on modules/polygon/src/polygon_area_calculator.cpp
> +    if (retcode)
Исправил

2021-05-12 16:08 UTC, RustamovAzer commented on modules/polygon/src/polygon_area_calculator.cpp
> +        " Coordinates of points...\nExample: " + filename +
Исправил

2021-05-12 16:08 UTC, RustamovAzer commented on modules/polygon/src/polygon_area_calculator.cpp
> +#include <sstream>
Исправил

2021-05-12 16:10 UTC, BFDestroyeer commented on modules/polygon/src/polygon_area_calculator.cpp
> +        " Coordinates of points...\nExample: " + filename +
Лучше ещё использовать не "+" а "\" как в этом [примере](https://github.com/UNN-ITMM-Software/devtools-course-practice/pull/309#discussion_r631119350)

2021-05-12 16:47 UTC, RustamovAzer commented on modules/polygon/src/polygon_area_calculator.cpp
> +        " Coordinates of points...\nExample: " + filename +
Исправил

2021-05-12 16:47 UTC, BFDestroyeer approved these changes

2021-05-12 17:33 UTC, Makarov-AA requested changes

2021-05-12 17:33 UTC, Makarov-AA commented on modules/polygon/include/polygon_area_calculator.hpp
> +    PolygonAreaCalculator() = default;;
Думаю, нужно убрать вторую точку с запятой

2021-05-12 17:33 UTC, Makarov-AA commented on modules/polygon/src/polygon_area_calculator.cpp
> +    numbers.reserve(argc - 1);
Можно убрать reserve, просто вызвав конструктор vector(argc - 1)

2021-05-12 18:01 UTC, RustamovAzer commented on modules/polygon/include/polygon_area_calculator.hpp
> +    PolygonAreaCalculator() = default;;
Исправил

2021-05-12 18:05 UTC, Makarov-AA approved these changes

2021-05-17 08:31 UTC, streltsova-yana requested changes

2021-05-17 08:31 UTC, streltsova-yana commented on modules/polygon/src/polygon_area_calculator.cpp
> +    }
```suggestion
    for (auto i = 0; i < argc - 2; i += 2) {
        points[i / 2].first = numbers[i];
        points[i / 2].second = numbers[i + 1];
    }
```

2021-05-17 09:15 UTC, streltsova-yana approved these changes

2021-05-17 09:16 UTC, merged