Пронькин Д.А. 381806-1. ЛР3.
UNN-ITMM-Software/devtools-course-practice pull request #308
Opened 2021-05-12 10:40 UTC by r01and3

### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [ ] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [ ] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [ ] Get two approve from your fellow students
- [ ] Take a review from one of the administrators

2021-05-12 10:45 UTC, r01and3 commented
@vla5924 @Alexandr-Solovev Сделайте ревью, пожалуйста

2021-05-12 16:47 UTC, vla5924 requested changes

2021-05-12 16:47 UTC, vla5924 commented on modules/grosfeld-cipher/include/grosfeld_cipher_app.h
> +    } Arguments;
Какова причина объявления структуры в стиле C? Если причин нет, то нужно переписать.
```suggestion
    struct Arguments {
        std::string sourceString;
        int key;
        char operation;
    };
```

2021-05-12 16:47 UTC, vla5924 commented on modules/grosfeld-cipher/src/grosfeld_cipher_app.cpp
> +          "<key> - cipher key, <operation> is one of 'decrypt' or 'encrypt'\n";
Лучше использовать `\`, чтобы компилятор склеивал строки в один литерал. Типа того:
```suggestion
    message_ = std::string(message) +
        "This is a Gronsfeld cipher application.\n\n" \
        "Please provide arguments in the following format:\n\n" \
        " $" + appname + " <sourceString> <key> <operation>\n\n" \
        "Where <sourceString> - string to decrypt or encrypt, " \
        "<key> - cipher key, <operation> is one of 'decrypt' or 'encrypt'\n";
```

2021-05-12 16:47 UTC, vla5924 commented on modules/grosfeld-cipher/src/grosfeld_cipher_app.cpp
> +        throw std::string("Wrong string format!");
Лучше выбрасывать `std::runtime_error` из `<stdexcept>`, а не строки

2021-05-12 18:32 UTC, Alexandr-Solovev requested changes

2021-05-12 18:32 UTC, Alexandr-Solovev commented on modules/grosfeld-cipher/src/grosfeld_cipher_app.cpp
> +#include <sstream>
Для красоты можно отсортировать в алфавитном порядке.

2021-05-12 18:32 UTC, Alexandr-Solovev commented on modules/grosfeld-cipher/src/grosfeld_cipher_app.cpp
> +    if (sourceString.find_first_of("1234567890") != std::string::npos) {
здесь, вероятно, вместо find_first_of("123..."), лучше использовать find_first_of("abc..."), так ты учетшь все символы не входящие в алфавит

2021-05-12 21:15 UTC, vla5924 approved these changes

2021-05-13 15:17 UTC, Alexandr-Solovev approved these changes

2021-05-17 08:46 UTC, streltsova-yana approved these changes

2021-05-17 08:47 UTC, merged