Зореев М.В. 381806-1. ЛР3.
UNN-ITMM-Software/devtools-course-practice pull request #309
Opened 2021-05-12 10:50 UTC by BFDestroyeer

### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [ ] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [ ] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [ ] Get two approve from your fellow students
- [ ] Take a review from one of the administrators

2021-05-12 12:27 UTC, BFDestroyeer commented
@dkurt Никак не могу добиться полного покрытия тестами, строки указанные в отчёте тестах задействованы. При этом я не нахожу отчёта по этим файлам до моих изменений, чтобы найти причину такого эффекта.

2021-05-12 14:57 UTC, vla5924 requested changes

2021-05-12 14:57 UTC, vla5924 commented on modules/binary_search/include/binary_search.h
>  #include <string>
Minor: заголовки можно отсортировать по алфавиту

2021-05-12 14:57 UTC, vla5924 commented on modules/binary_search/include/binary_search.h
> +    int Search(T key, std::vector<T> array, int left, int right) {
```suggestion
    int Search(const T& key, const std::vector<T>& array, int left, int right) {
```

2021-05-12 14:57 UTC, vla5924 commented on modules/binary_search/include/binary_search.h
>          bool flag = false;
`flag` - не лучшее название для переменной типа `bool`. Может быть, можно назвать ее как-то более конкретно?

2021-05-12 14:57 UTC, vla5924 commented on modules/binary_search/include/search_engine.h
> +#include <string>
Minor: заголовки можно отсортировать по алфавиту

2021-05-12 14:57 UTC, vla5924 commented on modules/binary_search/src/search_engine.cpp
> +                       int* retcode) const {
```suggestion
std::string SearchEngine::operator()(int argc, const char* argv[],
                                     int* retcode) const {
```

2021-05-12 14:57 UTC, vla5924 commented on modules/binary_search/src/search_engine.cpp
> +    "Will search \"5\" element in \"1 2 4 5\" row";
```suggestion
    return "Usage: " + filename + " DESIRED VALUES...\n" \
           "Example: " + filename + " 5 3 2 4 5\n" \
           "Will search \"5\" element in \"1 2 4 5\" row";
```

2021-05-12 16:15 UTC, vla5924 approved these changes

2021-05-12 16:18 UTC, taktaev-artyom requested changes

2021-05-12 16:18 UTC, taktaev-artyom commented on modules/binary_search/test/test_binary_search.cpp
> +                     std::runtime_error);
```suggestion
    ASSERT_THROW(BinarySearch::Search<int>(3, array, 2, -3),
                 std::runtime_error);
```

2021-05-12 16:18 UTC, taktaev-artyom commented on modules/binary_search/test/test_binary_search.cpp
> +                     std::runtime_error);
```suggestion
    ASSERT_THROW(BinarySearch::Search<int>(3, array, 2, 27),
                 std::runtime_error);
```

2021-05-12 16:18 UTC, taktaev-artyom commented on modules/binary_search/test/test_binary_search.cpp
> +            std::runtime_error);
```suggestion
    ASSERT_THROW(BinarySearch::Search<int>(3, array, -7, 8),
                 std::runtime_error);
```

2021-05-12 16:18 UTC, taktaev-artyom commented on modules/binary_search/test/test_binary_search.cpp
> +                     std::runtime_error);
```suggestion
    ASSERT_THROW(BinarySearch::Search<int>(3, array, 27, 8),
                 std::runtime_error);
```

2021-05-12 16:18 UTC, taktaev-artyom commented on modules/binary_search/test/test_binary_search.cpp
> +                     std::runtime_error);
```suggestion
    ASSERT_THROW(BinarySearch::Search<int>(3, array, 8, 3),
                 std::runtime_error);
```

2021-05-12 16:18 UTC, taktaev-artyom commented on modules/binary_search/test/test_binary_search.cpp
>  TEST(Binary_Search_Test, UnSortedSearch) {
```suggestion
TEST(Binary_Search_Test, UnsortedSearch) {
```

2021-05-12 16:22 UTC, taktaev-artyom approved these changes
клас

2021-05-20 05:48 UTC, BFDestroyeer commented
@streltsova-yana Ну так и что по итогу? Pull request висит уже больше недели, а "администраторы" ничего не говорят. Если есть причины чтобы не делать merge, **которые я могу исправить**, тогда надо написать что конкретно нужно и я это исправлю.

2021-05-20 06:49 UTC, streltsova-yana commented
В приложении можно добавить поддержку бинарного поиска элемента в массива типа double

2021-05-20 06:59 UTC, streltsova-yana commented
Для удовлетворения codecov можно сделать следующее:

`git checkout main`
`git remote add upstream https://github.com/UNN-ITMM-Software/devtools-course-practice`
`git pull upstream main`
`git rebase main my_branch_name`
`git push origin -f my_branch_name`

2021-05-20 08:09 UTC, BFDestroyeer commented
@streltsova-yana 
> 
> 
> В приложении можно добавить поддержку бинарного поиска элемента в массивe типа double

Сделано

> 
> 
> Для удовлетворения codecov можно сделать следующее:
> 
> `git checkout main`
> `git remote add upstream https://github.com/UNN-ITMM-Software/devtools-course-practice`
> `git pull upstream main`
> `git rebase main my_branch_name`
> `git push origin -f my_branch_name`

Сделано, но как видно покрытие тестом `IncorrectRightOutOfRange` и ему подобными строки 16 файла `modules/binary_search/include/binary_search.h `, на которую указывает отчёт, продолжает игнорироваться.

2021-05-20 09:38 UTC, streltsova-yana approved these changes

2021-05-20 09:39 UTC, merged