Прокофьева Е.А. 381806-2. ЛР3.
UNN-ITMM-Software/devtools-course-practice pull request #311
Opened 2021-05-13 13:49 UTC by prokofeval

### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [ ] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [ ] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [ ] Get two approve from your fellow students
- [ ] Take a review from one of the administrators

2021-05-13 14:11 UTC, prokofeval commented
@diligentConcernist , @dasha-ludina посмотрите, пожалуйста.

2021-05-13 15:07 UTC, diligentConcernist requested changes
У меня только одно замечание

2021-05-13 15:07 UTC, diligentConcernist commented on modules/stack/src/stack_app.cpp
> +#include <string>
Заголовки нужно поменять местами:

```suggestion
#include "include/stack_app.h"

#include <cstring>
#include <sstream>
#include <stdexcept>
#include <string>

#include "include/stack.h"
```

2021-05-13 15:13 UTC, dasha-ludina commented on modules/stack/src/stack_app.cpp
> +    std::ostringstream stream;
У меня тоже нет особых замечаний
Единственное, можно добавить пустую строку для более наглядного представления

2021-05-13 15:43 UTC, diligentConcernist approved these changes
👍🏻

2021-05-13 15:55 UTC, dasha-ludina approved these changes
Все хорошо)

2021-05-17 06:28 UTC, OnlyDeniko approved these changes

2021-05-17 06:28 UTC, merged