Колесников Г.Р. 381803-2. ЛР3
UNN-ITMM-Software/devtools-course-practice pull request #313
Opened 2021-05-14 12:32 UTC by BrandonRTL

### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [ ] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [ ] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [ ] Get two approve from your fellow students
- [ ] Take a review from one of the administrators

2021-05-14 15:16 UTC, andrewkin77 requested changes

2021-05-14 15:16 UTC, andrewkin77 commented on modules/prime_numbers/CTestTests.txt
> +    NAME ${prefix}_test_test
Поменяй название теста на что-нибудь более конкретное

2021-05-14 20:14 UTC, MADZEROPIE approved these changes
Какие-то пресные пулл реквесты у третьей лабы.
_**My job here is done**_

2021-05-14 20:14 UTC, MADZEROPIE commented on modules/prime_numbers/src/prime_numbers_application.cpp
> +
Ну что, господа, отделяем пустой строкой? Хаха.

2021-05-14 20:14 UTC, MADZEROPIE commented on modules/prime_numbers/src/prime_numbers_application.cpp
> +        }
Сразу вернуть `false`

2021-05-15 08:06 UTC, andrewkin77 approved these changes

2021-05-17 06:41 UTC, WerWebWer approved these changes

2021-05-17 06:42 UTC, merged