Кузнецов Н.С. 381806-3. ЛР3
UNN-ITMM-Software/devtools-course-practice pull request #317
Opened 2021-05-16 10:49 UTC by kuznetsov-ns

### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [ ] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [ ] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [ ] Get two approve from your fellow students
- [ ] Take a review from one of the administrators

2021-05-16 10:53 UTC, kuznetsov-ns commented
@ArtyomGi @Vladislavbul проверьте пожалуйста

2021-05-20 08:10 UTC, ArtyomGi commented on modules/bit_array/src/bit_array_application.cpp
> +      for (size_t i = 0; i < memMask.size(); i++) {
Инкремент в циклах необходимо делать в префиксной форме. Здесь это не так заметно, но, к примеру, при использовании итераторов возможно существенное замедление при возвращении значения

2021-05-20 08:13 UTC, ArtyomGi commented on modules/bit_array/src/bit_array_application.cpp
> +int BitArrayApplication::checkPositiveNumber(const char* argv) const {
Лучше переименовать функцию. С "check" ассоциации, что она должна возвращать логическое значение (число положительное или нет). Здесь же возвращается само число

2021-05-20 11:04 UTC, Vladislavbul approved these changes

2021-05-20 11:26 UTC, ArtyomGi approved these changes

2021-05-20 11:30 UTC, streltsova-yana requested changes

2021-05-20 11:30 UTC, streltsova-yana commented on modules/bit_array/CMakeLists.txt
> +include("CTestTests.txt")
Необходимо добавить пустую строку в конец файла

2021-05-20 11:44 UTC, streltsova-yana approved these changes

2021-05-20 11:45 UTC, merged