Щекотилова Ю. А. 381806-3. ЛР3
UNN-ITMM-Software/devtools-course-practice pull request #318
Opened 2021-05-16 10:52 UTC by shekotilova-yuliya

### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [ ] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [ ] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [ ] Get two approve from your fellow students
- [ ] Take a review from one of the administrators

2021-05-16 15:05 UTC, shekotilova-yuliya commented
@dasha-ludina @sashatyurmina посмотрите пожалуйста

2021-05-16 20:07 UTC, dasha-ludina commented on modules/algorithm-huffmana/include/algorithm_huffmana_app.h
> +  void help(const char* appname, const char* message = "");
Сначала лучше объявить поля private, затем public

```suggestion
 private:
  std::string message_;
  std::string convert(std::vector<std::string> _part_of_result);
  bool validateNumberOfArguments(int argc, const char** argv);
  void help(const char* appname, const char* message = "");
  
 public:
  AlgorithmHuffmanaApp();
  std::string operator()(int argc, const char** argv);
```

2021-05-16 20:07 UTC, dasha-ludina commented on modules/algorithm-huffmana/src/algorithm_huffmana_app.cpp
> +#include "include/algorithm_huffmana.h"
Необходимо добавить пустую строку

2021-05-17 18:15 UTC, sashatyurmina reviewed
Все хорошо. Замечаний нет.

2021-05-17 18:15 UTC, sashatyurmina approved these changes

2021-05-17 18:56 UTC, dasha-ludina approved these changes
Все отлично!)

2021-05-17 21:06 UTC, streltsova-yana requested changes

2021-05-17 21:06 UTC, streltsova-yana commented on modules/algorithm-huffmana/application/CMakeLists.txt
> +endif (UNIX)
Необходимо добавить пустую строку в конец файла

2021-05-17 21:07 UTC, streltsova-yana commented
Также можно протестировать в приложении создание гистограммы

2021-05-20 10:17 UTC, streltsova-yana approved these changes

2021-05-20 10:17 UTC, merged