Соловьев А.Ю. 381806-1. ЛР3
UNN-ITMM-Software/devtools-course-practice pull request #320
Opened 2021-05-16 13:10 UTC by Alexandr-Solovev

### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [ ] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [ ] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [ ] Get two approve from your fellow students
- [ ] Take a review from one of the administrators

2021-05-16 13:12 UTC, Alexandr-Solovev commented
@r01and3 @RustamovAzer можете поревьювить, пожалуйста

2021-05-16 13:26 UTC, RustamovAzer requested changes

2021-05-16 13:26 UTC, RustamovAzer commented on modules/bulls-n-cows/CTestTests.txt
> +    LABELS "${MODULE}")
Стоит добавить тест на корректную работу с проверкой на равенство полученного результата с ожидаемым

2021-05-16 13:26 UTC, RustamovAzer commented on modules/bulls-n-cows/src/BullsAndCowsApp.cpp
> +#include "include/BullsAndCows.h"
Желательно поменять порядок инклюдов: сначала <> в алфавитном порядке, потом ""

2021-05-16 13:26 UTC, RustamovAzer commented on modules/bulls-n-cows/src/BullsAndCowsApp.cpp
> +}
Для лучшей читабельности "Example..." стоит переместить на новую строку

2021-05-16 13:51 UTC, r01and3 commented on modules/bulls-n-cows/src/BullsAndCowsApp.cpp
> +        return "invalid argument.";
Можно еще дополнительно возвращать, сколько должно быть введено аргументов.

2021-05-16 13:51 UTC, r01and3 commented on modules/bulls-n-cows/src/BullsAndCowsApp.cpp
> +        return "invalid argument.";
Здесь также лучше дополнительно возвращать диапазон аргумента count

2021-05-16 13:51 UTC, r01and3 commented on modules/bulls-n-cows/src/BullsAndCowsApp.cpp
> +        str = "Bulls:" + std::to_string(result.first) + " Cows:" + std::to_string(result.second);
Здесь еще можно выводить правильный ответ для полноты картины.

2021-05-17 14:07 UTC, r01and3 approved these changes

2021-05-17 14:08 UTC, RustamovAzer approved these changes

2021-05-17 14:08 UTC, Alexandr-Solovev commented
@WerWebWer можешь посмотреть, пожалуйста

2021-05-17 16:52 UTC, WerWebWer approved these changes

2021-05-17 16:53 UTC, merged