Лебедев А.В. 381803-2. ЛР3
UNN-ITMM-Software/devtools-course-practice pull request #325
Opened 2021-05-16 15:16 UTC by andrewkin77

### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [ ] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [ ] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [ ] Get two approve from your fellow students
- [ ] Take a review from one of the administrators

2021-05-16 15:23 UTC, BrandonRTL requested changes

2021-05-16 15:23 UTC, BrandonRTL commented on modules/triangle-point/src/triangle_application.cpp
> +        "$ " + appname + " <val_1> <val_2> ... <val_8> \n\n";
Как-то здесь не особо понятно, какой аргумент за что отвечает

2021-05-16 15:34 UTC, BrandonRTL requested changes

2021-05-16 15:34 UTC, BrandonRTL commented on modules/triangle-point/src/triangle_application.cpp
> +        "$ " + appname + " <val_1> <val_2> ... <val_8> \n\n"
Я имел в виду не это. Пользователь вводит координаты четырех точек: три задают треугольник, а одна проверяется на нахождение внутри треугольника. По функции getHelp не особо понятно, какая из точек какая.

2021-05-16 15:37 UTC, alxndrvna commented
Можно добавить тесты на ввод отрицательных чисел

2021-05-16 15:47 UTC, BrandonRTL approved these changes

2021-05-16 16:02 UTC, alxndrvna approved these changes

2021-05-16 19:49 UTC, MADZEROPIE approved these changes
Смотрите, я тоже умею одобрять!
_**My job here is done**_

2021-05-17 06:35 UTC, WerWebWer approved these changes

2021-05-17 06:36 UTC, merged