Тактаев А.А. 381806-1. ЛР3
UNN-ITMM-Software/devtools-course-practice pull request #326
Opened 2021-05-16 15:26 UTC by taktaev-artyom

### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [ ] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [ ] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [ ] Get two approve from your fellow students
- [ ] Take a review from one of the administrators

2021-05-16 18:05 UTC, BFDestroyeer requested changes

2021-05-16 18:05 UTC, BFDestroyeer commented on modules/dheap/src/dheap_app.cpp
> +#include <stdexcept>
Стоит отсортировать по алфавиту

2021-05-16 18:05 UTC, BFDestroyeer commented on modules/dheap/src/dheap_app.cpp
> +        if (retcode)
Лучше явно сравнивать с nullptr

2021-05-16 18:05 UTC, BFDestroyeer commented on modules/dheap/src/dheap_app.cpp
> +        if (argc <= 1)
Рекомендуется не использовать операции вида `<= N` `>=N`. Вместо них лучше использовать `< N+1`

2021-05-16 18:12 UTC, BFDestroyeer approved these changes

2021-05-16 18:47 UTC, vla5924 requested changes

2021-05-16 18:47 UTC, vla5924 commented on modules/dheap/include/dheap_app.h
> +namespace DHeap {
Излишнее пространство имен, не совсем понятно зачем оно нужно

2021-05-16 18:47 UTC, vla5924 commented on modules/dheap/include/dheap_app.h
> +class DHeapApp {
Нужно либо назвать класс `DheapApp`, либо переименовать класс `Dheap` в `DHeap`.

2021-05-16 21:34 UTC, vla5924 approved these changes

2021-05-17 09:00 UTC, streltsova-yana approved these changes

2021-05-17 09:00 UTC, merged