Макаров А.А. 381806-1. ЛР3
UNN-ITMM-Software/devtools-course-practice pull request #327
Opened 2021-05-16 15:33 UTC by Makarov-AA

### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [ ] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [ ] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [ ] Get two approve from your fellow students
- [ ] Take a review from one of the administrators

2021-05-16 16:35 UTC, RustamovAzer requested changes

2021-05-16 16:35 UTC, RustamovAzer commented on modules/combination_generator/src/generator_app.cpp
> +#include <sstream>
Пользовательские инклюды("") должны идти после стандартных(<>)

2021-05-16 16:35 UTC, RustamovAzer commented on modules/combination_generator/src/generator_app.cpp
> +          "Where all arguments are integer numbers\n";
Вместо 
    "строка" +
    "строка" 
стоит использовать 
    "строка" \\
    "строка"

2021-05-16 16:35 UTC, RustamovAzer commented on modules/combination_generator/src/generator_app.cpp
> +    int *a = new int[m];
Память выделяется, но не освобождается

2021-05-16 16:35 UTC, RustamovAzer commented on modules/combination_generator/test/test.cpp
> +    int* a = new int[m];
Аналогично

2021-05-16 16:35 UTC, RustamovAzer commented on modules/combination_generator/test/test.cpp
> +    int* a = new int[m];
Аналогично

2021-05-16 16:35 UTC, RustamovAzer commented on modules/combination_generator/test/test.cpp
> +    int* a = new int[m];
Аналогично

2021-05-16 17:55 UTC, Makarov-AA commented on modules/combination_generator/src/generator_app.cpp
> +    int *a = new int[m];
Исправил везде

2021-05-16 18:55 UTC, Makarov-AA commented on modules/combination_generator/src/generator_app.cpp
> +          "Where all arguments are integer numbers\n";
Сделал

2021-05-16 18:57 UTC, RustamovAzer approved these changes

2021-05-17 06:03 UTC, SMolotkova approved these changes

2021-05-17 06:05 UTC, Makarov-AA commented
@streltsova-yana, проверьте, пожалуйста

2021-05-17 06:32 UTC, WerWebWer approved these changes

2021-05-17 06:32 UTC, merged