Гущин А.А. 381806-3. ЛР3.
UNN-ITMM-Software/devtools-course-practice pull request #330
Opened 2021-05-16 19:59 UTC by ArtyomGi

### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [ ] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [ ] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [ ] Get two approve from your fellow students
- [ ] Take a review from one of the administrators

2021-05-16 20:39 UTC, ArtyomGi commented
@kuznetsov-ns @Andrey0948 Сделайте ревью, пожалуйста

2021-05-18 07:18 UTC, Andrey0948 requested changes

2021-05-18 07:18 UTC, Andrey0948 commented on modules/Kruskal_algorithm/src/Kruskal_algorithm_app.cpp
> +    std::stringstream stream;
Лучше использовать std::ostringstream, т.к. используется только операция вывода

2021-05-18 07:18 UTC, Andrey0948 commented on modules/Kruskal_algorithm/src/Kruskal_algorithm_app.cpp
> +void KruskalAlgorithm::help(const char* appname, const char* message) {
Вместо const char* лучше использовать const std::string&

2021-05-20 09:16 UTC, Andrey0948 approved these changes

2021-05-23 10:16 UTC, kuznetsov-ns approved these changes

2021-05-23 10:19 UTC, ArtyomGi commented
@WerWebWer Замержи, пожалуйста

2021-05-23 11:44 UTC, WerWebWer approved these changes

2021-05-23 11:44 UTC, merged

2021-05-24 06:07 UTC, ArtyomGi commented
@WerWebWer Отметь в таблице, пожалуйста. В ней до сих пор под сомнением стоит 3 задача