Иванченко Алексей - Лабораторная работа 3
UNN-ITMM-Software/devtools-course-practice pull request #333
Opened 2024-05-01 11:14 UTC by aaldebarann

Реализовано приложение для демонстрации возможностей двусвязного списка. 
Приложение позволяет выводить список в командную строку, добавлять новые элементы в начало или в конец списка, развернуть список. Полную информацию о работе с приложением можно узнать, запустив его с флагом `--help`.

2024-05-01 13:23 UTC, aaldebarann commented
@MaximFLUNN @Amazingkivas

2024-05-01 15:16 UTC, Amazingkivas requested changes
Необходимо дополнить тесты исходного модуля

2024-05-01 15:16 UTC, Amazingkivas commented on modules/filatov_m_double_linked_list/src/DoubleLinkedListApp.cpp
> +            break;
Нужно добавить тест для данного участка кода

2024-05-02 00:43 UTC, MaximFLUNN commented
#### Добавь команды для удаления и добавления элементов по индексу

**template:**

--insert data index
--erase index

**example:**

--insert ! 0
--erase 0

2024-05-02 19:00 UTC, MaximFLUNN commented
LGTM

2024-05-03 10:19 UTC, Kuznetsov-Artyom approved these changes

2024-05-03 10:20 UTC, Kuznetsov-Artyom commented on modules/filatov_m_double_linked_list/src/DoubleLinkedListApp.cpp
> +            break;
@aaldebarann устраните замечание

2024-05-03 10:24 UTC, aaldebarann commented on modules/filatov_m_double_linked_list/src/DoubleLinkedListApp.cpp
> +            break;
> @aaldebarann устраните замечание

Замечание устранено. Добавлен тест
`${prefix}_unrecognized_Option`

2024-05-03 11:01 UTC, Kuznetsov-Artyom commented on modules/filatov_m_double_linked_list/src/DoubleLinkedListApp.cpp
> +            break;
> > @aaldebarann устраните замечание
> 
> Замечание устранено. Добавлен тест `${prefix}_unrecognized_Option`

Увидел, спасибо

2024-05-03 11:01 UTC, Kuznetsov-Artyom commented
> LGTM

Апрувните работу

2024-05-03 11:40 UTC, Amazingkivas approved these changes

2024-05-03 12:57 UTC, merged