Пестреев Д.С. 381806-2. ЛР3
UNN-ITMM-Software/devtools-course-practice pull request #335
Opened 2021-05-17 08:01 UTC by katsum25

### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [ ] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [ ] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [ ] Get two approve from your fellow students
- [ ] Take a review from one of the administrators

2021-05-17 12:29 UTC, katsum25 commented
@gitlng, @Talesard проверьте, пожалуйста

2021-05-17 13:07 UTC, Talesard commented
Нужно протестировать случаи, когда:
- один из элементов - знак минус
- один из элементов - строка

Поставить два последних теста после теста can_locate_arrayСontainsDouble, чтобы тесты, проверяющие вводимый формат, были в одном месте.

В сообщении help лучше словами объяснить, что последний аргумент - ключ, который ищем.

2021-05-17 14:40 UTC, Talesard approved these changes
GJ 👍

2021-05-19 10:49 UTC, gitlng requested changes

2021-05-19 10:49 UTC, gitlng commented on modules/interpolation-search/src/searchApplication.cpp
> +
Лишний пробел

2021-05-19 10:49 UTC, gitlng commented on modules/interpolation-search/src/searchApplication.cpp
> +            } else {  //  e = element
Здесь и дальше убери комментарии

2021-05-19 10:49 UTC, gitlng commented on modules/interpolation-search/src/searchApplication.cpp
> +    std::string result = "";
лучше сразу присвоить `result` значение `std::to_string(res_InterpSearch)`

2021-05-19 10:49 UTC, gitlng commented on modules/interpolation-search/src/searchApplication.cpp
> +    return result;
здесь и выше раздели пустыми строками разные структурные части (объявление, алгоритм, return)

2021-05-20 05:05 UTC, gitlng approved these changes
Одобряю изменения

2021-05-20 07:14 UTC, streltsova-yana requested changes

2021-05-20 07:14 UTC, streltsova-yana commented on modules/interpolation-search/CMakeLists.txt
> +include("CTestTests.txt")
Необходимо добавить пустую строку в конец файла

2021-05-20 07:14 UTC, streltsova-yana commented on modules/interpolation-search/application/CMakeLists.txt
> +endif (UNIX)
Необходимо добавить пустую строку в конец файла

2021-05-20 07:14 UTC, streltsova-yana commented on modules/interpolation-search/src/CMakeLists.txt
> +set(LIBRARY_DEPS "${LIBRARY_DEPS};${target}" PARENT_SCOPE)
Необходимо добавить пустую строку в конец файла

2021-05-20 07:14 UTC, streltsova-yana commented on modules/interpolation-search/test/CMakeLists.txt
> +    LABELS "${MODULE}")
Необходимо добавить пустую строку в конец файла

2021-05-20 07:16 UTC, streltsova-yana commented
Также необходимо проверить является ли входной массив отсортированным

2021-05-20 09:31 UTC, streltsova-yana approved these changes

2021-05-20 09:33 UTC, merged