Карагодин Андрей - Лабораторная работа №3
UNN-ITMM-Software/devtools-course-practice pull request #335
Opened 2024-05-01 14:03 UTC by MineShadow7

## Лабораторная работа №3 
* Добавлено приложение для библиотеки Figure_Surface.
* Добавлены CTests для приложения.
* Удалены лишние нервные клетки.

Please review, @LeakMachine, @ZhatkinVyacheslav

2024-05-01 17:08 UTC, LeakMachine approved these changes
Проверено.

2024-05-01 17:25 UTC, MineShadow7 commented
@Kuznetsov-Artyom :page_with_curl:  :paintbrush:

2024-05-01 17:25 UTC, ZhatkinVyacheslav approved these changes

2024-05-02 01:16 UTC, Kuznetsov-Artyom requested changes

2024-05-02 01:16 UTC, Kuznetsov-Artyom commented on .run/BuildAll.run.xml
В лабораторной работе не должно быть лишних файлов

2024-05-02 05:00 UTC, MineShadow7 commented on .run/BuildAll.run.xml
Исправлено в последних коммитах

2024-05-02 10:57 UTC, Kuznetsov-Artyom approved these changes

2024-05-02 10:57 UTC, merged