Алибеков М.Р. 381806-1. ЛР3
UNN-ITMM-Software/devtools-course-practice pull request #341
Opened 2021-05-17 12:52 UTC by AlibekovMurad5202

### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [ ] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [ ] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [ ] Get two approve from your fellow students
- [ ] Take a review from one of the administrators

2021-05-17 13:49 UTC, Alexandr-Solovev requested changes

2021-05-17 13:49 UTC, Alexandr-Solovev commented on modules/dijkstras-algorithm/application/main.cpp
> +#include <stdio.h>
Лучше расставить в алфавитном порядке

2021-05-17 13:49 UTC, Alexandr-Solovev commented on modules/dijkstras-algorithm/src/dijkstras_algorithm_app.cpp
> +#include <sstream>
лучше расставить в алфавитном порядке

2021-05-17 14:00 UTC, RustamovAzer requested changes

2021-05-17 14:00 UTC, RustamovAzer commented on modules/dijkstras-algorithm/src/dijkstras_algorithm_app.cpp
> +          "Where all arguments are double-precision numbers or word 'inf'.\n";
Вместо
"строка" +
"строка"
стоит использовать
"строка" \\
"строка"

2021-05-17 14:27 UTC, RustamovAzer approved these changes

2021-05-17 14:59 UTC, Alexandr-Solovev approved these changes

2021-05-17 18:32 UTC, AlibekovMurad5202 commented
@streltsova-yana, посмотри, пожалуйста

2021-05-17 21:31 UTC, streltsova-yana requested changes

2021-05-17 21:31 UTC, streltsova-yana commented on modules/dijkstras-algorithm/include/dijkstras_algorithm_app.h
> +    } Arguments;
```suggestion
    struct Arguments {
        int N;
        int source_vertex;
        std::vector<double> graph;
    };
```

2021-05-18 06:47 UTC, AlibekovMurad5202 commented on modules/dijkstras-algorithm/include/dijkstras_algorithm_app.h
> +    } Arguments;
@streltsova-yana
Исправлено)

2021-05-18 07:40 UTC, streltsova-yana approved these changes

2021-05-18 07:40 UTC, merged