Лудина Д.А. 381806-3. ЛР3
UNN-ITMM-Software/devtools-course-practice pull request #343
Opened 2021-05-17 16:52 UTC by dasha-ludina

### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [ ] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [ ] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [ ] Get two approve from your fellow students
- [ ] Take a review from one of the administrators

2021-05-17 18:48 UTC, dasha-ludina commented
@shekotilova-yuliya @sashatyurmina посмотрите пожалуйста

2021-05-17 18:54 UTC, shekotilova-yuliya commented on modules/mortgage/application/mortgage_app.cpp
> +#include "include/mortgage_app.h"
необходима пустая строка

2021-05-17 18:54 UTC, shekotilova-yuliya commented on modules/mortgage/src/mortgage_app.cpp
> +#include "include/mortgage_app.h"
необходима пустая строка

2021-05-17 18:54 UTC, shekotilova-yuliya commented on modules/mortgage/test/test_mortgage_app.cpp
> +#include "include/mortgage_app.h"
необходима пустая строка

2021-05-17 19:13 UTC, shekotilova-yuliya approved these changes

2021-05-17 19:15 UTC, sashatyurmina approved these changes

2021-05-20 08:17 UTC, streltsova-yana requested changes

2021-05-20 08:17 UTC, streltsova-yana commented on modules/mortgage/test/test_mortgage_app.cpp
> +    EXPECT_TRUE(RE::PartialMatch(output_, RE(expected)));
```suggestion
    ASSERT_TRUE(RE::PartialMatch(output_, RE(expected)));
```

2021-05-20 11:09 UTC, streltsova-yana approved these changes

2021-05-20 11:09 UTC, merged