Гапон А.К. 381806-3. ЛР3
UNN-ITMM-Software/devtools-course-practice pull request #347
Opened 2021-05-17 19:17 UTC by Andrey0948

### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [ ] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [ ] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [ ] Get two approve from your fellow students
- [ ] Take a review from one of the administrators

2021-05-19 07:46 UTC, Andrey0948 commented
@ArtyomGi @kuznetsov-ns сделайте ревью, пожалуйста

2021-05-20 08:05 UTC, ArtyomGi requested changes

2021-05-20 08:05 UTC, ArtyomGi commented on modules/conv-and-calc/src/NumConvCalcApplication.cpp
> +        std::string ENG = "-,ABCDEFGHIJKLMNOPQRSTUVWXYZ" \
Аналогично комментарию выше, \ можно не ставить

2021-05-20 08:05 UTC, ArtyomGi commented on modules/conv-and-calc/src/NumConvCalcApplication.cpp
> +        for (size_t i = 0; i < str[1].size(); i++) {
Тяжело читать, желательно добавить пустых строк перед циклами, чтобы визуально их отделить

2021-05-20 08:05 UTC, ArtyomGi commented on modules/conv-and-calc/src/NumConvCalcApplication.cpp
> +        std::string ENG = "-,ABCDEFGHIJKLMNOPQRSTUVWXYZ" \
Аналогично

2021-05-20 11:20 UTC, kuznetsov-ns requested changes

2021-05-20 11:20 UTC, kuznetsov-ns commented on modules/conv-and-calc/src/NumConvCalcApplication.cpp
> +#include <stdexcept>
Можно отсортировать по алфавиту.

2021-05-20 11:20 UTC, kuznetsov-ns commented on modules/conv-and-calc/src/NumConvCalcApplication.cpp
> +        for (size_t i = 0; i < str[1].size(); i++) {
Циклы лучше разделять пустой строчкой

2021-05-20 12:08 UTC, kuznetsov-ns approved these changes

2021-05-20 12:28 UTC, ArtyomGi approved these changes

2021-05-20 12:30 UTC, Andrey0948 commented
@streltsova-yana замержи, пожалуйста

2021-05-21 15:22 UTC, streltsova-yana requested changes

2021-05-21 15:22 UTC, streltsova-yana commented on modules/conv-and-calc/application/main.cpp
> +// Copyright 2021 Bulychev Vladislav
Copyright 2021 Bulychev Vladislav ?

2021-05-21 15:22 UTC, streltsova-yana commented on modules/conv-and-calc/src/NumConvCalcApplication.cpp
> +                }
```suggestion
                if (str[1].find_first_not_of("01") != std::string::npos)
                    throw std::runtime_error("ERROR: " +
                        str[1] + " is invalid argument\n\n");
```

2021-05-21 15:22 UTC, streltsova-yana commented on modules/conv-and-calc/src/NumConvCalcApplication.cpp
> +                }
```suggestion
                if (str[1].find_first_not_of("01234567") != std::string::npos)
                    throw std::runtime_error("ERROR: " +
                        str[1] + " is invalid argument\n\n");
```

2021-05-21 15:22 UTC, streltsova-yana commented on modules/conv-and-calc/src/NumConvCalcApplication.cpp
> +                }
```suggestion
                if (str[1].find_first_not_of("0123456789ABCDEF") != std::string::npos)
                    throw std::runtime_error("ERROR: " +
                        str[1] + " is invalid argument\n\n");
```

2021-05-21 16:13 UTC, Andrey0948 commented
@streltsova-yana исправил

2021-05-21 16:18 UTC, merged