Podyachikh Mikhail. Lab 3
UNN-ITMM-Software/devtools-course-practice pull request #350
Opened 2024-05-02 00:14 UTC by MuUJa

## Add application for `deposit calculator`

2024-05-02 00:18 UTC, MuUJa commented
@Instmois
@MorgachevStepan
Please review PR

2024-05-02 18:37 UTC, Instmois commented
добрый код

2024-05-02 18:37 UTC, Instmois approved these changes

2024-05-02 18:42 UTC, MorgachevStepan approved these changes

2024-05-02 18:51 UTC, MuUJa commented
@Kuznetsov-Artyom, норм?

2024-05-03 10:34 UTC, Kuznetsov-Artyom requested changes

2024-05-03 10:34 UTC, Kuznetsov-Artyom commented on modules/moiseev_n_deposit_calculator/application/main.cpp
> +#include "../include/deposit_calculator_app.h"
```suggestion
#include "include/deposit_calculator_app.h"
```

2024-05-03 10:34 UTC, Kuznetsov-Artyom commented on modules/moiseev_n_deposit_calculator/src/deposit_calculator_app.cpp
> +#include "../include/deposit_calculator.h"
```suggestion
#include "include/deposit_calculator_app.h"
#include "include/deposit_calculator.h"
```

2024-05-03 10:34 UTC, Kuznetsov-Artyom commented on modules/moiseev_n_deposit_calculator/src/deposit_calculator_app.cpp
> +      "and <n_months> is integer number.\n";
Чтобы избежать лишнего перевыделения памяти в результате конкатенаций строк, воспользуйтесь `stringstream`

2024-05-03 10:34 UTC, Kuznetsov-Artyom commented on modules/moiseev_n_deposit_calculator/src/deposit_calculator_app.cpp
> +    throw std::string("Wrong arguments format!");
Воспользуйтесь лучше каким-нибудь типом исключений из стандартной библиотеки

2024-05-03 21:49 UTC, MuUJa commented
Fixed

2024-05-04 01:16 UTC, Kuznetsov-Artyom approved these changes
LGTM

2024-05-04 01:16 UTC, merged