Филатов Максим - Лабораторная работа 3
UNN-ITMM-Software/devtools-course-practice pull request #352
Opened 2024-05-02 00:58 UTC by MaximFLUNN

Реализовано приложение для демонстрации возможностей двухсторонней очереди ``deque``.
Приложение позволяет выводить список в командную строку, добавлять новые элементы в начало или в конец списка, развернуть список. Полную информацию о работе с приложением можно узнать, запустив его с флагом ``--help``.

2024-05-02 00:59 UTC, MaximFLUNN commented
@AleksandrKutarin @ekistrimova

2024-05-03 10:50 UTC, Kuznetsov-Artyom requested changes

2024-05-03 10:50 UTC, Kuznetsov-Artyom commented on modules/kutarin_a_lab2/include/deque.h
> +    back_ = nullptr;
Чем вас не устроил вариант с `pop_front`?

2024-05-03 10:50 UTC, Kuznetsov-Artyom commented on modules/kutarin_a_lab2/include/dequeApp.h
> +    void push_front(std::vector<std::string>& output, std::string elem);
Добавьте пожалуйста также операции с удалением

2024-05-03 10:50 UTC, Kuznetsov-Artyom commented on modules/kutarin_a_lab2/include/dequeApp.h
> +        deque.push_back("up");
Это тут для чего?

2024-05-04 14:36 UTC, MaximFLUNN commented on modules/kutarin_a_lab2/include/dequeApp.h
> +        deque.push_back("up");
Стандартная инициализация deque приложения в виде пасхалки для `понимания`

2024-05-04 14:37 UTC, MaximFLUNN commented on modules/kutarin_a_lab2/include/dequeApp.h
> +    void push_front(std::vector<std::string>& output, std::string elem);
pop_back и pop_front были добавлены вместе с их покрытием

2024-05-04 14:47 UTC, MaximFLUNN commented on modules/kutarin_a_lab2/include/deque.h
> +    back_ = nullptr;
Я понимаю, что вы предпочитаете использование метода `pop_front` для удаления узлов. Однако, я выбрал другой подход, который, как мне кажется, более эффективен в данном контексте.

Например по причине того, что `pop_front` включает в себя различные проверки и ограничения а так же возвращает значение узла.

Поэтому вместо использования `pop_front`, я решил явно удалять каждый узел. Этот подход позволяет избежать потенциально ненужных операций, которые выполняются в `pop_front`, таких как возвращение значения узла или бросание исключения, когда дека пуста. Это приведёт к улучшению производительности в дистанции, особенно для больших деков.

Я ценю вашу обратную связь и всегда открыт для обсуждения, однако, я был бы признателен, если бы вы более **внимательно** **изучили** мой код перед тем, как делать предложения по его изменению.

2024-05-04 15:16 UTC, Kuznetsov-Artyom commented on modules/kutarin_a_lab2/include/dequeApp.h
> +        deque.push_back("up");
Какого понимания? Этот код не несет никакой пользы в данной ситуации

2024-05-04 15:30 UTC, Kuznetsov-Artyom commented on modules/kutarin_a_lab2/include/deque.h
> +    back_ = nullptr;
Хороший развернутый ответ), хватило бы фразы "нет лишних перепроверок и прочей мишуры".
1) Оберните данный фрагмент в метод `clear`, чтобы избежать дублирования кода в других методах.
2) Перепишите также перемещающий оператор присваивания применив новый метод `clear`

2024-05-05 20:57 UTC, MaximFLUNN commented on modules/kutarin_a_lab2/include/deque.h
> +    back_ = nullptr;
Спасибо, я знаю, что ответ хороший и развёрнутый)

Его бы не пришлось писать, если немного уделить времени и посмотреть всё-таки код, прежде чем просить исправлять чужой код) (хотелось бы такого же внимания к pr\`ам без проверок и к pr\`ам друзей ☺️)

В правилах указано давать такие правки если интерфейс не удобен для использования, а он вполне удобен, просто решил сделать хорошее дело и что видел, то поправил)

В любом случае задание выполнено)

2024-05-05 21:09 UTC, MaximFLUNN commented on modules/kutarin_a_lab2/include/dequeApp.h
> +        deque.push_back("up");
Во-первых, данный код имеет пользу в тестировании, инициализируя конкретные значения. Это дополнительно подтверждает работоспособность функциональности некоторой части кода.

Во-вторых, как я уже сказал ранее, данные слова являются пасхалкой. И слова “для понимания” относились именно к тому, что это пасхалка.

В-третьих, этот код является, как минимум, примером использования класса `Deque` с конкретными значениями и типом `std::string`. Это является наглядной демонстрацией использования кода для пользователя.

Так что, утверждение “он не несёт никакой пользы в данной ситуации” считаю категорически неверным. Да, без него, возможно, кардинально ничего бы не изменилось - это факт. Однако утверждать, что он не несёт пользы, я бы не стал.

2024-05-05 21:47 UTC, Kuznetsov-Artyom commented on modules/kutarin_a_lab2/include/dequeApp.h
> +        deque.push_back("up");
Данный код не нужен, доработайте

2024-05-05 21:55 UTC, Kuznetsov-Artyom commented on modules/kutarin_a_lab2/include/deque.h
> +    back_ = nullptr;
@MaximFLUNN не увидел исправленной версии перемещающего оператора присваивания, доработайте

2024-05-05 23:26 UTC, MaximFLUNN commented on modules/kutarin_a_lab2/include/deque.h
> +    back_ = nullptr;
@Kuznetsov-Artyom - доработано.

2024-05-05 23:35 UTC, MaximFLUNN commented on modules/kutarin_a_lab2/include/dequeApp.h
> +        deque.push_back("up");
“Данный код не нужен, доработайте” - пожалуйста, это ваше субъективное мнение. Я, как автор, вижу смысл в этом коде и вправе оставлять в нем то, что считаю нужным.

Что касается требований лабораторной работы:

- общие требования выполнены;
- все тесты запускаются и корректно проходят;
- классы грамотно спроектированы;
- код хорошо оформлен.

То, что вы считаете не нужным, напрямую не относится ни к одному из пунктов. Причиной тому является то, что данный код находится в инициализации класса, на которой завязаны тесты. Там может быть всё, что угодно, в том числе любые строки, которые в дальнейшем будут влиять на тесты, что они успешно и делают.

Какой будет эта стандартная инициализация, в праве решать в том числе автор. 

**Считаю данный спор оконченным, мерджите пулл реквест)**

В противном случае, мне придётся предпринять меры, которые коснутся, вероятно, не только вас, но и тех, кому вы приняли работы без проверок)

2024-05-06 12:34 UTC, dkurt commented on modules/kutarin_a_lab2/include/dequeApp.h
> +        deque.push_back("up");
Инициализацию как часть библиотеки проводить не стоит. Пользователь ожидает пустой контейнер.

Насколько понимаю, вы хотели чтобы в каждом тесте уже была проинициализирована очередь и не дублировался код? В таком случае, посмотрите в сторону метода `setUp` как в этом модуле: https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/e31997f06071f2db325ba1ce6e7a2741a7fc1d9a/modules/karagodin_a_objvolumes/test/test_objvolumes.cpp#L8

2024-05-06 17:47 UTC, AleksandrKutarin approved these changes

2024-05-06 18:27 UTC, ekistrimova approved these changes

2024-05-07 18:10 UTC, FirewallGR approved these changes

2024-05-07 18:11 UTC, merged