Кочетов Николай. Лабораторная работа №3.
UNN-ITMM-Software/devtools-course-practice pull request #354
Opened 2024-05-02 01:22 UTC by esthete014

2024-05-03 10:53 UTC, Kuznetsov-Artyom commented
Доработайте

2024-05-07 18:14 UTC, GERONlMO approved these changes

2024-05-07 18:15 UTC, FirewallGR commented
Approve от Geronimo не считается

2024-05-09 20:32 UTC, esthete014 commented
@GERONlMO @AleksandrKutarin

2024-05-09 20:32 UTC, GERONlMO approved these changes

2024-05-09 20:34 UTC, AleksandrKutarin approved these changes

2024-05-09 21:11 UTC, Kuznetsov-Artyom requested changes
В целом все хорошо, поправьте пару моментов

2024-05-09 21:11 UTC, Kuznetsov-Artyom commented on modules/sokolova_d_queue/src/queue_app.cpp
> +}
Сколько раз будет выполнена конкатенация строк для 10 элементов? А вместе с ним лишнее выделение памяти для создания временных объектов. В случае если таких элементов очень много, то будет значительная просадка в производительности

2024-05-09 21:11 UTC, Kuznetsov-Artyom commented on modules/sokolova_d_queue/src/queue_app.cpp
> +}
Аналогично в других местах программы

2024-05-09 21:11 UTC, Kuznetsov-Artyom commented on modules/sokolova_d_queue/src/queue_app.cpp
> +    }
Если пользователь вдруг захочет добавить много элементов в очередь, то метод `push_back` будет постоянно выполнять перепаковку, после того как израсходует запас емкости. Воспользуйтесь одним методом из `std::vector` который позволит выделить запас емкости с нужным размером

2024-05-10 02:26 UTC, esthete014 commented on modules/sokolova_d_queue/src/queue_app.cpp
> +}
для реализации без дублирования памяти надо будет добавлять в queue.h метод последовательного обращения к памяти, а это нарушает идею очереди, что ты хочешь?

2024-05-10 03:01 UTC, esthete014 commented on modules/sokolova_d_queue/src/queue_app.cpp
> +    }
> Если пользователь вдруг захочет добавить много элементов в очередь, то метод `push_back` будет постоянно выполнять перепаковку, после того как израсходует запас емкости. Воспользуйтесь одним методом из `std::vector` который позволит выделить запас емкости с нужным размером

сделано

2024-05-10 12:09 UTC, Kuznetsov-Artyom commented on modules/sokolova_d_queue/src/queue_app.cpp
> +}
> для реализации без дублирования памяти надо будет добавлять в queue.h метод последовательного обращения к памяти, а это нарушает идею очереди, что ты хочешь?

Посмотрите на работу другого студента в качестве примера https://github.com/UNN-ITMM-Software/devtools-course-practice/pull/339

2024-05-10 15:15 UTC, esthete014 commented on modules/sokolova_d_queue/src/queue_app.cpp
> +}
> > для реализации без дублирования памяти надо будет добавлять в queue.h метод последовательного обращения к памяти, а это нарушает идею очереди, что ты хочешь?
> 
> Посмотрите на работу другого студента в качестве примера #339

сделал

2024-05-10 16:13 UTC, Kuznetsov-Artyom approved these changes
Спасибо за внесенные изменения

2024-05-10 16:13 UTC, merged