Гурылев Н.С. 381806-3. ЛР3
UNN-ITMM-Software/devtools-course-practice pull request #354
Opened 2021-05-18 09:48 UTC by gurylev-nikita

### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [ ] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [ ] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [ ] Get two approve from your fellow students
- [ ] Take a review from one of the administrators

2021-05-18 11:37 UTC, gurylev-nikita commented
@Vladislavbul @zaitcev-andrey сделайте ревью, пожалуйста.

2021-05-18 11:38 UTC, Vladislavbul commented on modules/Pqueue/include/Pqueue-application.h
> +    std::string operator()(int argc, const char** argv);
Следует сначала писать public, а потом private.

2021-05-18 11:46 UTC, zaitcev-andrey commented on modules/Pqueue/include/Pqueue-application.h
> +#ifndef MODULES_PQUEUE_INCLUDE_PQUEUE_APPLICATION_H_
Лучше раздели пустой строкой

2021-05-18 11:46 UTC, zaitcev-andrey commented on modules/Pqueue/include/Pqueue-application.h
> +#include "include/Pqueue.h"
Нужно отделить пустой строкой подключение заголовочного файла

2021-05-18 11:46 UTC, zaitcev-andrey commented on modules/Pqueue/src/Pqueue-application.cpp
> +#include "include/Pqueue.h"
Аналогично

2021-05-18 11:46 UTC, zaitcev-andrey commented on modules/Pqueue/src/Pqueue-application.cpp
> +        "pop - extract from queue\n";
Вместо + для соединения строк лучше используй \ как символ окончания строки

2021-05-18 12:20 UTC, Vladislavbul approved these changes

2021-05-18 12:20 UTC, zaitcev-andrey approved these changes

2021-05-20 10:54 UTC, streltsova-yana requested changes

2021-05-20 10:54 UTC, streltsova-yana commented on modules/Pqueue/src/Pqueue-application.cpp
> +        int v = std::atoi(*(argv + 2));
Лучше использовать std::stoi, т.к. при передаче некорректной строки, например 'abc', std::atoi вернёт 0, что можно рассматривать как корректный ввод, в то время как std::stoi выбросит исключение

2021-05-20 13:29 UTC, gurylev-nikita commented on modules/Pqueue/src/Pqueue-application.cpp
> +        int v = std::atoi(*(argv + 2));
Corrected.

2021-05-21 14:17 UTC, streltsova-yana approved these changes

2021-05-21 14:17 UTC, merged