Юрин С. И. 381806-2 ЛР3
UNN-ITMM-Software/devtools-course-practice pull request #365
Opened 2021-05-29 19:40 UTC by stasyurin

### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [x] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [x] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [ ] Get two approve from your fellow students
- [ ] Take a review from one of the administrators

2021-05-29 19:54 UTC, stasyurin commented
@r01and3, @diligentConcernist, проверьте пожалуйста)

2021-05-29 20:26 UTC, diligentConcernist reviewed
В целом все хорошо, но предлагаю внести следующие правки:

2021-05-29 20:26 UTC, diligentConcernist commented on modules/wave-algorithm/src/application.cpp
> +        stream << path[path.size() - 1].first <<
Можно заменить на

```suggestion
        stream << path.back().first << 
```
Со следующей строкой аналогично

2021-05-29 20:26 UTC, diligentConcernist commented on modules/wave-algorithm/src/application.cpp
> +    while (std::getline(is, s, ','))
Непонятно, где заканчивается цикл. Добавь, пожалуйста, скобки для повышения читаемости

2021-05-29 20:29 UTC, r01and3 requested changes

2021-05-29 20:29 UTC, r01and3 commented on modules/wave-algorithm/src/application.cpp
> +        throw std::string("Wrong number format!");
Лучше выбрасывать std::runtime_error из <stdexcept>, а не строки

2021-05-29 20:29 UTC, r01and3 commented on modules/wave-algorithm/src/application.cpp
> +        throw std::string("Wrong number format!");
Лучше выбрасывать std::runtime_error из , а не строки

2021-05-29 20:29 UTC, r01and3 commented on modules/wave-algorithm/src/application.cpp
> +            throw std::string("Wrong map format!");
Аналогично

2021-05-30 06:27 UTC, r01and3 approved these changes

2021-05-30 06:31 UTC, diligentConcernist approved these changes

2021-05-30 07:08 UTC, stasyurin commented
@OnlyDeniko, проверь пожалуйста

2021-05-30 16:44 UTC, OnlyDeniko approved these changes

2021-05-30 16:44 UTC, merged