Савчук Антон. Лабораторная работа 3
UNN-ITMM-Software/devtools-course-practice pull request #366
Opened 2024-05-05 19:50 UTC by savchukPR2

Реализовал приложение для Fibonacci Heap!

2024-05-05 19:59 UTC, savchukPR2 commented
@vadimbelan @overinvest прошу посмотрите 🙏

2024-05-05 20:05 UTC, overinvest commented
> @vadimbelan @overinvest прошу посмотрите 🙏

Чтобы все тесты прошли, нужно доработать ( добавить или изменить функции ) основной модуль. При добавлении каких-то новых функций, сделать к ним тесты

Пока что могу дать идею исправить комментарии в моем модуле, чтобы не было такого, что одни комментарии на русском, другие комментарии на английском языке

2024-05-06 17:46 UTC, vadimbelan approved these changes
а мне все нравится 🥰

2024-05-06 21:11 UTC, overinvest commented
> а мне все нравится 🥰

Пока у него все чеки не пройдут. Лабу все равно не замержат, а чтобы чеки прошли, нужно внести изменения в основной модуль. Иначе никак

2024-05-06 21:12 UTC, overinvest commented
Тут к сожалению, мой голос не решит ничего, пока он не добавит изменения

2024-05-06 21:13 UTC, overinvest approved these changes

2024-05-06 21:13 UTC, overinvest commented
Приложение сделано хорошо

2024-05-07 03:31 UTC, vadimbelan commented
> > а мне все нравится 🥰
> 
> Пока у него все чеки не пройдут. Лабу все равно не замержат, а чтобы чеки прошли, нужно внести изменения в основной модуль. Иначе никак

codecov/project не проходит во всех последних работах

2024-05-07 19:49 UTC, FirewallGR requested changes

2024-05-07 19:49 UTC, FirewallGR commented on modules/bodrov_daniil_fibonacci_heap/src/console.cpp
> +}
Используйте, пожалуйста, команды для выбора опции, а не числа
Пример: --insert; --extract и т.д

2024-05-14 20:23 UTC, Kuznetsov-Artyom commented on modules/bodrov_daniil_fibonacci_heap/src/console.cpp
> +}
@savchukPR2 доработайте пожалуйста свою работу

2024-05-28 12:11 UTC, Kuznetsov-Artyom commented
@savchukPR2

2024-05-29 20:22 UTC, savchukPR2 commented
@Kuznetsov-Artyom

2024-05-30 02:45 UTC, Kuznetsov-Artyom approved these changes

2024-05-30 02:46 UTC, merged