Федотов Кирилл. Лабораторная работа №3
UNN-ITMM-Software/devtools-course-practice pull request #374
Opened 2024-05-25 17:56 UTC by KirFedotov

2024-05-27 06:40 UTC, Kuznetsov-Artyom requested changes
Все хорошо, поправьте пару моментов

2024-05-27 06:40 UTC, Kuznetsov-Artyom commented on modules/bakhtiarov_a_priority_queue/src/priority_queue_app.cpp
> +            Help(argv[0], "Invalid arguments.");
В данном случае лучше вывести конкретное сообщение об ошибке.
```suggestion
            Help(argv[0], e.what());
```

2024-05-27 06:40 UTC, Kuznetsov-Artyom commented on modules/bakhtiarov_a_priority_queue/src/priority_queue_app.cpp
> +                }
```suggestion
                } catch(const std::exception& e) {
                    result << e.what() << '\n';
                }
```

2024-05-31 10:57 UTC, KirFedotov commented
@Kuznetsov-Artyom

2024-05-31 17:38 UTC, Kuznetsov-Artyom approved these changes
LGTM

2024-05-31 17:39 UTC, merged