Коновалов Игорь - Лабораторная работа #3
UNN-ITMM-Software/devtools-course-practice pull request #383
Opened 2024-06-04 18:55 UTC by IgorKonovalovAleks

Консольное приложение для вычисления количества компонент связности в графе.

2024-06-04 19:06 UTC, IgorKonovalovAleks commented
@Kuznetsov-Artyom Проверьте пожалуйста

2024-06-05 19:04 UTC, Kuznetsov-Artyom requested changes
Все хорошо, поправьте несколько моментов

2024-06-05 19:04 UTC, Kuznetsov-Artyom commented on modules/graph_comp_shem_a/src/graph_components_app.cpp
> +      str << std::to_string(graph_components_numbers(n, v));
Для чего вам приведение возвращаемого значения из функции `graph_components_numbers` к строке?

2024-06-05 19:04 UTC, Kuznetsov-Artyom commented on modules/graph_comp_shem_a/include/graph_components_app.h
> +#include <string>
Лишние заголовочные файлы лучше перенести в .cpp файл. В самом заголовочном файле нужно оставить только те, которые требуются для описания сигнатур методов или других функций, объявленных вне класса

2024-06-08 16:22 UTC, IgorKonovalovAleks commented
@Kuznetsov-Artyom

2024-06-08 18:18 UTC, Kuznetsov-Artyom approved these changes
Спасибо за внесенные изменения

2024-06-08 18:18 UTC, merged