Шемякина - Лабораторная работа #3
UNN-ITMM-Software/devtools-course-practice pull request #384
Opened 2024-06-04 19:07 UTC by alesyacurtis

Разработка консольного приложения для подсчета числа компонент связности графа

2024-06-04 20:16 UTC, alesyacurtis commented
@Kuznetsov-Artyom

2024-06-05 18:56 UTC, Kuznetsov-Artyom requested changes
Все хорошо, поправьте один момент

2024-06-05 18:56 UTC, Kuznetsov-Artyom commented on modules/graph_comp_shem_a/src/graph_components_app.cpp
> +      str << std::to_string(graph_components_numbers(n, v));
В данном случае не обязательно приводить возвращаемое значение из функции `graph_components_numbers` к строке. `sstream` поддерживает все фундаментальные типы. (также будут поддерживаться пользовательские типы данных, для которых перегружен оператор вывода `operator<<`)

2024-06-13 06:57 UTC, Kuznetsov-Artyom commented
@alesyacurtis у вас пропал весь код :_)

2024-06-13 13:10 UTC, alesyacurtis commented
@Kuznetsov-Artyom вроде вернула....Случился конфликт веток и напуталось что-то. Момент с ненужным приведением функции к строке поправила.

2024-06-13 13:17 UTC, Kuznetsov-Artyom commented
> @Kuznetsov-Artyom вроде вернула....Случился конфликт веток и напуталось что-то. Момент с ненужным приведением функции к строке поправила.

Дело в том, что над этим модулем уже работал другой человек. Создайте новую папку для 3 лр и перенесите туда свою реализацию

2024-07-08 19:05 UTC, closed without merging