Кокин Иван Лабараторная №3
UNN-ITMM-Software/devtools-course-practice pull request #387
Opened 2024-06-07 21:12 UTC by ThreeToads

Приложение для второй лабораторной

2024-06-07 21:21 UTC, ThreeToads commented
@Kuznetsov-Artyom

2024-06-08 07:51 UTC, Kuznetsov-Artyom requested changes

2024-06-08 07:51 UTC, Kuznetsov-Artyom commented on modules/kokin_sort_station_org/application/application.cpp
> +#include "../include/Console_app.h"
Никогда не указывайте полный путь до файла. Это связано с тем, что если папка с заголовочными файлами мигрирует в другую директорию, то сборка проекта закончился с ошибкой. К тому же нужно будет изменять каждый файл, который подключал в любые другие файлы из той директории.

2024-06-08 07:51 UTC, Kuznetsov-Artyom commented on modules/kokin_sort_station_org/application/application.cpp
> +#include "../include/Console_app.h"
Аналогично во всех других файлах, где вы указывали полный путь

2024-06-08 07:51 UTC, Kuznetsov-Artyom commented on modules/kokin_sort_station_org/include/sort_station.h
> +};
Почему бы не сделать реализацию в одном классе?

2024-06-08 07:51 UTC, Kuznetsov-Artyom commented on modules/kokin_sort_station_org/src/Console_app.cpp
> +}
Почему бы не сделать возвращаемый тип данного метода `std::string`? Это было бы удобно в случае если в дальнейшем был бы предусмотрен графический интерфейс приложения

2024-06-08 07:51 UTC, Kuznetsov-Artyom commented on modules/kokin_sort_station_org/include/sort_station.h
> +     double evaluateFunction(const std::string& expression) override;
Оценка функции? Функция оценки? Почему бы не дать более информативное название данному методу? Например если заменить `evaluate` на `calculate`, то у разработчика использующего ваш api не возникло бы вопросов

2024-06-08 07:51 UTC, Kuznetsov-Artyom commented on modules/kokin_sort_station_org/include/sort_station.h
> +#include <stdexcept>
Лишние заголовочные файлы лучше перенести в .сpp файл. Нужно лишь оставить те, которые нужны для описания сигнатур

2024-06-09 18:13 UTC, ThreeToads commented on modules/kokin_sort_station_org/application/application.cpp
> +#include "../include/Console_app.h"
Где это возможно я исправил, в остальных случаях не позволяет cpplint

2024-06-09 18:13 UTC, ThreeToads commented on modules/kokin_sort_station_org/include/sort_station.h
> +};
Для удобства использования методов класса в других файлах(тестах и тд) реализовано так

2024-06-09 18:14 UTC, ThreeToads commented on modules/kokin_sort_station_org/src/Console_app.cpp
> +}
Исправил

2024-06-09 18:14 UTC, ThreeToads commented on modules/kokin_sort_station_org/include/sort_station.h
> +     double evaluateFunction(const std::string& expression) override;
Поправил

2024-06-09 18:14 UTC, ThreeToads commented on modules/kokin_sort_station_org/include/sort_station.h
> +#include <stdexcept>
Изменил

2024-06-09 18:34 UTC, Kuznetsov-Artyom commented on modules/kokin_sort_station_org/include/sort_station.h
> +     double evaluateFunction(const std::string& expression) override;
Expression как раз был кстати, чутка не то поправили

2024-06-09 18:36 UTC, Kuznetsov-Artyom commented on modules/kokin_sort_station_org/src/Console_app.cpp
> +}
Имелось ввиду нечто следующее
```cpp
std::string ConsoleApp::evaluateExpression(const std::string& expression) {
    return sortStation.evaluateFunction(expression);
}

2024-06-09 18:39 UTC, Kuznetsov-Artyom commented on modules/kokin_sort_station_org/application/application.cpp
> +#include "../include/Console_app.h"
Отправьте пожалуйста ссылку на action, где это не сработало

2024-06-09 18:41 UTC, Kuznetsov-Artyom commented on modules/kokin_sort_station_org/include/sort_station.h
> +};
Вам же не нужна абстракция, поэтому нет необходимости делать раздельные классы. Разве не так?

2024-06-09 18:42 UTC, Kuznetsov-Artyom commented on modules/kokin_sort_station_org/include/sort_station.h
> +     double evaluateFunction(const std::string& expression) override;
имелось ввиду получить нечто следующее: `calculateExpression`

2024-06-09 19:55 UTC, ThreeToads commented on modules/kokin_sort_station_org/include/sort_station.h
> +};
https://github.com/ThreeToads/devtools-course-practice/actions/runs/9438457465/job/25995456275
CodeCheck

2024-06-09 20:48 UTC, ThreeToads commented on modules/kokin_sort_station_org/application/application.cpp
> +#include "../include/Console_app.h"
https://github.com/ThreeToads/devtools-course-practice/actions/runs/9438457465/job/25995456275
CodeCheck

2024-06-09 21:24 UTC, ThreeToads commented on modules/kokin_sort_station_org/include/sort_station.h
> +};
Переделал в 1 класс

2024-06-09 21:24 UTC, ThreeToads commented on modules/kokin_sort_station_org/src/Console_app.cpp
> +}
Поменял

2024-06-09 21:25 UTC, ThreeToads commented on modules/kokin_sort_station_org/include/sort_station.h
> +     double evaluateFunction(const std::string& expression) override;
Сделал

2024-06-09 21:25 UTC, ThreeToads commented
@Kuznetsov-Artyom

2024-06-10 16:40 UTC, Kuznetsov-Artyom approved these changes
LGTM

2024-06-10 16:40 UTC, merged