Смирнов Павел. Лабораторная работа №2.
UNN-ITMM-Software/devtools-course-practice pull request #399
Opened 2024-10-09 09:14 UTC by PavelLSmirnov

2024-10-11 14:09 UTC, Kuznetsov-Artyom commented
Доработайте, чтоб проходили проверки

2024-10-11 14:12 UTC, Kuznetsov-Artyom requested changes

2024-10-11 14:12 UTC, Kuznetsov-Artyom commented on modules/smirnov_pavel_number_to_words/src/number_to_words.cpp
> +  std::string result;
Если вы формируете строку, конткатенацией других строк, то лучше использовать `std::stringstream`

2024-10-12 14:23 UTC, PavelLSmirnov commented on modules/smirnov_pavel_number_to_words/src/number_to_words.cpp
> +  std::string result;
поправил

2024-10-12 14:26 UTC, PavelLSmirnov commented
> Доработайте, чтоб проходили проверки
запускал локально тесты проходят, в ci падают actions на чужой работе

2024-10-14 05:50 UTC, Kuznetsov-Artyom approved these changes

2024-10-19 17:48 UTC, Kuznetsov-Artyom commented
Please rebase

2024-10-20 14:15 UTC, merged