Козел Светлана - Лабораторная работа #2
UNN-ITMM-Software/devtools-course-practice pull request #422
Opened 2022-05-25 17:48 UTC by Svetlana531

2022-05-25 18:23 UTC, Svetlana531 commented
@Leyzeld @kirill123kk

2022-05-25 18:28 UTC, Leyzeld requested changes

2022-05-25 18:42 UTC, kirill123kk requested changes

2022-05-25 18:42 UTC, kirill123kk commented on modules/kozel_s_k_combinations/src/combinations.cpp
> +    std::vector<int> v(1, 0);
поменяй v на _tmp_vec

2022-05-25 18:49 UTC, Leyzeld approved these changes
Good

2022-05-25 19:21 UTC, kirill123kk approved these changes
все в порядке

2022-05-25 20:46 UTC, Svetlana531 commented
@SHVlader

2022-05-26 17:33 UTC, Svetlana531 commented
@SHVlader дополнила тесты

2022-05-26 17:44 UTC, merged