Черный - Лабораторная работа #2
UNN-ITMM-Software/devtools-course-practice pull request #44
Opened 2022-03-29 18:21 UTC by Reloadif

2022-03-29 20:20 UTC, Reloadif commented
Реализовал шифр только для заглавных латинских букв.

2022-03-29 21:46 UTC, CheremshkinKI approved these changes

2022-03-30 07:26 UTC, dkurt commented
Please add your name at https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/topics.md

2022-03-30 19:58 UTC, MikhailZarubin requested changes

2022-03-30 19:58 UTC, MikhailZarubin commented on modules/chornyi-yura-vigenere/src/vigenere_cipher.cpp
> +    for (auto element : str) {
Лишняя операция копирования, хоть тут и не критично, так как идет работа с char. Но лучше const auto& делать

2022-03-30 19:58 UTC, MikhailZarubin commented on modules/chornyi-yura-vigenere/src/vigenere_cipher.cpp
> +        cipher << static_cast<char>(65 + (m_original[it] + m_key[it]) % 26);
Касаемо используемых литералов (здесь числа 65 и 26, а также на строке 10 числа 65 и 10) - лучше объявить их константами с "говорящим" названием, то есть необходимо описать, что они означают. Так читаемость кода повысится

2022-03-30 19:58 UTC, MikhailZarubin commented on modules/chornyi-yura-vigenere/test/test_vigenere_cipher.cpp
> +    ASSERT_NO_THROW(VigenereCipher());
В аннотации к тесту лучше указывать класс, то есть не просто Constructor, а VigenereCipherConstructor, например. Удобнее будет логи смотреть.

2022-03-30 20:43 UTC, Reloadif commented on modules/chornyi-yura-vigenere/test/test_vigenere_cipher.cpp
> +    ASSERT_NO_THROW(VigenereCipher());
Замечание учтено.

2022-03-30 20:44 UTC, Reloadif commented on modules/chornyi-yura-vigenere/src/vigenere_cipher.cpp
> +        cipher << static_cast<char>(65 + (m_original[it] + m_key[it]) % 26);
Замечание учтено.

2022-03-30 20:44 UTC, Reloadif commented
@SHVlader

2022-03-30 20:45 UTC, MikhailZarubin approved these changes

2022-04-08 17:59 UTC, merged