Lab 1
UNN-ITMM-Software/devtools-course-practice pull request #45
Opened 2024-03-23 12:58 UTC by Stepa123de

2024-03-23 19:11 UTC, Kuznetsov-Artyom requested changes

2024-03-23 19:11 UTC, Kuznetsov-Artyom commented on modules/complex-number/test/test_kashin_stepan_complex_number.cpp
> +}
Знакомый код, не так ли? :)  #37

2024-03-24 11:35 UTC, Stepa123de commented on modules/complex-number/test/test_kashin_stepan_complex_number.cpp
> +}
Согласен красивый код. Мне в строчку не нравятся #23. 
```TEST(ChuvashovAndreyTests, equalTest) {
    ASSERT_TRUE(ComplexNumber(0.1245, 1415.125) ==
        ComplexNumber(0.1245, 1415.125));
}

TEST(ChuvashovAndreyTests, notEqualTest) {
    ASSERT_TRUE(ComplexNumber(1241.6478, 2663.22) !=
        ComplexNumber(35743.15, 37326.2));
}```
Мне нужно местами поменять допустим 31 и 32 или 28 и 29 в одну строчку написать ?
Просто я хз, что можно написать такого, чтобы в equalTes все отличалось.

2024-03-24 13:10 UTC, Kuznetsov-Artyom commented on modules/complex-number/test/test_kashin_stepan_complex_number.cpp
> +}
> Согласен красивый код. Мне в строчку не нравятся #23.
> 
> ```
> TEST(ChuvashovAndreyTests, equalTest) {
>     ASSERT_TRUE(ComplexNumber(0.1245, 1415.125) ==
>         ComplexNumber(0.1245, 1415.125));
> }
> 
> TEST(ChuvashovAndreyTests, notEqualTest) {
>     ASSERT_TRUE(ComplexNumber(1241.6478, 2663.22) !=
>         ComplexNumber(35743.15, 37326.2));
> }
> ```
> 
> Мне нужно местами поменять допустим 31 и 32 или 28 и 29 в одну строчку написать ? Просто я хз, что можно написать такого, чтобы в equalTes все отличалось.

Делайте как хотите :), только одно условие — отсутствие 100% совпадения с чьим-то тестом, хотя бы значения поменяли.

2024-03-24 13:18 UTC, Stepa123de commented on modules/complex-number/test/test_kashin_stepan_complex_number.cpp
> +}
С легкостью лепестков на ветру, нежно приношу извинения за свою ошибку. Как звезды в ночном небе, мои слова мерцали неясно, и за это я глубоко сожалею. Дайте мне возможность исправить свою ошибку и вернуть в нашу взаимную гармонию. Пусть мирное спокойствие и понимание наполнят наши сердца, как ручей, бегущий сквозь лес, обновляя все на своем пути. Позвольте мне снова создать в наших отношениях яркую палитру радужных эмоций. Будьте любезны принять мои искренние извинения. 🌌🌿🌟

2024-03-24 13:21 UTC, Kuznetsov-Artyom commented on modules/complex-number/test/test_kashin_stepan_complex_number.cpp
Не могли бы ли вы добавить тесты с дробными значениями?

2024-03-24 13:37 UTC, Kuznetsov-Artyom commented
Спасибо 👍

2024-03-24 13:38 UTC, Kuznetsov-Artyom approved these changes

2024-03-24 13:38 UTC, merged