Соловьев А.Ю. 381806-1 ЛР1
UNN-ITMM-Software/devtools-course-practice pull request #59
Opened 2021-03-13 11:45 UTC by Alexandr-Solovev

### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [ ] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [ ] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [ ] Get two approve from your fellow students
- [ ] Take a review from one of the administrators

2021-03-13 11:58 UTC, taktaev-artyom requested changes

2021-03-13 11:58 UTC, taktaev-artyom commented on modules/complex-number/test/test_solovev_aleksandr_complex_number.cpp
> +    result = result * c2;
ComplexNumber result = c1 * c2;

2021-03-13 11:58 UTC, taktaev-artyom commented on modules/complex-number/test/test_solovev_aleksandr_complex_number.cpp
> +              result.getIm());
Можно упростить, посчитав значения этих выражений в отдельных переменных.

2021-03-13 12:19 UTC, Alexandr-Solovev commented on modules/complex-number/test/test_solovev_aleksandr_complex_number.cpp
> +              result.getIm());
Исправил

2021-03-13 12:19 UTC, Alexandr-Solovev commented on modules/complex-number/test/test_solovev_aleksandr_complex_number.cpp
> +    result = result * c2;
Исправил

2021-03-13 15:13 UTC, vlad-gogov requested changes

2021-03-13 15:13 UTC, vlad-gogov commented on modules/complex-number/test/test_solovev_aleksandr_complex_number.cpp
> +    EXPECT_EQ((c1.getIm() + c2.getIm()), result.getIm());
Лучше хранить контрольные значения в отдельных переменных

2021-03-13 15:22 UTC, MaksimShagov requested changes

2021-03-13 15:22 UTC, MaksimShagov commented on modules/complex-number/test/test_solovev_aleksandr_complex_number.cpp
> +}
Дубликат теста из мастера. https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/c146dbf31acc21be6506b4e6e89f07de06311086/modules/complex-number/test/test_shagov_maksim_complex_number.cpp#L25

2021-03-13 15:22 UTC, MaksimShagov commented on modules/complex-number/test/test_solovev_aleksandr_complex_number.cpp
> +    double resultIm = (c1.getRe() * c2.getIm()) + (c1.getIm() * c2.getRe());
Значения этих переменных стоит указать явно (поставить константы, а не использовать методы класса).

2021-03-13 15:40 UTC, Alexandr-Solovev commented on modules/complex-number/test/test_solovev_aleksandr_complex_number.cpp
> +    EXPECT_EQ((c1.getIm() + c2.getIm()), result.getIm());
испарвил

2021-03-13 15:43 UTC, Alexandr-Solovev commented on modules/complex-number/test/test_solovev_aleksandr_complex_number.cpp
> +    double resultIm = (c1.getRe() * c2.getIm()) + (c1.getIm() * c2.getRe());
не валидный комментарий, так как более приоритетным(на мой взгляд), является подсчет значений данных переменных, используя методы класса, а не калькулятор.

2021-03-13 15:43 UTC, Alexandr-Solovev commented on modules/complex-number/test/test_solovev_aleksandr_complex_number.cpp
> +}
исправил

2021-03-13 16:10 UTC, MaksimShagov commented on modules/complex-number/test/test_solovev_aleksandr_complex_number.cpp
> +    double resultIm = (c1.getRe() * c2.getIm()) + (c1.getIm() * c2.getRe());
Использование методов класса было бы приемлемо,возможно если бы был параметрический тест.

2021-03-13 20:40 UTC, WerWebWer commented
Для ускорения прохождения ревью вы можете пригласить сокурсников посмотреть ваш PR, упомянув их в комментариях 

[See more details]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

2021-03-14 07:08 UTC, Alexandr-Solovev commented on modules/complex-number/test/test_solovev_aleksandr_complex_number.cpp
> +    double resultIm = (c1.getRe() * c2.getIm()) + (c1.getIm() * c2.getRe());
@WerWebWer можешь подсказать, пожалуйста, стоит ли исправлять этот комментарий?

2021-03-14 07:31 UTC, WerWebWer commented on modules/complex-number/test/test_solovev_aleksandr_complex_number.cpp
> +    double resultIm = (c1.getRe() * c2.getIm()) + (c1.getIm() * c2.getRe());
Так как тест на проверку умножения, думаю разумно будет максимально абстрагироваться до проверки этой функции. Так что, думаю надо исправить.

2021-03-14 07:35 UTC, vla5924 commented on modules/complex-number/test/test_solovev_aleksandr_complex_number.cpp
> +    double resultIm = (c1.getRe() * c2.getIm()) + (c1.getIm() * c2.getRe());
Ну и в следующем тесте Test_Add аналогичная проблема

2021-03-14 07:36 UTC, WerWebWer commented on modules/complex-number/test/test_solovev_aleksandr_complex_number.cpp
> +    double resultIm = (c1.getRe() * c2.getIm()) + (c1.getIm() * c2.getRe());
С другой стороны, это получается плагиат теста, который уже в мастере. В таком случае предлагаю сделать параметрический тест на муножение
[Пример параметрического теста](https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/modules/complex-number/test/test_simple.cpp#L15)

2021-03-14 10:18 UTC, vla5924 approved these changes

2021-03-14 10:18 UTC, MaksimShagov approved these changes

2021-03-14 10:18 UTC, taktaev-artyom approved these changes
хорошо

2021-03-14 10:25 UTC, WerWebWer approved these changes
Отлично

2021-03-14 10:26 UTC, merged