Кудрявцев А. С. 381803-2 ЛР1
UNN-ITMM-Software/devtools-course-practice pull request #61
Opened 2021-03-13 14:14 UTC by MADZEROPIE

### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [ ] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [ ] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [ ] Get two approve from your fellow students
- [ ] Take a review from one of the administrators

2021-03-13 19:08 UTC, streltsova-yana commented
Необходимо пройти ревью кода от двух своих сокурсников из данной таблицы: https://docs.google.com/spreadsheets/d/11dxBeegDOpkStVuHZJgpatZV4HqxIkdf6H4gnRpclSM/edit#gid=0 Пригласите их к дискуссии, добавив в pull reqeust комментарий вида @github-name. 
Рецензия считается незавершенной, пока вы не получите два approve (Pull Request -> File chenged -> Review changes -> Approve -> Submit review) от коллег. Его наличие означает одобрение ваших изменений от них.
Также те, кто аппрувит пулл реквесты без оставления комментариев попадают в специальный список и могут иметь трудности с получением зачёта.

2021-03-14 11:49 UTC, Vodeneev approved these changes
Very nice code!

2021-03-15 12:21 UTC, MADZEROPIE commented
Что-то мне надоело висеть здесь.
@Iliamish выручай.

2021-03-15 15:03 UTC, Iliamish approved these changes

2021-03-15 15:43 UTC, streltsova-yana requested changes

2021-03-15 15:43 UTC, streltsova-yana commented on modules/complex-number/test/test_kudriavtsev_alexandr_complex_number.cpp
> +TEST(Kudriavtsev_Alexandr_ComplexNumberTest, Addition) {
Похожий [тест](https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/5f4d32d9d2c07d817115f7ade7fd68d73bdbbc74/modules/complex-number/test/test_gogov_vlad_complex_number.cpp#L7) уже есть в мастере. Можно попробовать поделить нулевое комплексное число на другое.

2021-03-15 15:43 UTC, streltsova-yana commented on modules/complex-number/test/test_kudriavtsev_alexandr_complex_number.cpp
> +    const double im2 = -500.5;
Перед переменными, объявленными как const, ставится префикс "k", за которым следует смешанный регистр. 
[See more details](https://google.github.io/styleguide/cppguide.html#Constant_Names)

2021-03-15 16:01 UTC, MADZEROPIE commented on modules/complex-number/test/test_kudriavtsev_alexandr_complex_number.cpp
> +TEST(Kudriavtsev_Alexandr_ComplexNumberTest, Addition) {
А можно просто удалить тест.

2021-03-15 16:03 UTC, MADZEROPIE commented on modules/complex-number/test/test_kudriavtsev_alexandr_complex_number.cpp
> +    const double im2 = -500.5;
Сомневаюсь, что здесь это нужно. Смысл немного другой.

2021-03-15 16:10 UTC, merged