lab2
UNN-ITMM-Software/devtools-course-practice pull request #66
Opened 2024-03-24 14:57 UTC by Stepa123de

2024-03-24 15:14 UTC, Kuznetsov-Artyom commented
Добавьте пожалуйста описание к вашему пр (чтоб понимать в чем заключалась ваша задача)

2024-03-24 17:20 UTC, Stepa123de commented
> Добавьте пожалуйста описание к вашему пр (чтоб понимать в чем заключалась ваша задача)

добавил

2024-03-24 17:23 UTC, Stepa123de commented
@Kuznetsov-Artyom Мне обязательно писать тесты для классов ошибок(codecov/patch)?
```
class TheStringDoesNotContainCharacters : public std::exception {
public:
    virtual const char* what() const noexcept {
        return "it was expected that the l"
               "ine would not be empty";
    }
};

class TheStringContainsNonLatinCharacters : public std::exception {
public:
    virtual const char* what() const noexcept {
        return "the string was expected to contain only Latin characters";
    }
};

class IncorrectKeyLength : public std::exception {
public:
    virtual const char* what() const noexcept {
        return "the key must be longer than 0 and less than the length of the text";
    }
};
```

2024-03-24 19:49 UTC, Kuznetsov-Artyom commented
> @Kuznetsov-Artyom Мне обязательно писать тесты для классов ошибок(codecov/patch)?
> 
> ```
> class TheStringDoesNotContainCharacters : public std::exception {
> public:
>     virtual const char* what() const noexcept {
>         return "it was expected that the l"
>                "ine would not be empty";
>     }
> };
> 
> class TheStringContainsNonLatinCharacters : public std::exception {
> public:
>     virtual const char* what() const noexcept {
>         return "the string was expected to contain only Latin characters";
>     }
> };
> 
> class IncorrectKeyLength : public std::exception {
> public:
>     virtual const char* what() const noexcept {
>         return "the key must be longer than 0 and less than the length of the text";
>     }
> };
> ```

Не нужно, вы и так много сделали:)

2024-03-24 19:51 UTC, Stepa123de commented
> Не нужно, вы и так много сделали:)

ну просто я написал все возможные тесты для этих классов , проверку все равно не проходит

2024-03-24 20:04 UTC, Kuznetsov-Artyom commented
> > Не нужно, вы и так много сделали:)
> 
> ну просто я написал все возможные тесты для этих классов , проверку все равно не проходит

Понял, завтра посмотрю и разберусь

2024-03-25 05:47 UTC, dkurt commented on modules/kashin_s_lab2/include/GronsfeldCipher.h
> +class TheStringDoesNotContainCharacters : public std::exception {
Зачем вам наследники от `std::exception`?

2024-03-25 05:48 UTC, dkurt commented on modules/kashin_s_lab2/include/GronsfeldCipher.h
> +class TheStringDoesNotContainCharacters : public std::exception {
Если вводите - создайте тест с `ASSERT_THROW` - иначе ветки с исключениями остаются не покрытыми

2024-03-25 08:12 UTC, FirewallGR commented on modules/kashin_s_lab2/test/test_kashin_s_gronsfeld_cipher.cpp
> +    EXPECT_STREQ(
Замени expect_streq на assert_throw

2024-03-25 10:51 UTC, dkurt commented on modules/kashin_s_lab2/test/test_kashin_s_gronsfeld_cipher.cpp
> +    EXPECT_STREQ(
Этого недостаточно - нужен тест который бросает исключение. Просто создать его как объект не имеет смысла - нужна ветка кода которая делает `throw` этого объекта.

2024-03-25 10:52 UTC, dkurt commented on modules/kashin_s_lab2/test/test_kashin_s_gronsfeld_cipher.cpp
> +    EXPECT_NO_THROW(TheStringContainsNonLatinCharacters().what());
проверка не имеет смысла

2024-03-25 10:53 UTC, Stepa123de commented on modules/kashin_s_lab2/test/test_kashin_s_gronsfeld_cipher.cpp
> +    EXPECT_NO_THROW(TheStringContainsNonLatinCharacters().what());
это делалось чтобы пройти тесты, все проверки которые осмысленны выше данного

2024-03-25 10:54 UTC, dkurt commented on modules/kashin_s_lab2/test/test_kashin_s_gronsfeld_cipher.cpp
> +    EXPECT_NO_THROW(TheStringContainsNonLatinCharacters().what());
Codecoverage имеете ввиду?

2024-03-25 10:54 UTC, Stepa123de commented on modules/kashin_s_lab2/test/test_kashin_s_gronsfeld_cipher.cpp
> +    EXPECT_NO_THROW(TheStringContainsNonLatinCharacters().what());
> Codecoverage имеете ввиду?

да

2024-03-25 10:57 UTC, dkurt commented on modules/kashin_s_lab2/test/test_kashin_s_gronsfeld_cipher.cpp
> +    EXPECT_NO_THROW(TheStringContainsNonLatinCharacters().what());
Давайте попробуем закомментировать перегрузки методов `what` - посмотрим что скажет coverage

2024-03-25 11:09 UTC, Stepa123de commented on modules/kashin_s_lab2/test/test_kashin_s_gronsfeld_cipher.cpp
> +    EXPECT_NO_THROW(TheStringContainsNonLatinCharacters().what());
> Давайте попробуем закомментировать перегрузки методов `what` - посмотрим что скажет coverage

прошло

2024-03-25 11:11 UTC, dkurt commented on modules/kashin_s_lab2/test/test_kashin_s_gronsfeld_cipher.cpp
> +    EXPECT_NO_THROW(TheStringContainsNonLatinCharacters().what());
Прелагаю тогда оставить без сообщений в `what` - разных наследников по типу исключений достаточно. Просто чтобы не тратить ваше время на поиск в чем проблема.

2024-03-25 11:11 UTC, dkurt commented
@Stepa123de, тегните двух студентов, чтобы они сделали вам ревью и поставили Approve. Например из списка https://unn-itmm-software.github.io/devtools-course-practice

2024-03-25 11:14 UTC, Stepa123de commented
@Kuznetsov-Artyom 
@Namxobick

2024-03-25 15:48 UTC, Kuznetsov-Artyom requested changes

2024-03-25 15:48 UTC, Kuznetsov-Artyom commented on modules/kashin_s_lab2/include/GronsfeldCipher.h
> +    //     return "изза тупых проверок codev тут этот текст";
LGTM, только напишите позитивный контекст, у вас это хорошо получается 🥇 
Либо уберите собственный класс исключения 😄

2024-03-25 16:47 UTC, dkurt commented on modules/kashin_s_lab2/include/GronsfeldCipher.h
> +    //     return "изза тупых проверок codev тут этот текст";
@Kuznetsov-Artyom , с текстом проблема покрытия тестами (нет времени разбираться почему), поэтому я предложил закомментировать для проверки. Тесты прошли, предлагаю классы оставить (полезно), но убрать комментированный код

2024-03-25 18:39 UTC, Kuznetsov-Artyom commented on modules/kashin_s_lab2/include/GronsfeldCipher.h
> +    //     return "изза тупых проверок codev тут этот текст";
@Stepa123de Уберите пожалуйста закомментированный код 😺

2024-03-25 20:44 UTC, Kuznetsov-Artyom approved these changes

2024-03-26 15:21 UTC, Namxobick reviewed
Имхо =)

2024-03-26 15:21 UTC, Namxobick commented on modules/kashin_s_lab2/src/GronsfeldCipher.cpp
> +    if (text == "") throw TheStringDoesNotContainCharacters();
Я бы использовал std::string::empty

2024-03-26 15:21 UTC, Namxobick commented on modules/kashin_s_lab2/src/GronsfeldCipher.cpp
> +    if (text == "") throw TheStringDoesNotContainCharacters();
Я бы использовал std::string::empty

2024-03-26 15:21 UTC, Namxobick commented on modules/kashin_s_lab2/src/GronsfeldCipher.cpp
> +    if (text == "") throw TheStringDoesNotContainCharacters();
Я бы использовал std::string::empty

2024-03-26 15:21 UTC, Namxobick commented on modules/kashin_s_lab2/include/GronsfeldCipher.h
> +    int first = 'a';
я бы переименовал переменную в  firstLetter или firstLetterInAlphabet и добавил бы const

2024-03-26 15:21 UTC, Namxobick commented on modules/kashin_s_lab2/include/GronsfeldCipher.h
> +    int alfabet = 26;
переименовал бы в alphabetSize и const

2024-03-26 15:21 UTC, Namxobick commented on modules/kashin_s_lab2/include/GronsfeldCipher.h
> +    std::unordered_map<char, double> letterFrequency = {
const

2024-03-26 15:21 UTC, Namxobick commented on modules/kashin_s_lab2/src/GronsfeldCipher.cpp
> +    if ('a' <= word && word <= 'z') {
вместо 'a' я бы использовал уже созданную переменную first
аналогично бы сделал с 'z'
а также бы вынес в отдельный метод (isLetterInAlphabet), т.к. это условия встречается ещё в коде и при изменении алфавита будет легче исправить

2024-03-26 15:21 UTC, Namxobick commented on modules/kashin_s_lab2/src/GronsfeldCipher.cpp
> +        word =  first + (word - code + 'z' + 1 - first) % 26;
есть переменная равная 26

2024-03-26 15:21 UTC, Namxobick commented on modules/kashin_s_lab2/src/GronsfeldCipher.cpp
> +    if (keyWord == "") throw TheStringDoesNotContainCharacters();
Я бы использовал std::string::empty

2024-03-26 15:21 UTC, Namxobick commented on modules/kashin_s_lab2/src/GronsfeldCipher.cpp
> +        if (!('a' <= keyWord[i] && keyWord[i] <= 'z')) {
выше писал об этом

2024-03-26 15:21 UTC, Namxobick commented on modules/kashin_s_lab2/src/GronsfeldCipher.cpp
> +    if ('a' <= word && word <= 'z') {
выше писал об этом

2024-03-26 15:21 UTC, Namxobick commented on modules/kashin_s_lab2/src/GronsfeldCipher.cpp
> +        if ('a' <= tolower(text[i]) && tolower(text[i]) <= 'z') {
выше писал об этом

2024-03-26 15:21 UTC, Namxobick commented on modules/kashin_s_lab2/src/GronsfeldCipher.cpp
> +    std::string answer = "";
Я бы написал так: std::string answer{};

2024-03-26 15:21 UTC, Namxobick commented on modules/kashin_s_lab2/src/GronsfeldCipher.cpp
> +    std::string answer = "";
std::string answer{};

2024-03-26 15:52 UTC, Namxobick commented on modules/kashin_s_lab2/include/GronsfeldCipher.h
> +    std::unordered_map<char, double> letterFrequency = {
Вообще можно избавиться от first и alfabet. У нас же есть std::unordered_map, можно использовать его методы

2024-03-26 15:54 UTC, Namxobick commented on modules/kashin_s_lab2/src/GronsfeldCipher.cpp
> +    if ('a' <= word && word <= 'z') {
а лучше, наверное, использовать unordered_map<Key,T,Hash,KeyEqual,Allocator>::contains

2024-03-26 16:32 UTC, Stepa123de commented on modules/kashin_s_lab2/src/GronsfeldCipher.cpp
> +    std::string answer = "";
Душнила

2024-03-26 17:10 UTC, Stepa123de commented
@Namxobick изменил

2024-03-27 18:44 UTC, Stepa123de commented
@FirewallGR можешь пж апрувнуть ?

2024-03-29 13:52 UTC, merged