Колесников Г. Р. 381803-2 ЛР1
UNN-ITMM-Software/devtools-course-practice pull request #72
Opened 2021-03-13 20:41 UTC by BrandonRTL

### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [ ] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [ ] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [ ] Get two approve from your fellow students
- [ ] Take a review from one of the administrators

2021-03-14 08:48 UTC, MADZEROPIE approved these changes
Ни к чему не могу докопаться. Кроме латыни. Латынь == зло.

2021-03-14 19:19 UTC, MADZEROPIE approved these changes
_**My job here is done**_

2021-03-15 15:03 UTC, dashachernyh approved these changes

2021-03-15 15:11 UTC, WerWebWer requested changes

2021-03-15 15:11 UTC, WerWebWer commented on modules/complex-number/test/test_kolesnikov_gleb_complex_number.cpp
> +TEST(Kolesnikov_Gleb_ComplexNumberTEST, Substract_number) {
Вижу похожий тест в #61, предлагаю кому-нибудь из вас сделать его параметрическим

2021-03-15 15:43 UTC, WerWebWer approved these changes

2021-03-15 15:43 UTC, merged

2021-03-15 16:03 UTC, dkurt commented
@MADZEROPIE, для удобства автора, оставляйте комментарии на конкретные строчки, чтобы было понятно.

Pull request page -> Files changed -> нажать на  "+":

![image](https://user-images.githubusercontent.com/25801568/111183570-16a49800-85c1-11eb-9ed9-f76b7f5d8f62.png)