Напылов Е.И. 381806-2 ЛР1
UNN-ITMM-Software/devtools-course-practice pull request #74
Opened 2021-03-13 21:08 UTC by Talesard

### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [ ] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [ ] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [ ] Get two approve from your fellow students
- [ ] Take a review from one of the administrators

2021-03-13 21:17 UTC, streltsova-yana commented
Необходимо пройти ревью кода от двух своих сокурсников из данной таблицы: https://docs.google.com/spreadsheets/d/11dxBeegDOpkStVuHZJgpatZV4HqxIkdf6H4gnRpclSM/edit#gid=0 Пригласите их к дискуссии, добавив в pull reqeust комментарий вида @ github-name.
Рецензия считается незавершенной, пока вы не получите два approve (Pull Request -> File chenged -> Review changes -> Approve -> Submit review) от коллег. Его наличие означает одобрение ваших изменений от них.
Также те, кто аппрувит пулл реквесты без оставления комментариев попадают в специальный список и могут иметь трудности с получением зачёта.

2021-03-15 18:22 UTC, Talesard commented
@OnlyDeniko @vla5924 @Alexandr-Solovev чекните пожалуйста

2021-03-15 19:20 UTC, vla5924 requested changes

2021-03-15 19:20 UTC, vla5924 commented on modules/complex-number/test/test_napylov_evgenii_complex_number.cpp
> +TEST(Napylov_Evgenii_ComplexNumberTest, Divide_by_real) {
Дубликат теста в мастере https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/9af8712ad7d955bb3da674a691f060504c5710fe/modules/complex-number/test/test_Belik_Julia_complex_number.cpp#L19

2021-03-15 19:33 UTC, OnlyDeniko requested changes

2021-03-15 19:33 UTC, OnlyDeniko commented on modules/complex-number/test/test_napylov_evgenii_complex_number.cpp
> +TEST(Napylov_Evgenii_ComplexNumberTest, Mult_by_conjugate) {
Дубликат теста в мастере

https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/9af8712ad7d955bb3da674a691f060504c5710fe/modules/complex-number/test/test_gogov_vlad_complex_number.cpp#L43

2021-03-15 19:33 UTC, OnlyDeniko commented on modules/complex-number/test/test_napylov_evgenii_complex_number.cpp
> +    EXPECT_NO_THROW(ComplexNumber num_inf(inf, inf));
Пожалуйста, помните об отличии ASSERT_* от EXPECT_* в Google Test. При провале условия в ASSERT тест прекращает выполнение и помечается как FAILED. При провале условия в EXPECT тест будет отмечен как FAILED, но продолжит проверки, если ещё есть в данном блоке. Рекомендуем использовать всегда ASSERT_*, чтобы исключить падения всей тестовой системы.
```suggestion
    ASSERT_NO_THROW(ComplexNumber num_inf(inf, inf));
```

2021-03-15 19:33 UTC, OnlyDeniko commented on modules/complex-number/test/test_napylov_evgenii_complex_number.cpp
> +TEST(Napylov_Evgenii_ComplexNumberTest, Divide_by_zero) {
Дубликат теста в мастере

https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/9af8712ad7d955bb3da674a691f060504c5710fe/modules/complex-number/test/test_taktaev_artem_complex_number.cpp#L7

2021-03-17 10:05 UTC, vla5924 approved these changes

2021-03-17 10:41 UTC, OnlyDeniko approved these changes

2021-03-17 10:42 UTC, merged