Зореев М.В. 381806-1 ЛР1
UNN-ITMM-Software/devtools-course-practice pull request #76
Opened 2021-03-14 12:21 UTC by BFDestroyeer

### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [ ] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [ ] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [ ] Get two approve from your fellow students
- [ ] Take a review from one of the administrators

2021-03-14 18:26 UTC, OnlyDeniko requested changes

2021-03-14 18:26 UTC, OnlyDeniko commented on modules/complex-number/test/test_zoreev_mikhail_complex_number.cpp
> +}
Подобный тест уже присутствует в мастере

2021-03-14 18:26 UTC, OnlyDeniko commented on modules/complex-number/test/test_zoreev_mikhail_complex_number.cpp
> +TEST(Zoreev_Mikhail_ComplexNumberTest, Summ_With_Opposite_Give_Zero) {
Подобный тест уже присутствует в мастере

2021-03-14 19:29 UTC, BFDestroyeer commented on modules/complex-number/test/test_zoreev_mikhail_complex_number.cpp
> +}
Тест заменён.

2021-03-14 19:29 UTC, BFDestroyeer commented on modules/complex-number/test/test_zoreev_mikhail_complex_number.cpp
> +TEST(Zoreev_Mikhail_ComplexNumberTest, Summ_With_Opposite_Give_Zero) {
Тест заменён.

2021-03-14 20:02 UTC, vla5924 approved these changes

2021-03-14 20:06 UTC, OnlyDeniko requested changes

2021-03-14 20:06 UTC, OnlyDeniko commented on modules/complex-number/test/test_zoreev_mikhail_complex_number.cpp
> +TEST(Zoreev_Mikhail_ComplexNumberTest, Equality_Transitivity) {
Я наблюдаю похожий тест в пул реквесте от Юлии Белик, разберитесь между собой кто будет менять тест.

2021-03-14 20:13 UTC, BFDestroyeer commented on modules/complex-number/test/test_zoreev_mikhail_complex_number.cpp
> +TEST(Zoreev_Mikhail_ComplexNumberTest, Equality_Transitivity) {
@OnlyDeniko 
Если вы про https://github.com/BelikJulia/devtools-course-practice/blob/5ec6e5e0d868ab15da7f26e92894104e1211348c/modules/complex-number/test/test_Belik_Julia_complex_number.cpp#L26 то тесты по смыслу совершенно разные, она тестирует корректность операции == я же проверяю выполнение свойства транзитивности для реализации этой операции.
Но вообще, т.к. у меня имеется 4 теста при требуемых 3, я могу этот тест у себя убрать, в том случае если не имеется иных претензий.

2021-03-14 20:18 UTC, OnlyDeniko commented on modules/complex-number/test/test_zoreev_mikhail_complex_number.cpp
> +TEST(Zoreev_Mikhail_ComplexNumberTest, Equality_Transitivity) {
Иных претензий не имеется. Убирайте тест и приглашайте второго одногруппника на ревью.

2021-03-14 20:27 UTC, taktaev-artyom approved these changes
Отличная идея использовать параметрические тесты

2021-03-14 20:28 UTC, BFDestroyeer commented on modules/complex-number/test/test_zoreev_mikhail_complex_number.cpp
> +TEST(Zoreev_Mikhail_ComplexNumberTest, Equality_Transitivity) {
@OnlyDeniko 
Исполнено

2021-03-15 04:32 UTC, OnlyDeniko approved these changes

2021-03-15 04:33 UTC, merged