Белик Ю.А. 381806-1 ЛР1
UNN-ITMM-Software/devtools-course-practice pull request #77
Opened 2021-03-14 16:21 UTC by BelikJulia

2021-03-14 17:04 UTC, ParanichevaAlyona commented on modules/complex-number/test/test_Belik_Julia_complex_number.cpp
> +    EXPECT_EQ((a * b).getRe(), 26);
Лучше завести отдельную переменную для проверки

2021-03-14 18:06 UTC, OnlyDeniko requested changes

2021-03-14 18:06 UTC, OnlyDeniko commented on modules/complex-number/test/test_Belik_Julia_complex_number.cpp
> +}
Такой тест уже есть

2021-03-14 18:11 UTC, OnlyDeniko commented on modules/complex-number/test/test_Belik_Julia_complex_number.cpp
> +}
Убери дублирование переменных. 
Попробуй сделать параметризированные тесты, пример здесь: https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/modules/complex-number/test/test_simple.cpp#L15

2021-03-15 07:23 UTC, BelikJulia commented on modules/complex-number/test/test_Belik_Julia_complex_number.cpp
> +    EXPECT_EQ((a * b).getRe(), 26);
Исправлено

2021-03-15 07:23 UTC, BelikJulia commented on modules/complex-number/test/test_Belik_Julia_complex_number.cpp
> +}
Исправлено

2021-03-15 07:24 UTC, BelikJulia commented on modules/complex-number/test/test_Belik_Julia_complex_number.cpp
> +}
Исправлено

2021-03-15 07:43 UTC, OnlyDeniko requested changes

2021-03-15 07:43 UTC, OnlyDeniko commented on modules/complex-number/test/test_Belik_Julia_complex_number.cpp
> +TEST(Belik_Julia_ComplexNumberTest, Conjugate_Numbers_Multiplication) {
Подобный тест уже есть: https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/modules/complex-number/test/test_gogov_vlad_complex_number.cpp#L43

2021-03-15 08:06 UTC, OnlyDeniko approved these changes

2021-03-15 08:07 UTC, OnlyDeniko reviewed
Напомню, что необходимо ревью второго студента

2021-03-15 08:12 UTC, SMolotkova approved these changes
Good job!

2021-03-15 08:14 UTC, ParanichevaAlyona approved these changes
Все хорошо)

2021-03-15 08:14 UTC, merged