Волкова А.Д. 381806-2 ЛР №1
UNN-ITMM-Software/devtools-course-practice pull request #79
Opened 2021-03-15 08:34 UTC by WolfCub15

### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [ ] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [ ] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [ ] Get two approve from your fellow students
- [ ] Take a review from one of the administrators

2021-03-15 09:20 UTC, WolfCub15 commented
@OnlyDeniko

2021-03-15 10:18 UTC, OnlyDeniko requested changes

2021-03-15 10:18 UTC, OnlyDeniko commented on modules/complex-number/test/test_volkova_nastya_complex_number.cpp
> +}
Данный тест уже есть в мастере. Можешь удалять, у тебя все равно 1 тест лишний

2021-03-15 10:42 UTC, OnlyDeniko approved these changes
LGTM

2021-03-15 10:42 UTC, OnlyDeniko reviewed
Пригласи кого-нибудь из студентов на ревью

2021-03-16 20:19 UTC, WolfCub15 commented
@WerWebWer

2021-03-16 20:53 UTC, WerWebWer commented
> @WerWebWer

@WolfCub15, к сожалению, я являюсь администратором и не могу ревьюить ваш код, до аппрувов двух ваших однокурсников, к тому же я не могу вмешаться в этот пр, так как он принадлежит @OnlyDeniko (из Assigness)

Вы можете найти кого-нибудь из [этой таблицы](https://docs.google.com/spreadsheets/d/11dxBeegDOpkStVuHZJgpatZV4HqxIkdf6H4gnRpclSM/edit?ts=603d0735&pli=1#gid=0), в ней отсутствуют администраторы

2021-03-16 22:21 UTC, WolfCub15 commented
@vla5924 посмотри, пожалуйста

2021-03-17 10:04 UTC, vla5924 requested changes

2021-03-17 10:04 UTC, vla5924 commented on modules/complex-number/test/test_volkova_nastya_complex_number.cpp
> +    EXPECT_EQ(res4, numb3);
ASSERT_EQ

2021-03-17 10:04 UTC, vla5924 commented on modules/complex-number/test/test_volkova_nastya_complex_number.cpp
> +    EXPECT_EQ(res3, res5);
ASSERT_EQ

2021-03-17 10:04 UTC, vla5924 commented on modules/complex-number/test/test_volkova_nastya_complex_number.cpp
> +TEST(Volkova_Nastya_ComplexNumberTest, AssignmentOperator) {
Название не очень подходящее, по-моему, поскольку в тесте не только оператор присваивания

2021-03-17 18:56 UTC, WerWebWer requested changes

2021-03-17 18:56 UTC, WerWebWer commented on modules/complex-number/test/test_volkova_nastya_complex_number.cpp
> +INSTANTIATE_TEST_CASE_P(/**/, Volkova_Parametrized, testing::Combine(
Вы уверены, что хотите использовать `Combine`? В данном случае образуется 64+64 теста

2021-03-17 20:30 UTC, WerWebWer approved these changes

2021-03-17 20:37 UTC, WolfCub15 commented on modules/complex-number/test/test_volkova_nastya_complex_number.cpp
> +    EXPECT_EQ(numb1.getIm(), numb3.getIm());
@vla5924  все исправлено

2021-03-18 18:54 UTC, vla5924 approved these changes

2021-03-18 19:12 UTC, merged