Пронькин Д.А. 381806-1 ЛР №1
UNN-ITMM-Software/devtools-course-practice pull request #83
Opened 2021-03-15 17:05 UTC by r01and3

### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [ ] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [ ] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [ ] Get two approve from your fellow students
- [ ] Take a review from one of the administrators

2021-03-15 17:28 UTC, Alexandr-Solovev commented on modules/complex-number/test/test_pronkin_dmitry_complex_number.cpp
> +    ComplexNumber* z = new ComplexNumber(re, im);
отсутствует оператор delete

2021-03-15 17:28 UTC, Alexandr-Solovev commented on modules/complex-number/test/test_pronkin_dmitry_complex_number.cpp
> +    testing::Combine(
форматирование поехало

2021-03-15 17:28 UTC, Alexandr-Solovev commented on modules/complex-number/test/test_pronkin_dmitry_complex_number.cpp
> +    testing::Combine(
форматирование поехало

2021-03-15 18:55 UTC, taktaev-artyom commented on modules/complex-number/test/test_pronkin_dmitry_complex_number.cpp
> +    ASSERT_DOUBLE_EQ(result.getIm(), z1.getIm());
1. Обычно, порядок параметров функции ASSERT таков: контрольное значение, затем экспериментальное, у тебя они расположены в ином порядке.
2. В качестве первого(контрольного) параметра теста следовало бы использовать уже полученные функцией std::get значения вместо вызова метода get класса ComplexNumber для его повторного получения.

2021-03-15 18:55 UTC, taktaev-artyom commented on modules/complex-number/test/test_pronkin_dmitry_complex_number.cpp
> +    ASSERT_EQ(z->getIm(), im);
Обычно, порядок параметров функции ASSERT таков: контрольное значение, затем экспериментальное, у тебя они расположены в ином порядке.

2021-03-15 19:10 UTC, vla5924 commented on modules/complex-number/test/test_pronkin_dmitry_complex_number.cpp
> +    testing::Combine(
@Alexandr-Solovev и где оно поехало? Всё тут нормально

2021-03-15 19:12 UTC, vla5924 commented on modules/complex-number/test/test_pronkin_dmitry_complex_number.cpp
> +    testing::Combine(
https://github.com/UNN-ITMM-Software/devtools-course-practice/pull/83#discussion_r594613037

2021-03-15 19:17 UTC, taktaev-artyom commented on modules/complex-number/test/test_pronkin_dmitry_complex_number.cpp
> +    testing::Combine(
@Alexandr-Solovev и этот человек представляет Intel Corporation...

2021-03-15 19:22 UTC, vla5924 commented on modules/complex-number/test/test_pronkin_dmitry_complex_number.cpp
> +    ComplexNumber* z = new ComplexNumber(re, im);
(Возможно, хорошей практикой здесь было бы использование `std::unique_ptr`)

2021-03-15 19:25 UTC, vla5924 commented on modules/complex-number/test/test_pronkin_dmitry_complex_number.cpp
> +    testing::Combine(
@taktaev-artyom Ох, и не говори...

2021-03-15 20:29 UTC, taktaev-artyom approved these changes
Супер класс

2021-03-15 20:34 UTC, vla5924 approved these changes

2021-03-16 08:23 UTC, streltsova-yana requested changes

2021-03-16 08:23 UTC, streltsova-yana commented on modules/complex-number/test/test_pronkin_dmitry_complex_number.cpp
> +TEST_P(Pronkin_Dmitry_ComplexNumberTest_Parametrized_2,
Похожий [тест](https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/300acb58c959fc50e50325e196ca4317c6c43607/modules/complex-number/test/test_rustamov_azer_complex_number.cpp#L23) уже есть в мастере

2021-03-16 08:23 UTC, streltsova-yana commented on modules/complex-number/test/test_pronkin_dmitry_complex_number.cpp
> +  testing::Values(1.3, 7.5, 4.8, 8.0)
Поскольку используется Combine - это декартово произведение (всевозможные комбинации из набора параметров) тесты будут запускаться не два раза, а 16. Точно ли ожидается такое поведение?

2021-03-16 08:23 UTC, streltsova-yana commented on modules/complex-number/test/test_pronkin_dmitry_complex_number.cpp
> +  testing::Values(3.0, 3.0, 3.0, 3.0)
В данном случае тесты будут запускаться 256 раз, а не 4, а это очень много.
![VlWKoHCX-p0](https://user-images.githubusercontent.com/43129466/111277587-af7ef600-8649-11eb-8f07-b2d9f43f4859.jpg)

2021-03-16 10:20 UTC, dkurt commented on modules/complex-number/test/test_pronkin_dmitry_complex_number.cpp
> +  testing::Values(1.3, 7.5, 4.8, 8.0)
Я бы перефразировал в утверждение :) Нужно убрать Combine

2021-03-16 18:39 UTC, r01and3 commented on modules/complex-number/test/test_pronkin_dmitry_complex_number.cpp
> +#include "include/complex_number.h"
Исправил

2021-03-16 18:40 UTC, r01and3 commented on modules/complex-number/test/test_pronkin_dmitry_complex_number.cpp
> +TEST_P(Pronkin_Dmitry_ComplexNumberTest_Parametrized_2,
Поменял на другой тест

2021-03-16 18:40 UTC, r01and3 commented on modules/complex-number/test/test_pronkin_dmitry_complex_number.cpp
> +  testing::Values(1.3, 7.5, 4.8, 8.0)
Исправил

2021-03-16 18:40 UTC, r01and3 commented on modules/complex-number/test/test_pronkin_dmitry_complex_number.cpp
> +  testing::Values(3.0, 3.0, 3.0, 3.0)
И это тоже исправил)

2021-03-16 18:55 UTC, streltsova-yana approved these changes

2021-03-16 18:56 UTC, merged