Черных Д. А. 381803-2 ЛР1
UNN-ITMM-Software/devtools-course-practice pull request #84
Opened 2021-03-15 18:14 UTC by dashachernyh

### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [ ] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [ ] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [ ] Get two approve from your fellow students
- [ ] Take a review from one of the administrators

2021-03-15 18:29 UTC, BrandonRTL approved these changes
Хорошая программа и тесты интересные, но может во втором тесте сумму произведений вынести в отдельную переменную для большей читаемости?

2021-03-15 19:18 UTC, WerWebWer commented
> 
> 
> Хорошая программа и тесты интересные, но может во втором тесте сумму произведений вынести в отдельную переменную для большей читаемости?

@BrandonRTL, для удобства, прошу оставляйте комментарий у строк кода, автору и всем остальным, думаю, будет удобнее и нагляднее понимать о чем идет речь

2021-03-15 19:29 UTC, MADZEROPIE approved these changes
Замечание от мистера ~~Брауна~~ Брэндона выше, а так сойдет.

2021-03-15 19:31 UTC, BrandonRTL commented
Ящитаю, надо ввести санкции для MADZEROPIE  за коверкание ников и неувожительное отношение к сокурсникам.

2021-03-16 09:12 UTC, WerWebWer requested changes
Могу предложить в некоторых добавить параметризацию или добавить рандом

2021-03-16 09:12 UTC, WerWebWer commented on modules/complex-number/test/test_chernyh_daria_complex_number.cpp
> +TEST(Chernyh_Daria_ComplexNumberTEST, Multiply_of_conjugate) {
Такой же тест уже в мастере 
https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/300acb58c959fc50e50325e196ca4317c6c43607/modules/complex-number/test/test_rustamov_azer_complex_number.cpp#L23

2021-03-16 09:27 UTC, dashachernyh commented on modules/complex-number/test/test_chernyh_daria_complex_number.cpp
> +TEST(Chernyh_Daria_ComplexNumberTEST, Not_equality_of_conjugate) {
Там сравнение просто неравных чисел, я проверяла неравенство именно сопряженных

2021-03-16 09:30 UTC, WerWebWer commented on modules/complex-number/test/test_chernyh_daria_complex_number.cpp
> +TEST(Chernyh_Daria_ComplexNumberTEST, Not_equality_of_conjugate) {
Действительно, тест подходит

2021-03-16 11:08 UTC, WerWebWer approved these changes

2021-03-16 11:08 UTC, merged

2021-03-16 13:27 UTC, dkurt commented
@dashachernyh, Проверьте настройки `~/.gitconfig` файла - ваши коммиты анонимны <img src="https://user-images.githubusercontent.com/25801568/111316449-524c6a00-8674-11eb-9059-4620a9a26d85.png" width="16">. Чтобы исправить, нужно указать email такой же, как в GitHub аккаунте.