Ногин Денис лаба 2
UNN-ITMM-Software/devtools-course-practice pull request #86
Opened 2024-03-26 17:09 UTC by Gr0miLa

Здесь реализован шифр Виженера со стандартным сдвигом ROT0, шифрующий символы латинского алфавита

2024-03-26 17:50 UTC, Gr0miLa commented
@Kuznetsov-Artyom
@FirewallGR

2024-03-26 18:19 UTC, Kuznetsov-Artyom requested changes

2024-03-26 18:19 UTC, Kuznetsov-Artyom commented on modules/nogin-d-vigenere-cipher/include/vigenere_cipher.h
> +std::string vigenereCipher(std::string data, std::string key);
Пожалуйста, передайте строки как const ref если строка не будет никаким образом видоизменяться (аналогично в других методах).

2024-03-26 18:19 UTC, Kuznetsov-Artyom commented on modules/nogin-d-vigenere-cipher/src/vigenere_cipher.cpp
> +              << new_symbol << std::endl;
Дебаг информацию (логирование) лучше убрать или закомментировать (аналогично в других местах)

2024-03-26 18:19 UTC, Kuznetsov-Artyom commented on modules/nogin-d-vigenere-cipher/include/vigenere_cipher.h
> +#define MODULES_NOGIN_D_VIGENERE_CIPHER_INCLUDE_VIGENERE_CIPHER_H_
```suggestion
#ifndef MODULES_NOGIN_D_VIGENERE_CIPHER_INCLUDE_VIGENERE_CIPHER_H_
#define MODULES_NOGIN_D_VIGENERE_CIPHER_INCLUDE_VIGENERE_CIPHER_H_

#include <algorithm>
#include <iostream>
#include <string>
```

2024-03-26 18:19 UTC, Kuznetsov-Artyom commented on modules/nogin-d-vigenere-cipher/include/vigenere_cipher.h
> +#define MODULES_NOGIN_D_VIGENERE_CIPHER_INCLUDE_VIGENERE_CIPHER_H_
Подключение заголовков должно быть в теле header guards (либо используйте `#pragma once` после копирайта)

2024-03-26 18:19 UTC, Kuznetsov-Artyom commented on modules/nogin-d-vigenere-cipher/src/vigenere_cipher.cpp
> +          new_symbol -= 26;
Можете пожалуйста как-нибудь задокументировать ваши магические числа 65 122 и так далее? Как вариант, можно вынести все константы в отдельное пространство имен:
``` cpp
// src.cpp
namespace constants {
extern const int varConstant = 123;
}

// hdr.h
namespace constants {
extern const int varConstant;
}
```

2024-03-26 19:00 UTC, Gr0miLa commented
@Kuznetsov-Artyom Готово

2024-03-26 19:02 UTC, Kuznetsov-Artyom approved these changes
Спасибо за внесенные изменения

2024-03-29 13:55 UTC, Gr0miLa commented
@Manymoera

2024-03-29 13:56 UTC, Manymoera commented
LGTM

2024-03-29 13:57 UTC, merged