Воденеев М.В. 381803-2 ЛР1
UNN-ITMM-Software/devtools-course-practice pull request #88
Opened 2021-03-16 07:13 UTC by Vodeneev

### Pull Request Readiness Checklist

See details at [code review]( https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/main/lab-guide/lab-1-setup.md#%D1%80%D0%B5%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F-%D0%BA%D0%BE%D0%B4%D0%B0)

- [ ] Code is well documented and more information can be seen on the [website](https://devtools-course-practice-2021.readthedocs.io/en/latest/modules.html) (recommended)
- [ ] Make sure that the testing has passed successfully on [GitHub Actions](https://github.com/UNN-ITMM-Software/devtools-course-practice/actions)
- [ ] Get two approve from your fellow students
- [ ] Take a review from one of the administrators

2021-03-16 07:18 UTC, streltsova-yana commented
Необходимо обновить мастер

2021-03-16 11:35 UTC, MADZEROPIE commented on modules/complex-number/test/test_VODENEEV_MIKHAIL_complex_number.cpp
> +    EXPECT_EQ(z1, z2);
Здесь и ниже заменить на ASSERT_EQ

2021-03-16 11:36 UTC, MADZEROPIE commented on modules/complex-number/test/test_VODENEEV_MIKHAIL_complex_number.cpp
> +    EXPECT_EQ(res.getRe(), 3);
Здесь и далее. Сначала expected, потом actual. (поменять местами)

2021-03-17 16:13 UTC, Vodeneev commented
@MADZEROPIE @alxndrvna

2021-03-17 16:37 UTC, MADZEROPIE approved these changes
_**My job here is done**_
Оставляю всё на тебя, @WerWebWer. (Если ты понимаешь, о чем я.) Не подведи.

2021-03-17 18:01 UTC, alxndrvna commented
@Vodeneev 
Хорошие тесты.

2021-03-17 18:04 UTC, alxndrvna approved these changes

2021-03-17 19:06 UTC, streltsova-yana requested changes

2021-03-17 19:06 UTC, streltsova-yana commented on modules/complex-number/test/test_VODENEEV_MIKHAIL_complex_number.cpp
> +TEST(Vodeneev_Mikhail_ComplexNumberTest, Setter) {
Похожие [тест1](https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/2cacbe6345f89b2401e496ea8bc3524963d8ada0/modules/complex-number/test/test_vlasov_maksim_complex_number.cpp#L29) и [тест2](https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/2cacbe6345f89b2401e496ea8bc3524963d8ada0/modules/complex-number/test/test_vlasov_maksim_complex_number.cpp#L38) уже есть в мастере

2021-03-17 19:06 UTC, streltsova-yana commented on modules/complex-number/test/test_VODENEEV_MIKHAIL_complex_number.cpp
> +TEST(Vodeneev_Mikhail_ComplexNumberTest, Comparison) {
Похожий тест уже есть в мастере, как в [параметрическом](https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/2cacbe6345f89b2401e496ea8bc3524963d8ada0/modules/complex-number/test/test_Belik_Julia_complex_number.cpp#L35), так и в [обычном](https://github.com/UNN-ITMM-Software/devtools-course-practice/blob/2cacbe6345f89b2401e496ea8bc3524963d8ada0/modules/complex-number/test/test_solovev_aleksandr_complex_number.cpp#L8) видах

2021-03-17 19:06 UTC, streltsova-yana commented on modules/complex-number/test/test_VODENEEV_MIKHAIL_complex_number.cpp
> +    EXPECT_EQ(z1, z2);
Необходимо заменить везде EXPECT_* на ASSERT_*

2021-03-17 20:00 UTC, streltsova-yana approved these changes

2021-03-17 20:00 UTC, merged