Сафаров Нурлан. Лабораторная работа №2.
UNN-ITMM-Software/devtools-course-practice pull request #91
Opened 2024-03-26 22:31 UTC by safarov-nm

Цель 2 л/р — реализовать алгоритм интерполяционного поиска. Функция int interpolationSearch(const std::vector &sequence, const int &target) принимает на вход два параметра: отсортированный по неубыванию массив чисел и элемент (число), который необходимо найти в данном массиве. Если элемент будет найден в этом массиве, функция вернёт его индекс, иначе — -1. Для того, чтобы проверить эту функцию на корректность работы, были написаны 5 тестов.

Эпилог. Если вы заблудились в лесу, идите домой.

2024-03-28 20:06 UTC, safarov-nm commented
@Kuznetsov-Artyom

2024-03-28 21:19 UTC, Kuznetsov-Artyom requested changes

2024-03-28 21:19 UTC, Kuznetsov-Artyom commented on modules/safarov_n_interpolation_search/src/interpolation_search.cpp
> +        return -1;
Можете пожалуйста задокументировать константу `-1`  дав ей какое-то конкретное имя?

2024-03-28 21:19 UTC, Kuznetsov-Artyom commented on modules/safarov_n_interpolation_search/test/test_interpolation_search.cpp
> +    std::vector<int> v = {1, 3, 5, 7, 9};
```suggestion
    std::vector<int> v{1, 3, 5, 7, 9};
```

2024-03-28 21:19 UTC, Kuznetsov-Artyom commented on modules/safarov_n_interpolation_search/test/test_interpolation_search.cpp
> +    std::vector<int> v = {1, 3, 5, 7, 9};
Пожалуйста, сделайте так и в других местах

2024-03-28 21:19 UTC, Kuznetsov-Artyom commented on modules/safarov_n_interpolation_search/test/test_interpolation_search.cpp
Добавьте пожалуйста рандомные тесты на малых и больших диапазонах. В качестве проверки работоспособности можете реализовать другой метод поиска или использовать возможности стандартной библиотеки.

Пример:
```cpp
template<typename T>
auto findPosElem(const std::vector<T>& vec, const T& elem) {
  return std::distance(vec.cbegin(), std::find(vec.cbegin(), vec.cend(), elem));
}
```

2024-04-01 21:46 UTC, safarov-nm commented
@Kuznetsov-Artyom

2024-04-01 21:47 UTC, safarov-nm commented
Готово.

2024-04-02 00:53 UTC, Kuznetsov-Artyom reviewed
А тест на большом диапазоне?

2024-04-02 11:25 UTC, safarov-nm commented
Так-с. Забыл. Добавлю.

2024-04-02 15:27 UTC, safarov-nm commented
@Kuznetsov-Artyom

2024-04-02 15:28 UTC, safarov-nm commented
Добавил.

2024-04-02 15:40 UTC, Kuznetsov-Artyom approved these changes

2024-04-07 19:27 UTC, Kuznetsov-Artyom commented
Тегните одного любого студента из [списка,](https://unn-itmm-software.github.io/devtools-course-practice) чтобы он провел код ревью.

2024-04-17 12:46 UTC, FirewallGR approved these changes

2024-04-17 12:46 UTC, merged

2024-04-17 23:12 UTC, safarov-nm commented
Тегнул, так сказать, силой мысли.