lab1: Morgachev Stepan
UNN-ITMM-Software/devtools-course-practice pull request #98
Opened 2024-03-27 18:35 UTC by MorgachevStepan

1. Тест геттера
2. Тест сеттера
3-6. Тесты арифметических операций (+, -, *, \)
7-8. Тесты оператора ==

2024-03-27 20:18 UTC, Kuznetsov-Artyom approved these changes

2024-03-29 15:39 UTC, FirewallGR commented
Добавьте пожалуйста проверку деления на 0

2024-03-29 15:40 UTC, FirewallGR requested changes
Добавьте пожалуйста проверку деления на 0

2024-03-31 05:17 UTC, FirewallGR approved these changes

2024-03-31 05:17 UTC, merged